(import (scheme base) (scheme write) (srfi 69))
;; string/fixnum-keyed hash table churn: insert, update, delete
(define t (make-hash-table equal?))
(let loop ((i 0))
  (when (< i 20000)
    (hash-table-set! t i (list i (* i i)))
    (loop (+ i 1))))
(let loop ((r 0))
  (when (< r 5)
    (let inner ((i 0))
      (when (< i 20000)
        (hash-table-update!/default t i (lambda (v) (cons r v)) '())
        (inner (+ i 1))))
    (loop (+ r 1))))
(display (length (hash-table-ref/default t 77 '()))) (newline)
