(import (scheme base) (scheme write))
;; in-place quicksort over a vector of pairs (heap values) and of fixnums
(define (qsort! v lo hi key)
  (if (< lo hi)
      (let ((p (key (vector-ref v hi))))
        (let loop ((i lo) (j lo))
          (if (< j hi)
              (if (< (key (vector-ref v j)) p)
                  (let ((t (vector-ref v i)))
                    (vector-set! v i (vector-ref v j))
                    (vector-set! v j t)
                    (loop (+ i 1) (+ j 1)))
                  (loop i (+ j 1)))
              (let ((t (vector-ref v i)))
                (vector-set! v i (vector-ref v hi))
                (vector-set! v hi t)
                (qsort! v lo (- i 1) key)
                (qsort! v (+ i 1) hi key)))))))
(define n 20000)
(define (rnd s) (modulo (+ (* s 1103515245) 12345) 2147483648))
(define vp (make-vector n #f))
(define vf (make-vector n 0))
(let loop ((i 0) (s 42))
  (when (< i n)
    (vector-set! vp i (cons (modulo s 100000) i))
    (vector-set! vf i (modulo s 100000))
    (loop (+ i 1) (rnd s))))
;; age the vectors: allocate garbage
(let loop ((i 0) (acc '())) (if (< i 200000) (loop (+ i 1) (if (= 0 (modulo i 1000)) '() (cons i acc))) #t))
(qsort! vp 0 (- n 1) car)
(qsort! vf 0 (- n 1) (lambda (x) x))
(display (car (vector-ref vp 0))) (newline)
