(define DEPTH (string->number (cadr (command-line))))
(define SECONDS (string->number (caddr (command-line))))
(define (deep n) (if (= n 0) 0 (+ 1 (deep (- n 1)))))
(display (deep DEPTH)) (newline)
(define start (real-time))
(let loop ((i 0) (acc '()))
  (if (> (- (real-time) start) (* SECONDS 1000))
      (begin (display i) (newline))
      (loop (+ i 1) (if (= 0 (modulo i 1000)) '() (cons i acc)))))
