(define N (string->number (cadr (command-line))))
(let loop ((i 0) (acc 0))
  (if (< i N)
      (let* ((e (environment '(rnrs base)))
             (g (eval '(lambda (x) (* x 2)) e)))
        (loop (+ i 1) (+ acc (g 21))))
      (begin (display acc) (newline))))
