(define LEN (string->number (cadr (command-line))))
(define SECONDS (string->number (caddr (command-line))))
(define (build n) (let loop ((i 0) (acc '())) (if (= i n) acc (loop (+ i 1) (cons (vector i i) acc)))))
(define big (build LEN))
(display (length big)) (newline)
(set! big #f)
(define start (real-time))
(let loop ((i 0) (acc '()))
  (if (> (- (real-time) start) (* SECONDS 1000))
      (begin (display i) (newline))
      (loop (+ i 1) (if (= 0 (modulo i 1000)) '() (cons i acc)))))
