(define N (string->number (cadr (command-line))))
(let loop ((i 0) (acc 0))
  (if (< i N)
      (let-values (((out get) (open-string-output-port)))
        (write (list i "abc" 'sym (vector 1 2 3)) out)
        (let* ((s (get))
               (in (open-string-input-port s))
               (d (read in)))
          (close-port in)
          (close-port out)
          (loop (+ i 1) (+ acc (car d)))))
      (begin (display acc) (newline))))
