(define N (string->number (cadr (command-line))))
(define env (interaction-environment))
(let loop ((i 0))
  (when (< i N)
    (eval (list 'lambda '() (string->symbol (string-append "unbound-" (number->string i)))) env)
    (loop (+ i 1))))
(display 'done) (newline)
