(import (scheme base) (scheme eval) (scheme repl) (scheme write)
        (scheme process-context))
(define n (string->number (cadr (command-line))))
(define form '(guard (e (#t 0)) (raise 'x)))
(let loop ((i 0))
  (when (< i n)
    (eval form (interaction-environment))
    (loop (+ i 1))))
(write (eval form (interaction-environment)))
(newline)
