(import (scheme base) (scheme write) (patina debug))
(define (syms) (cdr (assq 'symbols (gc-stats))))
(define s0 (syms))
(guard (e (#t 0)) (raise 'x))
(define s1 (syms))
(guard (e (#t 0)) (raise 'x))
(define s2 (syms))
(guard (e ((symbol? e) 0)) (raise 'x))
(define s3 (syms))
(write (list s0 s1 s2 s3)) (newline)
(write (gc-stats)) (newline)
