(import (scheme base) (scheme write) (scheme eval) (scheme repl) (scheme process-context))
(define N (string->number (cadr (command-line))))
(define env (interaction-environment))
(define keep '())
(let loop ((i 0))
  (when (< i N)
    (eval '(import (scheme char) (scheme list)) env)
    (set! keep (cons (make-bytevector 1000 0) keep))
    (loop (+ i 1))))
(display (length keep)) (newline)
