//! Pass 2 — Closure Conversion
//!
//! Transforms `CoreExpr` into `ClosedExpr` by making all free-variable
//! captures explicit. After this pass every `ClosedLambda` knows exactly
//! which variables it captures (in stable order) and in what slot they live.
//!
//! The `capture_list` on a `ClosedLambda` is a `Vec<Symbol>` of the variables
//! that must be copied from the enclosing environment when `MakeClosure` runs.
//! The slot index of each captured variable is its index in this list — used
//! by `LoadClosure` / `StoreClosure` in the generated bytecode.
//!
//! **Mutable captures (A3+):** Variables that appear in `AnalysisInfo::mutated`
//! *and* are captured across a lambda boundary need `MutableCell` boxing.
//! In A2 we detect them but emit a plain `Box`/`Unbox` annotation that Pass 5
//! will lower later. For now the codegen (A2) only lowers non-mutated captures.
//!
//! See VM_COMPILER.md §Pass 2.

use super::pass1_analysis::{AnalysisInfo, NodeId};
use patina_core::core_expr::{CoreExpr, CoreExprKind, Formals, Symbol};
use patina_core::tagged_value::TaggedValue;

// ─────────────────────────────────────────────────────────────────────────────
// ClosedExpr — the output IR of Pass 2
// ─────────────────────────────────────────────────────────────────────────────

/// A closure-converted expression.
#[derive(Debug, Clone)]
pub enum ClosedExpr {
    Literal(TaggedValue),
    Quote(TaggedValue),
    Quasiquote(TaggedValue),

    /// Reference to a locally-bound parameter register.
    LocalRef(Symbol),

    /// Reference to a captured free variable (slot index into closure).
    ClosureRef {
        name: Symbol,
        slot: u16,
    },

    /// Reference to a global variable.
    GlobalRef(Symbol),

    /// Closure-converted lambda.
    Lambda(Box<ClosedLambda>),

    If {
        test: Box<ClosedExpr>,
        then: Box<ClosedExpr>,
        else_: Box<ClosedExpr>,
    },

    /// `set!` on a local (non-captured) variable.
    SetLocal {
        var: Symbol,
        value: Box<ClosedExpr>,
    },

    /// `set!` on a captured variable (writes through a `MutableCell`).
    SetClosure {
        var: Symbol,
        slot: u16,
        value: Box<ClosedExpr>,
    },

    /// `set!` on a global.
    SetGlobal {
        var: Symbol,
        value: Box<ClosedExpr>,
    },

    Begin(Vec<ClosedExpr>),

    /// Top-level `define`.
    Define {
        name: Symbol,
        value: Box<ClosedExpr>,
    },

    App {
        func: Box<ClosedExpr>,
        args: Vec<ClosedExpr>,
    },

    Apply {
        func: Box<ClosedExpr>,
        args: Vec<ClosedExpr>,
    },
}

/// A closure-converted lambda.
#[derive(Debug, Clone)]
pub struct ClosedLambda {
    /// Parameters of this lambda (names in the callee's scope).
    pub params: Vec<Symbol>,
    /// Whether the last parameter is a rest parameter (collects extra args).
    pub rest_param: bool,
    /// Variables captured from the enclosing environment, in slot order.
    /// `capture_list[i]` is the name of the variable in slot `i`.
    pub capture_list: Vec<Symbol>,
    /// The body after closure conversion, with all variable references resolved
    /// to `LocalRef`, `ClosureRef`, or `GlobalRef`.
    pub body: Vec<ClosedExpr>,
    /// Monotonic id assigned by Pass 1.
    pub node_id: NodeId,
}

// ─────────────────────────────────────────────────────────────────────────────
// Conversion context
// ─────────────────────────────────────────────────────────────────────────────

/// Describes where a variable is currently bound from the perspective of the
/// expression being converted.
#[derive(Debug, Clone)]
enum VarLoc {
    /// Bound as a parameter in the current lambda's register window.
    Local,
    /// Captured from the enclosing closure at `slot`.
    Closure(u16),
    /// Unresolved at this level — may be global or bound by an outer lambda.
    Global,
}

/// Conversion state threaded through the pass.
struct Ctx<'a> {
    /// Analysis info from Pass 1.
    analysis: &'a AnalysisInfo,
    /// NodeId counter (mirrors the assignment order in Pass 1).
    counter: u32,
    /// Stack of enclosing scopes (innermost last).
    /// Each entry: list of (name, VarLoc) pairs for one lambda's bindings.
    scopes: Vec<Vec<(Symbol, VarLoc)>>,
}

impl<'a> Ctx<'a> {
    fn new(analysis: &'a AnalysisInfo) -> Self {
        Self {
            analysis,
            counter: 0,
            scopes: vec![],
        }
    }

    /// Allocate the next NodeId (must match Pass 1's pre-order assignment).
    fn next_node_id(&mut self) -> NodeId {
        let id = NodeId(self.counter);
        self.counter += 1;
        id
    }

    /// Look up a variable name in the current scope stack.
    fn lookup(&self, name: &Symbol) -> VarLoc {
        // Search from innermost scope outward.
        for scope in self.scopes.iter().rev() {
            for (bound_name, loc) in scope.iter().rev() {
                if bound_name == name {
                    return loc.clone();
                }
            }
        }
        VarLoc::Global
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Pass entry point
// ─────────────────────────────────────────────────────────────────────────────

pub struct Pass2Closure;

impl Pass2Closure {
    pub fn run(expr: &CoreExpr, analysis: &AnalysisInfo) -> ClosedExpr {
        let mut ctx = Ctx::new(analysis);
        convert(expr, &mut ctx)
    }
}

fn convert(expr: &CoreExpr, ctx: &mut Ctx<'_>) -> ClosedExpr {
    match &expr.kind {
        CoreExprKind::Literal(v) => ClosedExpr::Literal(*v),
        CoreExprKind::Quote(v) => ClosedExpr::Quote(*v),
        CoreExprKind::Quasiquote(v) => ClosedExpr::Quasiquote(*v),

        CoreExprKind::Var { name, .. } => match ctx.lookup(name) {
            VarLoc::Local => ClosedExpr::LocalRef(name.clone()),
            VarLoc::Closure(slot) => ClosedExpr::ClosureRef {
                name: name.clone(),
                slot,
            },
            VarLoc::Global => ClosedExpr::GlobalRef(name.clone()),
        },

        CoreExprKind::Set { var, value, .. } => {
            let converted_val = convert(value, ctx);
            match ctx.lookup(var) {
                VarLoc::Local => ClosedExpr::SetLocal {
                    var: var.clone(),
                    value: Box::new(converted_val),
                },
                VarLoc::Closure(slot) => ClosedExpr::SetClosure {
                    var: var.clone(),
                    slot,
                    value: Box::new(converted_val),
                },
                VarLoc::Global => ClosedExpr::SetGlobal {
                    var: var.clone(),
                    value: Box::new(converted_val),
                },
            }
        }

        CoreExprKind::Lambda { params, body, .. } => {
            let node_id = ctx.next_node_id();

            // Retrieve the capture list computed by Pass 1.
            let capture_list: Vec<Symbol> = ctx
                .analysis
                .lambdas
                .get(&node_id)
                .map(|info| info.free_vars.clone())
                .unwrap_or_default();

            // Build the capture slot map: capture_list[i] → Closure(i).
            let closure_locs: Vec<(Symbol, VarLoc)> = capture_list
                .iter()
                .enumerate()
                .map(|(i, name)| (name.clone(), VarLoc::Closure(i as u16)))
                .collect();

            // Extract parameter names and rest-param flag.
            let (param_names, rest_param) = flatten_formals(params);

            // Local locs for params (shadow closure locs if names collide).
            let local_locs: Vec<(Symbol, VarLoc)> = param_names
                .iter()
                .map(|n| (n.clone(), VarLoc::Local))
                .collect();

            // Push a scope: closure slots first, then locals (locals win on lookup).
            ctx.scopes.push(closure_locs);
            ctx.scopes.push(local_locs);

            let converted_body: Vec<ClosedExpr> = body.iter().map(|e| convert(e, ctx)).collect();

            ctx.scopes.pop();
            ctx.scopes.pop();

            ClosedExpr::Lambda(Box::new(ClosedLambda {
                params: param_names,
                rest_param,
                capture_list,
                body: converted_body,
                node_id,
            }))
        }

        CoreExprKind::If { test, then, else_ } => ClosedExpr::If {
            test: Box::new(convert(test, ctx)),
            then: Box::new(convert(then, ctx)),
            else_: Box::new(convert(else_, ctx)),
        },

        CoreExprKind::Begin(exprs) => {
            ClosedExpr::Begin(exprs.iter().map(|e| convert(e, ctx)).collect())
        }

        CoreExprKind::Define { name, value } => ClosedExpr::Define {
            name: name.clone(),
            value: Box::new(convert(value, ctx)),
        },

        CoreExprKind::App { func, args } => ClosedExpr::App {
            func: Box::new(convert(func, ctx)),
            args: args.iter().map(|a| convert(a, ctx)).collect(),
        },

        CoreExprKind::Apply { func, args } => ClosedExpr::Apply {
            func: Box::new(convert(func, ctx)),
            args: args.iter().map(|a| convert(a, ctx)).collect(),
        },

        CoreExprKind::Import { .. } | CoreExprKind::Expand { .. } => {
            // Not lowered through the VM compiler for now.
            ClosedExpr::Literal(TaggedValue::UNSPECIFIED)
        }
    }
}

/// Flatten a `Formals` into (param_names, rest_param).
fn flatten_formals(params: &Formals) -> (Vec<Symbol>, bool) {
    match params {
        Formals::Fixed(ps) => (ps.iter().map(|p| p.name.clone()).collect(), false),
        Formals::Variadic(p) => (vec![p.name.clone()], true),
        Formals::Mixed { fixed, rest } => {
            let mut names: Vec<Symbol> = fixed.iter().map(|p| p.name.clone()).collect();
            names.push(rest.name.clone());
            (names, true)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compiler::pass1_analysis::Pass1Analysis;
    use patina_core::core_expr::{CoreExpr, CoreExprKind, Formals, ScopedParam};
    use patina_core::tagged_value::TaggedValue;
    use std::rc::Rc;

    fn var(name: &str) -> CoreExpr {
        CoreExpr::new(CoreExprKind::Var {
            name: Rc::from(name),
            scopes: Default::default(),
        })
    }

    fn lit(n: i64) -> CoreExpr {
        CoreExpr::new(CoreExprKind::Literal(TaggedValue::fixnum(n)))
    }

    fn lambda(params: Vec<&str>, body: Vec<CoreExpr>) -> CoreExpr {
        CoreExpr::new(CoreExprKind::Lambda {
            params: Formals::Fixed(
                params
                    .iter()
                    .map(|n| ScopedParam::simple(Rc::from(*n)))
                    .collect(),
            ),
            body,
            binding_scope: None,
        })
    }

    #[test]
    fn literal_converts() {
        let expr = lit(7);
        let info = Pass1Analysis::run(&expr);
        let closed = Pass2Closure::run(&expr, &info);
        assert!(matches!(closed, ClosedExpr::Literal(_)));
    }

    #[test]
    fn local_ref_resolved() {
        // (lambda (x) x) — x should become LocalRef
        let expr = lambda(vec!["x"], vec![var("x")]);
        let info = Pass1Analysis::run(&expr);
        let closed = Pass2Closure::run(&expr, &info);
        let ClosedExpr::Lambda(lam) = closed else {
            panic!("expected Lambda");
        };
        assert!(matches!(&lam.body[0], ClosedExpr::LocalRef(n) if n.as_ref() == "x"));
        assert!(lam.capture_list.is_empty());
    }

    #[test]
    fn free_var_becomes_closure_ref() {
        // (lambda (x) y)  — y is free, becomes ClosureRef slot 0
        let expr = lambda(vec!["x"], vec![var("y")]);
        let info = Pass1Analysis::run(&expr);
        let closed = Pass2Closure::run(&expr, &info);
        let ClosedExpr::Lambda(lam) = closed else {
            panic!("expected Lambda");
        };
        assert_eq!(lam.capture_list, vec![Rc::<str>::from("y")]);
        assert!(matches!(
            &lam.body[0],
            ClosedExpr::ClosureRef { slot: 0, .. }
        ));
    }

    #[test]
    fn unresolved_var_becomes_global_ref() {
        // top-level reference — should become GlobalRef
        let info = Pass1Analysis::run(&var("foo"));
        let closed = Pass2Closure::run(&var("foo"), &info);
        assert!(matches!(closed, ClosedExpr::GlobalRef(n) if n.as_ref() == "foo"));
    }

    #[test]
    fn nested_lambda_capture_list() {
        // (lambda (x) (lambda (y) x))
        // inner captures x (+ possibly outer globals like nothing here)
        let inner = lambda(vec!["y"], vec![var("x")]);
        let outer = lambda(vec!["x"], vec![inner]);
        let info = Pass1Analysis::run(&outer);
        let closed = Pass2Closure::run(&outer, &info);
        let ClosedExpr::Lambda(outer_lam) = closed else {
            panic!("expected outer Lambda");
        };
        // outer has no captures (x is its param)
        assert!(outer_lam.capture_list.is_empty());
        let ClosedExpr::Lambda(inner_lam) = &outer_lam.body[0] else {
            panic!("expected inner Lambda");
        };
        // inner captures x
        assert!(inner_lam.capture_list.contains(&Rc::<str>::from("x")));
        assert!(matches!(&inner_lam.body[0], ClosedExpr::ClosureRef { .. }));
    }
}
