(import (scheme base) (scheme write) (patina debug))
(define-library (tmp steady) (export f m) (import (scheme base)) (begin (define (f x) (+ x 1)) (define-syntax m (syntax-rules () ((_ x) (f x))))))
(import (tmp steady))
(define old f)
(define (via-macro) (m 10))
(define-library (tmp steady) (export f m) (import (scheme base)) (begin (define (f x) (+ x 100)) (define-syntax m (syntax-rules () ((_ x) (f x))))))
(import (tmp steady))
(define (churn n) (if (> n 0) (begin (cons n n) (churn (- n 1)))))
(churn 300000)
(gc)
(write (list (old 1) (f 1) (via-macro) (m 10))) (newline)
