(import (scheme base) (prefix (chibi irregex) r:) (patina compat smoke))
(define (matched re text) (let ((m (r:irregex-search re text))) (and m (r:irregex-match-substring m))))
(check-equal "compiled expressions satisfy their predicate" #t (r:irregex? (r:irregex "ab+")))
(check-equal "search locates an unanchored match" "abb" (matched "ab+" "xxabbz"))
(check-equal "whole-string matching rejects a prefix-only result" #f (r:irregex-match "ab+" "abbz"))
(check-equal "anchors admit the whole input" "abb" (matched "^ab+$" "abb"))
(check-equal "alternation uses leftmost longest matching" "abc" (matched "a|abc" "abc"))
(check-equal "captured groups retain text and half-open indices" '("abc-42" "abc" "42" 2 8)
  (let ((m (r:irregex-search "([a-z]+)-([0-9]+)" "xxabc-42!" 2)))
    (list (r:irregex-match-substring m) (r:irregex-match-substring m 1) (r:irregex-match-substring m 2)
          (r:irregex-match-start-index m) (r:irregex-match-end-index m))))
(check-equal "optional unmatched capture is false" #f (r:irregex-match-substring (r:irregex-match "(a)?b" "b") 1))
(check-equal "SRE named groups are accessible by name" "123"
  (r:irregex-match-substring (r:irregex-search '(=> digits (+ numeric)) "a123b") 'digits))
(check-equal "case-insensitive flag affects literals" "AbC" (matched (r:irregex "abc" 'i) "AbC"))
(check-equal "bounded search respects its end index" #f (r:irregex-search "abc" "--abc--" 2 4))
(check-equal "first replacement preserves the remaining input" "x22b33" (r:irregex-replace "a" "a22b33" "x"))
(check-equal "all replacements use every nonoverlapping match" "a#b#" (r:irregex-replace/all "[0-9]+" "a22b33" "#"))
(check-equal "replacement references captured groups" "42:abc" (r:irregex-replace "([a-z]+)-([0-9]+)" "abc-42" 2 ":" 1))
(check-equal "extract returns matches in input order" '("12" "3") (r:irregex-extract "[0-9]+" "a12b3"))
(check-equal "split removes delimiter matches" '("a" "b" "c") (r:irregex-split ",+" "a,,b,c"))
(check-equal "fold accumulates independent match records" '("12" "3")
  (map r:irregex-match-substring (reverse (r:irregex-fold "[0-9]+" (lambda (i m acc) (cons m acc)) '() "a12b3"))))
(check-error "malformed regular expressions are rejected" (r:irregex "("))
(smoke-finish)
