(import (scheme base) (chibi term edit-line) (patina compat smoke))
(check-equal "new history is empty" '() (history->list (make-history)))
(check-equal "history preserves most recent first" '("b" "a") (let ((h (make-history))) (history-insert! h "a") (history-insert! h "b") (history->list h)))
(check-equal "history evicts oldest at capacity" '("c" "b") (let ((h (make-history 2))) (history-insert! h "a") (history-insert! h "b") (history-insert! h "c") (history->list h)))
(check-equal "commit suppresses immediate duplicate" '("a") (let ((h (make-history))) (history-commit! h "a") (history-commit! h "a") (history->list h)))
(check-equal "history filter omits matching input" '("keep") (let ((h (make-history 3 (lambda (x) (equal? x "skip"))))) (history-insert! h "skip") (history-insert! h "keep") (history->list h)))
(check-equal "list conversion round trips" '("b" "a") (history->list (list->history '("b" "a"))))
(check-equal "reset retains committed history" '("a") (let ((h (list->history '("a")))) (history-reset! h) (history->list h)))
(check-equal "new buffer has empty text and origin position" '("" 0 0) (let ((b (make-buffer))) (list (buffer->string b) (buffer-row b) (buffer-col b))))
;; Explicit width, no-stty and string ports exercise the editor without a tty.
(define (edit text . options)
  (apply edit-line (open-input-string text) (open-output-string)
    'prompt: "" 'terminal-width: 80 'no-stty?: #t options))
(check-equal "editor accepts a line" "abc" (edit "abc\n"))
(check-equal "editor returns EOF on empty input" #t (eof-object? (edit "")))
(check-equal "editor returns final unterminated input" "abc" (edit "abc"))
(check-equal "backspace removes previous character" "ac" (edit (string-append "ab" (string (integer->char 127)) "c\n")))
(check-equal "cursor movement inserts in the middle" "aXb" (edit (string-append "ab" (string (integer->char 2)) "X\n")))
(check-equal "editor resizes past initial buffer capacity" (make-string 300 #\x) (edit (string-append (make-string 300 #\x) "\n")))
(check-equal "hidden input still returns its text" "secret" (edit "secret\n" 'hidden?: #t))
;; Native Chibi needs a real tty for stty; the portable branch is a no-op.
(cond-expand (chibi (define bypass-native-stty? #t))
             (else (define bypass-native-stty? #f)))
(check-equal "terminal setup dispatch matches the selected implementation" "ok"
  (edit-line (open-input-string "ok\n") (open-output-string)
    'prompt: "" 'terminal-width: 80 'no-stty?: bypass-native-stty?))
(smoke-finish)
