;; Exercise generated constructors, accessors, binary writing and reading.
(import (scheme base) (scheme write) (chibi binary-record))
(import (patina compat smoke))
(define-binary-record-type packet
  (make: make-packet) (pred: packet?)
  (read: read-packet) (write: write-packet)
  (block: "PT" (kind (u8) packet-kind) (size (u16/be) packet-size)))
(define (packet-bytes p)
  (let ((out (open-output-bytevector)))
    (write-packet p out)
    (get-output-bytevector out)))
(define bytes (packet-bytes (make-packet 7 258)))
(check-equal "wire bytes" #u8(80 84 7 1 2) bytes)
(define decoded (read-packet (open-input-bytevector bytes)))
(check-equal "record predicate" #t (packet? decoded))
(check-equal "decoded kind" 7 (packet-kind decoded))
(check-equal "decoded size" 258 (packet-size decoded))
(check-equal "read/write round trip" bytes (packet-bytes decoded))
(smoke-finish)
