(import (scheme base) (chibi monad environment) (patina compat smoke))
(define-environment-monad state
  (fields: (x get-x set-x!) (y get-y set-y!))
  (sequence: seq) (bind: bind) (bind-fork: fork)
  (local: local) (local!: update) (run: run) (return: ret)
  (ask: ask raw-ask) (tell: tell raw-tell) (copy: copy))
(check-equal "return is independent of state" 7 (run (ret 7)))
(check-equal "declared fields initially false" '(#f #f) (run (bind (x y) (ret (list x y)))))
(check-equal "updates flow through sequence" '(1 2) (run (seq (update (x 1) (y 2)) (bind (x y) (ret (list x y))))))
(check-equal "bind supports renamed variables" 5 (run (seq (update (x 5)) (bind ((value x)) (ret value)))))
(check-equal "dynamic fields can be read and replaced" 9 (run (seq (update (extra 3)) (update (extra 9)) (bind (extra) (ret extra)))))
(check-equal "local shadows a declared field" 8 (run (seq (update (x 1)) (local ((x 8)) (bind (x) (ret x))))))
(check-equal "local restores original state" 1 (run (seq (update (x 1)) (local ((x 8)) (update (y 2))) (bind (x) (ret x)))))
(check-equal "fork isolates declared updates" 1 (run (seq (update (x 1)) (fork (update (x 9)) (bind (x) (ret x))))))
(check-equal "fork isolates dynamic property cells" 2 (run (seq (update (extra 2)) (fork (update (extra 9)) (bind (extra) (ret extra))))))
(check-equal "each run starts fresh" #f (begin (run (update (x 3))) (run (bind (x) (ret x)))))
(smoke-finish)
