(import (scheme base) (prefix (chibi sxml) s:) (patina compat smoke))
(define (captured proc value) (let ((out (open-output-string))) (proc value out) (get-output-string out)))
(check-equal "text escaping handles less-than and ampersand" "a&lt;b&amp;c" (s:html-escape "a<b&c"))
(check-equal "text escaping accepts scalar nodes" "42" (s:html-escape 42))
(check-equal "empty text remains empty" "" (s:html-escape ""))
(check-equal "attribute escaping also quotes double quotes" "<p title=\"a&amp;&lt;&quot;\">" (s:html-tag->string 'p '((title "a&<\""))))
(check-equal "dotted attributes and booleans retain their forms" "<input value=\"x\" disabled>" (s:html-tag->string 'input '((value . "x") (disabled . #f))))
(check-equal "nested nodes serialize recursively" "<p>a<b>b</b>c</p>" (s:sxml->xml '(p "a" (b "b") "c")))
(check-equal "attributes serialize ahead of children" "<p id=\"x\">text</p>" (s:sxml->xml '(p (@ (id "x")) "text")))
(check-equal "raw nodes bypass text escaping" "<p><b>x</b></p>" (s:sxml->xml '(p (@raw "<b>x</b>"))))
(check-equal "node lists serialize each sibling" "<a>x</a><b>y</b>" (s:sxml->xml '((a "x") (b "y"))))
(check-equal "strip removes tags and attributes" "textmore" (s:sxml-strip '(p (@ (id "hidden")) "text" (b "more"))))
(check-equal "text display inserts paragraph line breaks" "one\ntwo\n" (captured s:sxml-display-as-text '((p "one") (p "two"))))
(check-equal "text display ignores attribute values" "visible\n" (captured s:sxml-display-as-text '(p (@ (title "hidden")) "visible")))
(check-equal "text display omits script and style content" "shown\n" (captured s:sxml-display-as-text '((script "hidden") (style "hidden") (p "shown"))))
(check-equal "explicit HTML output port matches string conversion" "<p>x</p>" (captured s:sxml-display-as-html '(p "x")))
(check-error "unsupported text nodes raise" (s:html-escape '#(1)))
(smoke-finish)
