(import (scheme base) (prefix (chibi char-set) c:) (patina compat smoke))
(define (chars cs) (c:char-set->string cs))
(check-equal "constructors remove duplicates and enumerate codepoint order" "abc" (chars (c:char-set #\c #\a #\b #\a)))
(check-equal "empty set has no members" '(0 #f) (list (c:char-set-size c:char-set:empty) (c:char-set-contains? c:char-set:empty #\a)))
(check-equal "predicate distinguishes sets" '(#t #f) (list (c:char-set? (c:char-set)) (c:char-set? '(#\a))))
(check-equal "string conversion deduplicates" "ab" (chars (c:string->char-set "baba")))
(check-equal "list conversion retains characters" '(#\a #\z) (c:char-set->list (c:list->char-set '(#\z #\a #\z))))
(check-equal "ranges exclude their upper endpoint" "abc" (chars (c:ucs-range->char-set 97 100)))
(check-equal "range construction accepts a base set" "abcz" (chars (c:ucs-range->char-set 97 100 #f (c:char-set #\z))))
(check-equal "copied sets can mutate independently" '("ab" "abc")
  (let* ((a (c:string->char-set "ab")) (b (c:char-set-copy a))) (c:char-set-adjoin! b #\c) (list (chars a) (chars b))))
(check-equal "functional adjoin preserves input" '("ab" "abc")
  (let ((a (c:string->char-set "ab"))) (let ((b (c:char-set-adjoin a #\c))) (list (chars a) (chars b)))))
(check-equal "union joins overlapping sets" "abcd" (chars (c:char-set-union (c:string->char-set "ac") (c:string->char-set "bcd"))))
(check-equal "intersection keeps shared members" "bc" (chars (c:char-set-intersection (c:string->char-set "abc") (c:string->char-set "bcd"))))
(check-equal "difference removes right-hand members" "a" (chars (c:char-set-difference (c:string->char-set "abc") (c:string->char-set "bcd"))))
(check-equal "destructive union updates destination" "abc" (let ((a (c:char-set #\a))) (c:char-set-union! a (c:string->char-set "bc")) (chars a)))
(check-equal "destructive intersection updates destination" "b" (let ((a (c:string->char-set "ab"))) (c:char-set-intersection! a (c:string->char-set "bc")) (chars a)))
(check-equal "destructive difference updates destination" "a" (let ((a (c:string->char-set "ab"))) (c:char-set-difference! a (c:char-set #\b)) (chars a)))
(check-equal "fold visits each distinct member" 294 (c:char-set-fold (lambda (ch n) (+ n (char->integer ch))) 0 (c:string->char-set "abcaa")))
(check-equal "for-each visits every member once" 3 (let ((n 0)) (c:char-set-for-each (lambda (ch) (set! n (+ n 1))) (c:string->char-set "abaac")) n))
(check-equal "ASCII set covers exactly 128 characters" '(128 #t #f) (list (c:char-set-size c:char-set:ascii) (c:char-set-contains? c:char-set:ascii (integer->char 127)) (c:char-set-contains? c:char-set:ascii (integer->char 128))))
(check-equal "complement removes chosen characters within the supported universe" '(#f #t) (let ((cs (c:char-set-complement (c:char-set #\a)))) (list (c:char-set-contains? cs #\a) (c:char-set-contains? cs #\b))))
(smoke-finish)
