(import (scheme base) (prefix (chibi char-set boundary) b:) (prefix (chibi regexp) r:) (patina compat smoke))
(cond-expand (chibi (import (only (chibi char-set) char-set-contains?)))
             (else (import (only (srfi 14) char-set-contains?))))
(define (contains set code) (char-set-contains? set (integer->char code)))
(check-equal "regional indicators include both endpoints" '(#t #t #f #f)
  (map (lambda (cp) (contains b:char-set:regional-indicator cp)) '(#x1f1e6 #x1f1ff #x1f1e5 #x1f200)))
(check-equal "combining acute and spacing vowel marks extend a grapheme" '(#t #t #f)
  (map (lambda (cp) (contains b:char-set:extend-or-spacing-mark cp)) '(#x301 #x903 65)))
(check-equal "Hangul leading consonants cover their boundary" '(#t #t #f)
  (map (lambda (cp) (contains b:char-set:hangul-l cp)) '(#x1100 #x115f #x1160)))
(check-equal "Hangul vowels cover their boundary" '(#t #t #f)
  (map (lambda (cp) (contains b:char-set:hangul-v cp)) '(#x1160 #x11a7 #x11a8)))
(check-equal "Hangul trailing consonants cover their boundary" '(#t #t #f)
  (map (lambda (cp) (contains b:char-set:hangul-t cp)) '(#x11a8 #x11ff #x1200)))
(check-equal "LV syllables repeat every 28 codepoints" '(#t #f #t)
  (map (lambda (cp) (contains b:char-set:hangul-lv cp)) '(#xac00 #xac01 #xac1c)))
(check-equal "LVT syllables exclude LV positions" '(#f #t #t #f)
  (map (lambda (cp) (contains b:char-set:hangul-lvt cp)) '(#xac00 #xac01 #xac1b #xac1c)))
(check-equal "every precomposed Hangul syllable has exactly one syllable class" #t
  (let loop ((cp #xac00))
    (or (> cp #xd7a3)
        (and (not (eqv? (contains b:char-set:hangul-lv cp) (contains b:char-set:hangul-lvt cp))) (loop (+ cp 1))))))
(check-equal "ASCII letters are absent from all boundary sets" '(#f #f #f #f #f #f #f)
  (map (lambda (cs) (contains cs 65)) (list b:char-set:regional-indicator b:char-set:extend-or-spacing-mark b:char-set:hangul-l b:char-set:hangul-v b:char-set:hangul-t b:char-set:hangul-lv b:char-set:hangul-lvt)))
(check-equal "grapheme consumes an LV syllable and trailing jamo" #t
  (r:regexp-matches? 'grapheme (string (integer->char #xac00) (integer->char #x11a8))))
(check-equal "grapheme consumes a restored spacing-mark singleton" #t
  (r:regexp-matches? 'grapheme (string #\a (integer->char #x903))))
(smoke-finish)
