(import (scheme base) (prefix (chibi html-parser) h:) (patina compat smoke))
(define (parse text) (h:html->sxml (open-input-string text)))
(check-equal "empty input yields an empty top node" '(*TOP*) (parse ""))
(check-equal "nested tags preserve their children" '(*TOP* (p "a" (b "b") "c")) (parse "<p>a<b>b</b>c</p>"))
(check-equal "tag and attribute names fold case" '(*TOP* (p (@ (id "X")) "t")) (parse "<P ID='X'>t</P>"))
(check-equal "attributes retain decoded entity values" '(*TOP* (a (@ (href "a&b")) "x")) (parse "<a href='a&amp;b'>x</a>"))
(check-equal "void elements do not consume following text" '(*TOP* (p "a" (br) "b")) (parse "<p>a<br>b</p>"))
(check-equal "self-closing tags close immediately" '(*TOP* (x) (y "z")) (parse "<x/><y>z</y>"))
(check-equal "comments are represented explicitly" '(*TOP* (*COMMENT* " note ") (p "x")) (parse "<!-- note --><p>x</p>"))
(check-equal "named and numeric entities decode to characters" "<&AA" (h:html-strip (open-input-string "&lt;&amp;&#65;&#x41;")))
(check-equal "strip preserves whitespace between tags" "a  b\nc" (h:html-strip (open-input-string "<p>a  <b>b</b>\nc</p>")))
(check-equal "EOF closes an unfinished element" '(*TOP* (p (b "x"))) (parse "<p><b>x"))
(check-equal "successive list items implicitly close their predecessor" '(*TOP* (ul (li "one") (li "two"))) (parse "<ul><li>one<li>two</ul>"))
(check-equal "raw script text keeps markup characters" '(*TOP* (script "if (a < b) x++;")) (parse "<script>if (a < b) x++;</script>"))
(check-equal "custom parser callbacks preserve seed order" '("a" "b")
  (let ((parser (h:make-html-parser 'start: (lambda (tag attrs seed virtual?) seed)
                  'end: (lambda (tag attrs parent seed virtual?) seed)
                  'text: (lambda (text seed) (cons text seed)))))
    (reverse (parser '() (open-input-string "<p>a<b>b</b></p>")))))
(check-equal "default input comes from the dynamic input port" '(*TOP* (p "x"))
  (parameterize ((current-input-port (open-input-string "<p>x</p>"))) (h:html->sxml)))
(check-equal "stray close tags retain the parser's synthesized opening" '(*TOP* (b)) (parse "</b>"))
(check-equal "explicit list item closures add no extra nodes" '(*TOP* (ul (li "x"))) (parse "<ul><li>x</li></ul>"))
(check-equal "formatting tags retain documented interleaving recovery" '(*TOP* (b (i)) (i)) (parse "<b><i></b>"))
(smoke-finish)
