(import (scheme base) (scheme char) (scheme file) (scheme write) (chibi config) (patina compat smoke))
(define base (make-conf '((port 80) (paths "base") (enabled #f) (nested (a 1) (b 2))) #f 'base 0))
(define child (conf-extend base '((port 443) (paths "child")) 'child))
(define (attempt thunk) (guard (ex (else 'raised)) (thunk)))
(check-equal "config predicate" '(#t #f) (list (conf? base) (conf? '())))
(check-error "constructor rejects non-alist" (make-conf '(bad) #f #f 0))
(check-equal "child overrides parent" 443 (conf-get child 'port))
(check-equal "parent supplies missing child keys" #f (conf-get child 'enabled 'missing))
(check-equal "missing key default" 'missing (conf-get child 'absent 'missing))
(check-equal "nested lookup" 2 (conf-get child '(nested b)))
(check-equal "source and parent retained" '(child #t) (list (conf-source child) (eq? base (conf-parent child))))
(check-equal "head drops parent" '(#f missing) (list (conf-parent (conf-head child)) (conf-get (conf-head child) 'enabled 'missing)))
(check-equal "empty extension preserves config" #t (eq? base (conf-extend base '())))
(check-equal "get-list normalizes scalar" '(443) (conf-get-list child 'port))
(check-equal "get-cdr retains wrapping" '(443) (conf-get-cdr child 'port))
(check-equal "multi concatenates child before parent" '("child" "base") (conf-get-multi child 'paths))
(check-equal "append preserves left precedence" '(443 90) (let ((c (conf-append child (make-conf '((port 90) (extra 90)) #f #f 0)))) (list (conf-get c 'port) (conf-get c 'extra))))
(check-equal "set is persistent" '(80 81) (let ((c (conf-set base 'port 81))) (list (conf-get base 'port) (conf-get c 'port))))
(check-equal "nested set preserves siblings" '(9 2 1) (let ((c (conf-set base '(nested a) 9))) (list (conf-get c '(nested a)) (conf-get c '(nested b)) (conf-get base '(nested a)))))
(check-equal "unfold creates missing nested keys" '(a (b . 7)) (conf-unfold-key '(a b) 7))
(check-equal "assoc-get handles documented cell shapes" '(() 1 1 (1 2) (1 2)) (map (lambda (cell) (assoc-get (list cell) 'x)) '((x) (x . 1) (x 1) (x (1 2)) (x 1 2))))
(check-equal "assoc-get custom equality" 3 (assoc-get '(("KEY" 3)) "key" string-ci=? 'missing))
(check-equal "assoc-get-list missing default" '(fallback) (assoc-get-list '() 'x '(fallback)))
(check-equal "specialization lifts matching section and keeps fallback" '(443 "base")
  (attempt (lambda () (let ((c (conf-specialize (conf-extend base '((profile (prod (port 443))))) 'profile 'prod))) (list (conf-get c 'port) (conf-get c 'paths))))))
(define (warnings spec alist)
  (let ((n 0)) (conf-verify spec (make-conf alist #f #f 0) (lambda args (set! n (+ n 1)) #f)) n))
(check-equal "verification accepts scalar schema" 0 (warnings '((port integer) (name string)) '((port 80) (name "web"))))
(check-equal "verification reports all invalid fields" 3 (warnings '((port integer) (name string)) '((port "80") (name 2) (unknown #t))))
(check-equal "verification supports list elements" 0 (attempt (lambda () (warnings '((ports (list integer))) '((ports 80 443))))))
(check-equal "verification tries alternate types" 0 (attempt (lambda () (warnings '((port (or integer string))) '((port "http"))))))
;; The runner owns its scratch cwd. Refuse a collision and remove only this fixture.
(define fixture "patina-smoke-config.scm")
(define included "patina-smoke-config-child.scm")
(if (file-exists? included) (error "fixture already exists" included))
(if (file-exists? fixture) (error "fixture already exists" fixture))
(dynamic-wind
  (lambda ()
    (call-with-output-file fixture (lambda (out) (write `((port 8080) (include ,included)) out)))
    (call-with-output-file included (lambda (out) (write '((port 9000) (extra 42)) out))))
  (lambda ()
    (check-equal "file loader reads configuration" 8080 (conf-get (conf-load fixture) 'port))
    (check-equal "cascaded loader appends includes with outer precedence" '(8080 42) (attempt (lambda () (let ((c (conf-load-cascaded '(".") fixture))) (list (conf-get c 'port) (conf-get c 'extra)))))))
  (lambda () (delete-file fixture) (delete-file included)))
(check-equal "list verifier reports bad member" 1 (warnings '((ports (list integer))) '((ports 80 "bad"))))
(check-equal "or verifier reports once when all alternatives fail" 1 (warnings '((port (or integer string))) '((port #t))))
(check-equal "specialization retains child precedence across parents" 443
  (conf-get (conf-specialize
    (conf-extend (make-conf '((profile (prod (port 80)))) #f #f 0)
                 '((profile (prod (port 443))))) 'profile 'prod) 'port))
(check-equal "zero-depth cascade returns an empty config" 'missing
  (conf-get (conf-load-cascaded '(".") "unused-file" 'include 0) 'port 'missing))
(smoke-finish)
