(import (scheme base) (chrisoei test) (chibi test) (patina compat smoke))
;; Keep real test evaluation and accounting; capture only human-readable output.
(define (failures thunk)
  (parameterize ((current-output-port (open-output-string)) (current-error-port (open-output-string)) (current-test-group #f) (test-failure-count 0))
    (thunk) (test-failure-count)))
(check-equal "nearby scalars pass" 0 (failures (lambda () (test-approx= 1 1.01 0.1))))
(check-equal "distant scalars fail" 1 (failures (lambda () (test-approx= 1 2 0.1))))
(check-equal "tolerance boundary is strict" 1 (failures (lambda () (test-approx= 1 2 1))))
(check-equal "negative scalar comparison" 0 (failures (lambda () (test-approx= -10 -10.01 0.1))))
(check-equal "list comparison checks every element" 2 (failures (lambda () (test-approx= '(1 2 3) '(1 8 9) 0.1))))
(check-equal "nested lists recurse" 0 (failures (lambda () (test-approx= '((1 2) (3)) '((1.01 2.01) (3.01)) 0.1))))
(check-equal "length mismatch reports failure" 1 (failures (lambda () (test-approx= '(1 2) '(1) 0.1))))
(check-equal "empty lists compare" 0 (failures (lambda () (test-approx= '() '() 0.1))))
(smoke-finish)
