(import (scheme base) (generators) (patina compat smoke))
(check-equal "empty generator stays exhausted" '(#t #t) (let ((g (generator))) (list (eof-object? (g)) (eof-object? (g)))))
(check-equal "generator preserves values" '(1 #f "a") (generator->list (generator 1 #f "a")))
(check-equal "iota start and step" '(5 7 9) (generator->list (make-iota-generator 3 5 2)))
(check-equal "range excludes upper bound" '(2 5 8) (generator->list (make-range-generator 2 9 3)))
(check-equal "infinite range can be bounded" '(4 5 6) (generator->list (make-range-generator 4) 3))
(check-equal "coroutine resumes after each yield" '(a b c) (generator->list (make-coroutine-generator (lambda (yield) (yield 'a) (yield 'b) (yield 'c)))))
(check-equal "for-each generator resumes traversal" '(1 2 3) (generator->list (make-for-each-generator for-each '(1 2 3))))
(check-equal "unfold generator evolves seed" '(0 1 4 9) (generator->list (make-unfold-generator (lambda (n) (= n 4)) (lambda (n) (* n n)) (lambda (n) (+ n 1)) 0)))
(check-equal "list and vector slices" '((a b) (b c)) (list (generator->list (list->generator '(a b))) (generator->list (vector->generator '#(a b c d) 1 3))))
(check-equal "reverse vector slice" '(c b) (generator->list (reverse-vector->generator '#(a b c d) 1 3)))
(check-equal "string slice" "bc" (generator->string (string->generator "abcd" 1 3)))
(check-equal "bytevector slice" '(0 255) (generator->list (bytevector->generator #u8(7 0 255 9) 1 3)))
(check-equal "cons and append skip exhausted sources" '(1 2 3 4) (generator->list (gcons* 1 2 (gappend (generator) (generator 3) (generator) (generator 4)))))
(check-equal "combine threads seed and stops at shortest" '(11 33) (generator->list (gcombine (lambda (a b s) (values (+ a b s) (+ a b s))) 0 (generator 1 2 3) (generator 10 20))))
(check-equal "filter and remove" '((2 4) (1 3)) (list (generator->list (gfilter even? (generator 1 2 3 4))) (generator->list (gremove even? (generator 1 2 3 4)))))
(check-equal "take pads short input" '(1 pad pad) (generator->list (gtake (generator 1) 3 'pad)))
(check-equal "drop removes prefix" '(3 4) (generator->list (gdrop (generator 1 2 3 4) 2)))
(check-equal "take-while stays exhausted after first mismatch" '(1 2) (generator->list (gtake-while (lambda (x) (< x 3)) (generator 1 2 3 1))))
(check-equal "drop-while stops testing after first mismatch" '(3 1) (generator->list (gdrop-while (lambda (x) (< x 3)) (generator 1 2 3 1))))
(check-equal "delete matching items" '(1 3) (generator->list (gdelete 2 (generator 1 2 2 3))))
(check-equal "neighbor dedup retains nonadjacent duplicates" '(1 2 1) (generator->list (gdelete-neighbor-dups (generator 1 1 2 2 1))))
(check-equal "index selects increasing offsets" '(a c e) (generator->list (gindex (generator 'a 'b 'c 'd 'e) (generator 0 2 4))))
(check-equal "select follows truth generator" '(a c) (generator->list (gselect (generator 'a 'b 'c 'd) (generator #t #f #t))))
(check-equal "reverse-list consumer" '(3 2 1) (generator->reverse-list (generator 1 2 3)))
(check-equal "vector consumer limit" '#(1 2) (generator->vector (generator 1 2 3) 2))
(check-equal "vector fill reports count and preserves outside slice" '(2 #(x a b)) (let ((v (vector 'x 'x 'x))) (let ((n (generator->vector! v 1 (generator 'a 'b)))) (list n v))))
(check-equal "fold accumulates across generators" 33 (generator-fold (lambda (a b s) (+ a b s)) 0 (generator 1 2) (generator 10 20 30)))
(check-equal "for-each processes corresponding pairs" '(11 22) (let ((xs '())) (generator-for-each (lambda (a b) (set! xs (cons (+ a b) xs))) (generator 1 2) (generator 10 20)) (reverse xs)))
(check-equal "find returns matching value" 4 (generator-find even? (generator 1 3 4 6)))
(check-equal "find returns false on exhaustion without calling predicate on EOF" #f (guard (ex (else 'raised)) (generator-find even? (generator 1 3))))
(check-equal "count matching values" 2 (generator-count even? (generator 1 2 3 4)))
(check-equal "any and every including empty inputs" '(#t #f #t #f) (list (generator-any even? (generator 1 2)) (generator-any even? (generator)) (generator-every even? (generator)) (generator-every even? (generator 2 3))))
(check-equal "find on empty input returns false even with a truthy predicate" #f (generator-find (lambda (x) 'yes) (generator)))
(check-equal "any returns predicate witness" 'found (generator-any (lambda (x) (and (even? x) 'found)) (generator 1 2 3)))
(check-equal "every returns last predicate value" 3 (generator-every (lambda (x) x) (generator 1 2 3)))
(smoke-finish)
