(import (scheme base) (lassik unpack-assoc) (patina compat smoke))
(check-equal "required and optional scalar bindings" '(3 #f) (unpack '((x 3)) ((x integer?) (y string? ?)) (list x y)))
(check-equal "many bindings preserve all values" '((1 2) ("a" "b")) (unpack '((xs 1 2) (ys "a" "b")) ((xs integer? *) (ys string? +)) (list xs ys)))
(check-equal "present empty list differs from absent optional key" '(() #f) (unpack '((xs)) ((xs integer? *) (ys integer? *)) (list xs ys)))
(check-error "missing required key" (unpack '() ((x integer?)) x))
(check-error "missing required list key" (unpack '() ((xs integer? +)) xs))
(check-error "wrong scalar type" (unpack '((x "no")) ((x integer?)) x))
(check-error "wrong list member type" (unpack '((xs 1 "no")) ((xs integer? *)) xs))
(check-error "multiple scalar values" (unpack '((x 1 2)) ((x integer?)) x))
(check-error "empty scalar value" (unpack '((x)) ((x integer?)) x))
(check-error "duplicate key" (unpack '((x 1) (x 2)) ((x integer?)) x))
(check-error "unknown key" (unpack '((other 1)) ((x integer? ?)) x))
(check-error "improper alist" (unpack '((x 1) . tail) ((x integer?)) x))
(check-error "improper values" (unpack '((xs 1 . tail)) ((xs integer? *)) xs))
(check-equal "case dispatch and fallback" '(4 fallback) (list (unpack-case '(point (x 4)) ((point (x integer?)) x) (else 'fallback)) (unpack-case '(other) ((point (x integer?)) x) (else 'fallback))))
(check-equal "unpack-using accepts custom traversal" 8 (unpack-using (lambda (f pairs) (f 'x (list (vector-ref pairs 0)))) '#(8) ((x integer?)) x))
(check-equal "exclusive choices accept one truthy value" 'ok (let ((a #f) (b 'yes)) (at-most-one-of a b) (exactly-one-of a b) 'ok))
(check-error "at-most-one rejects two choices" (let ((a 1) (b 2)) (at-most-one-of a b)))
(check-error "exactly-one rejects no choice" (let ((a #f) (b #f)) (exactly-one-of a b)))
(smoke-finish)
