(import (scheme base) (lassik trivial-tar-writer) (patina compat smoke))
(define (archive thunk) (let ((out (open-output-bytevector))) (parameterize ((current-output-port out)) (thunk)) (get-output-bytevector out)))
(define (field bv start len) (let loop ((i start)) (if (or (= i (+ start len)) (= 0 (bytevector-u8-ref bv i))) (utf8->string (bytevector-copy bv start i)) (loop (+ i 1)))))
(define sample (archive (lambda () (tar-write-file "hello.txt" (string->utf8 "abc")))))
(check-equal "short file occupies header and padded data block" 1024 (bytevector-length sample))
(check-equal "header filename" "hello.txt" (field sample 0 100))
(check-equal "header records size in octal" 3 (string->number (field sample 124 12) 8))
(check-equal "header magic" "ustar  " (field sample 257 8))
(check-equal "file data starts at block boundary" "abc" (utf8->string (bytevector-copy sample 512 515)))
(check-equal "data padding is zero filled" (make-bytevector 509 0) (bytevector-copy sample 515))
(check-equal "header checksum treats all eight checksum bytes as spaces" #t
  (let loop ((i 0) (sum 0)) (if (= i 512) (= sum (string->number (field sample 148 7) 8)) (loop (+ i 1) (+ sum (if (and (>= i 148) (< i 156)) 32 (bytevector-u8-ref sample i)))))))
(check-equal "empty file needs only a header" 512 (bytevector-length (archive (lambda () (tar-write-file "empty" #u8())))))
(check-equal "aligned content needs no extra data block" 1024 (bytevector-length (archive (lambda () (tar-write-file "aligned" (make-bytevector 512 7))))))
(check-equal "file after empty entry follows its header" "next" (field (archive (lambda () (tar-write-file "empty" #u8()) (tar-write-file "next" #u8()))) 512 100))
(check-equal "end marker is two zero blocks" (make-bytevector 1024 0) (archive tar-write-end))
(check-equal "parameters control metadata" '(493 12 34 123 "owner" "group")
  (let ((bv (parameterize ((tar-unix-mode #o755) (tar-owner '(12 . "owner")) (tar-group '(34 . "group")) (tar-unix-time 123)) (archive (lambda () (tar-write-file "f" #u8()))))))
    (list (string->number (field bv 100 8) 8) (string->number (field bv 108 8) 8) (string->number (field bv 116 8) 8) (string->number (field bv 136 12) 8) (field bv 265 32) (field bv 297 32))))
(check-error "overlong name rejected" (archive (lambda () (tar-write-file (make-string 100 #\a) #u8()))))
(check-error "negative uid rejected" (parameterize ((tar-owner '(-1 . "bad"))) (archive (lambda () (tar-write-file "f" #u8())))))
(check-error "oversized mode rejected" (parameterize ((tar-unix-mode (expt 8 8))) (archive (lambda () (tar-write-file "f" #u8())))))
(smoke-finish)
