(import (scheme base) (scheme char) (prefix (lightweight-testing) l:) (chibi test) (patina compat smoke))
(define (quiet thunk) (parameterize ((current-output-port (open-output-string)) (current-error-port (open-output-string))) (thunk)))
(quiet l:check-reset!)
(check-equal "reset starts with zero passes" #t (l:check-passed? 0))
(quiet (lambda () (l:check (+ 1 2) => 3)))
(check-equal "successful check updates count" '(#t #f) (list (l:check-passed? 1) (l:check-passed? 0)))
(quiet (lambda () (l:check "A" (=> string-ci=?) "a")))
(check-equal "custom comparator updates count once" #t (l:check-passed? 2))
(define evaluations 0)
(quiet (lambda () (l:check (begin (set! evaluations (+ evaluations 1)) 7) => 7)))
(check-equal "check evaluates expression once" '(1 #t) (list evaluations (l:check-passed? 3)))
(quiet (lambda () (l:check 1 => 2)))
(check-equal "failed check prevents passed status" #f (l:check-passed? 3))
(check-error "report raises on recorded failure" (quiet l:check-report))
(quiet l:check-reset!)
(check-equal "reset clears prior failures" #t (l:check-passed? 0))
(l:check-set-mode! 'off)
(quiet (lambda () (l:check (error "off mode must not evaluate") => 0)))
(check-equal "off mode skips expression" #t (l:check-passed? 0))
(check-error "unknown mode rejected" (l:check-set-mode! 'unknown))
(quiet (lambda () (l:check-set-mode! 'summary) (l:check 4 => 4) (l:check-report)))
(check-equal "summary reports without changing count" #t (l:check-passed? 1))
(smoke-finish)
