(import (scheme base) (scheme write) (macduffie json) (srfi 69))
(import (patina compat smoke))
(check-equal "JSON array" '(1 #t #f "hello")
  (json-read-string "[1,true,false,\"hello\"]"))
(check-equal "null" #t (json-null? (json-read-string "null")))
(check-equal "string escape round trip" "line\n\"quoted\"\\tail"
  (json-read-string (json-write-string "line\n\"quoted\"\\tail")))
(define object (json-read-string "{\"answer\":42,\"items\":[2,3]}"))
(check-equal "object lookup" 42 (hash-table-ref object 'answer))
(define decoded (json-read-string (json-write-string object)))
(check-equal "object round trip by fields" '(42 (2 3))
  (list (hash-table-ref decoded 'answer) (hash-table-ref decoded 'items)))
(check-error "malformed input" (json-read-string "[1,"))
(smoke-finish)
