;; Maintained smoke drivers for the pinned corpus, separate from upstream suites.
;; Counts are checked by the runner: an empty or truncated driver cannot pass.
(patina-compat-smokes
 (tests
  ((slug "chibi-binary-record") (assertions 5))
  ((slug "pfds-queue") (assertions 6))
  ((slug "pfds-heap") (assertions 6))
  ((slug "pfds-deque") (assertions 8))
  ((slug "pfds-difference-list") (assertions 6))
  ((slug "pfds-fector") (assertions 8))
  ((slug "pfds-lazy-list") (assertions 7))
  ((slug "pfds-sequence") (assertions 12))
  ((slug "pfds-set") (assertions 9))
  ((slug "slib-format") (assertions 4))
  ((slug "slib-string-search") (assertions 9))
  ((slug "slib-string-case") (assertions 7))
  ((slug "slib-string-port") (assertions 6))
  ((slug "slib-line-io") (assertions 7))
  ((slug "slib-generic-write") (assertions 7))
  ((slug "slib-printf") (assertions 7))
  ((slug "srfi-63") (assertions 6))
  ((slug "srfi-95") (assertions 14))
  ((slug "srfi-43") (assertions 12))
  ((slug "srfi-37") (assertions 8))
  ((slug "srfi-180") (assertions 18))
  ((slug "macduffie-json") (assertions 6))))
