(import (scheme base) (pfds priority-search-queue) (patina compat smoke))
(define empty (make-psq < <))
(define pairs '((1 . 40) (2 . 10) (3 . 30) (4 . 20) (5 . 10) (6 . 50)))
(define (insert-all queue pairs)
  (if (null? pairs) queue
      (insert-all (psq-set queue (caar pairs) (cdar pairs)) (cdr pairs))))
(define original (insert-all empty pairs))
(check-equal "empty queue and range queries" '(#t #t 0 #f () ())
  (list (psq? empty) (psq-empty? empty) (psq-size empty) (psq-contains? empty 1)
        (psq-at-most empty 100) (psq-at-most-range empty 100 1 6)))
(check-equal "singleton pop returns a key and an empty queue" '(7 #t 0)
  (call-with-values (lambda () (psq-pop (psq-set empty 7 20)))
    (lambda (key rest) (list key (psq-empty? rest) (psq-size rest)))))
(check-equal "insertion retains key-priority associations and the source"
  (list 6 pairs 0)
  (list (psq-size original) (psq-at-most original 100) (psq-size empty)))
(check-equal "lookup and membership use keys rather than priorities"
  '(40 10 #t #f)
  (list (psq-ref original 1) (psq-ref original 5)
        (psq-contains? original 6) (psq-contains? original 40)))
(check-equal "replacement can promote a new minimum without adding a key"
  '(6 6 5 50)
  (let ((changed (psq-set original 6 5)))
    (list (psq-size changed) (psq-min changed)
          (psq-ref changed 6) (psq-ref original 6))))
(check-equal "increasing a minimum restores priority order" '(10 100 6)
  (let ((changed (psq-set (psq-set original 6 5) 6 100)))
    (list (psq-ref changed (psq-min changed)) (psq-ref changed 6) (psq-size changed))))
(check-equal "update calls once with an existing priority or the default"
  '(0 30 (30 60) 7 30 #f)
  (let* ((calls '())
         (lower (lambda (old) (set! calls (cons old calls)) (- old 30)))
         (changed (psq-update original 3 lower 60))
         (extended (psq-update changed 7 lower 60)))
    (list (psq-ref extended 3) (psq-ref extended 7) (reverse calls)
          (psq-size extended) (psq-ref original 3) (psq-contains? original 7))))
(check-equal "arbitrary deletion preserves the remaining associations and source"
  (list '((1 . 40) (2 . 10) (4 . 20) (5 . 10) (6 . 50)) pairs)
  (list (psq-at-most (psq-delete original 3) 100) (psq-at-most original 100)))
(check-equal "absent deletion leaves populated and empty queues unchanged"
  (list pairs #t)
  (list (psq-at-most (psq-delete original 99) 100)
        (psq-empty? (psq-delete empty 99))))
;; Equal priorities do not promise a particular winning key.
(check-equal "pop removes one minimum and preserves the original" '(10 #f 5 6)
  (call-with-values (lambda () (psq-pop original))
    (lambda (key rest)
      (list (psq-ref original key) (psq-contains? rest key)
            (psq-size rest) (psq-size original)))))
(check-equal "delete-min removes the same key selected by min" '(#f 5 10)
  (let* ((key (psq-min original)) (rest (psq-delete-min original)))
    (list (psq-contains? rest key) (psq-size rest) (psq-ref rest (psq-min rest)))))
(define (drain-priorities queue)
  (if (psq-empty? queue) '()
      (call-with-values (lambda () (psq-pop queue))
        (lambda (key rest) (cons (psq-ref queue key) (drain-priorities rest))))))
(check-equal "successive pops retain ties and follow priority order"
  '(10 10 20 30 40 50) (drain-priorities original))
(check-equal "priority threshold is inclusive and results follow key order"
  '((2 . 10) (4 . 20) (5 . 10)) (psq-at-most original 20))
(check-equal "thresholds below, at and above priorities"
  (list '() '((2 . 10) (5 . 10)) pairs)
  (list (psq-at-most original 0) (psq-at-most original 10) (psq-at-most original 50)))
(check-equal "range queries combine priority and inclusive key bounds"
  '((2 . 10) (3 . 30) (4 . 20)) (psq-at-most-range original 30 2 4))
(check-equal "range boundaries include a single key and can miss all keys"
  '(((2 . 10)) () ())
  (list (psq-at-most-range original 10 2 2)
        (psq-at-most-range original 9 2 2)
        (psq-at-most-range original 100 7 10)))
(check-equal "custom key and priority orderings control queries and minimum"
  '(6 ((6 . 50) (3 . 30) (1 . 40)) ((5 . 10) (4 . 20) (3 . 30) (2 . 10)))
  (let ((descending (insert-all (make-psq > >) pairs)))
    (list (psq-min descending) (psq-at-most descending 30)
          (psq-at-most-range descending 10 5 2))))
(check-equal "key equivalence follows the ordering predicate" '(1 20 20 10)
  (let* ((base (psq-set (make-psq (lambda (a b) (< (abs a) (abs b))) <) -2 10))
         (changed (psq-set base 2 20)))
    (list (psq-size changed) (psq-ref changed -2) (psq-ref changed 2) (psq-ref base -2))))
(check-equal "balancing and deletion preserve all 64 ordered insertions" #t
  (let* ((many (let loop ((key 1) (acc '()))
                 (if (> key 64) (reverse acc)
                     (loop (+ key 1) (cons (cons key (- 65 key)) acc)))))
         (queue (insert-all empty many))
         (reduced (let loop ((key 2) (q queue))
                    (if (> key 64) q (loop (+ key 2) (psq-delete q key)))))
         (odd-pairs (let loop ((rest many))
                      (cond ((null? rest) '())
                            ((odd? (caar rest)) (cons (car rest) (loop (cdr rest))))
                            (else (loop (cdr rest)))))))
    (and (equal? (psq-at-most queue 100) many)
         (equal? (psq-at-most reduced 100) odd-pairs)
         (= (psq-size reduced) 32)
         (equal? (drain-priorities reduced) (reverse (map cdr odd-pairs)))
         (equal? (psq-at-most queue 100) many))))
(check-error "missing key lookup raises" (psq-ref original 99))
(check-error "empty minimum raises" (psq-min empty))
(check-error "empty delete-min raises" (psq-delete-min empty))
(check-error "empty pop raises" (psq-pop empty))
(smoke-finish)
