(import (scheme base) (prefix (pfds vector) v:) (patina compat smoke))
(define original (vector 'a 'b 'c))
(define changed (v:vector-set original 1 'new))
(check-equal "indexed update preserves the source" '(#(a new c) #(a b c))
  (list changed original))
(check-equal "insert at the beginning, middle and end"
  '(#(x a b c) #(a x b c) #(a b c x))
  (list (v:vector-insert original 0 'x) (v:vector-insert original 1 'x)
        (v:vector-insert original 3 'x)))
(check-equal "remove at the beginning, middle and end" '(#(b c) #(a c) #(a b))
  (list (v:vector-remove original 0) (v:vector-remove original 1)
        (v:vector-remove original 2)))
(check-equal "empty and singleton transitions" '(#(x) #())
  (list (v:vector-insert '#() 0 'x) (v:vector-remove '#(x) 0)))
(vector-set! changed 0 'branch)
(check-equal "returned vectors have independent storage" '(#(branch new c) #(a b c))
  (list changed original))
(check-equal "fold visits left to right and preserves the empty base"
  '((c b a) seed)
  (list (v:vector-fold cons '() original)
        (v:vector-fold (lambda args (error "unexpected callback")) 'seed '#())))
(check-error "insert rejects a negative index" (v:vector-insert original -1 'x))
(check-error "insert rejects an index past the end" (v:vector-insert original 4 'x))
(check-error "remove rejects a negative index" (v:vector-remove original -1))
(check-error "remove rejects the end index" (v:vector-remove original 3))
(smoke-finish)
