(import (scheme base) (prefix (pfds lazy-list) lazy:) (patina compat smoke))
(define forced 0)
(define delayed
  (lazy:cons* 'first
    (begin (set! forced (+ forced 1)) (lazy:cons* 'second '()))))
(check-equal "constructing and reading the head leaves the tail delayed" '(first 0)
  (list (lazy:head delayed) forced))
(define first-tail (lazy:tail delayed))
(define second-tail (lazy:tail delayed))
(check-equal "forcing the same tail twice evaluates it once" '(second second 1)
  (list (lazy:head first-tail) (lazy:head second-tail) forced))
(define (naturals n) (lazy:cons* n (naturals (+ n 1))))
(define (to-list xs)
  (if (lazy:empty? xs) '() (cons (lazy:head xs) (to-list (lazy:tail xs)))))
(define numbers (naturals 0))
(check-equal "take terminates on an infinite list" '(0 1 2 3 4)
  (to-list (lazy:take 5 numbers)))
(check-equal "drop advances without changing the original head" '(7 0)
  (list (lazy:head (lazy:drop 7 numbers)) (lazy:head numbers)))
(check-equal "reverse a finite prefix" '(4 3 2 1 0)
  (to-list (lazy:rev (lazy:take 5 numbers))))
(check-equal "append lazy prefixes" '(0 1 2 3 4)
  (to-list (lazy:append* (lazy:take 2 numbers)
                         (lazy:take 3 (lazy:drop 2 numbers)))))
(check-equal "empty tail, take and drop" '(() () ())
  (list (lazy:tail '()) (lazy:take 0 numbers) (lazy:drop 0 '())))
(smoke-finish)
