(import (scheme base) (scheme write) (pfds queue))
(import (patina compat smoke))
(check-equal "empty queue" #t (queue-empty? (make-queue)))
(define original (list->queue '(a b c)))
(define extended (enqueue original 'd))
(check-equal "length after enqueue" 4 (queue-length extended))
(check-equal "FIFO order" '(a b c d) (queue->list extended))
(check-equal "persistent original" '(a b c) (queue->list original))
(check-equal "dequeue returns front and remaining queue" '(a (b c d))
  (call-with-values (lambda () (dequeue extended))
    (lambda (front rest) (list front (queue->list rest)))))
(check-error "empty dequeue" (dequeue (make-queue)))
(smoke-finish)
