(import (scheme base) (pfds alist) (patina compat smoke))
;; These operations do not promise association order.
(check-equal "empty lookup uses its default" 'missing
  (alist-ref '() 1 'missing =))
(define original '((1 . 10) (2 . 20) (3 . #f)))
(check-equal "lookup distinguishes false values from missing keys" '(10 #f absent)
  (list (alist-ref original 1 'absent =)
        (alist-ref original 3 'absent =) (alist-ref original 9 'absent =)))
(define inserted (alist-set original 4 40 =))
(check-equal "insertion preserves existing associations and the source"
  '(4 10 20 #f 40 3 absent)
  (list (length inserted) (alist-ref inserted 1 'absent =)
        (alist-ref inserted 2 'absent =) (alist-ref inserted 3 'absent =)
        (alist-ref inserted 4 'absent =) (length original)
        (alist-ref original 4 'absent =)))
(define replaced (alist-set original 2 99 =))
(check-equal "replacement preserves cardinality and the source" '(3 99 20)
  (list (length replaced) (alist-ref replaced 2 #f =)
        (alist-ref original 2 #f =)))
(define deleted (alist-delete original 2 =))
(check-equal "deletion removes only the requested key" '(2 10 absent #f 20)
  (list (length deleted) (alist-ref deleted 1 'absent =)
        (alist-ref deleted 2 'absent =) (alist-ref deleted 3 'absent =)
        (alist-ref original 2 'absent =)))
(define unchanged (alist-delete original 9 =))
(check-equal "deleting an absent key preserves the associations" '(3 10 20 #f)
  (list (length unchanged) (alist-ref unchanged 1 #f =)
        (alist-ref unchanged 2 #f =) (alist-ref unchanged 3 'absent =)))
(define calls '())
(define (increment old) (set! calls (cons old calls)) (+ old 1))
(define updated (alist-update original 2 increment 100 =))
(define extended (alist-update original 4 increment 100 =))
(check-equal "update calls its procedure once with the value or default"
  '(21 101 (20 100) 20 absent)
  (list (alist-ref updated 2 #f =) (alist-ref extended 4 #f =)
        (reverse calls) (alist-ref original 2 #f =)
        (alist-ref original 4 'absent =)))
(define (same-last-digit? a b) (= (modulo a 10) (modulo b 10)))
(define equivalent (alist-set original 12 120 same-last-digit?))
(check-equal "lookup and replacement honor custom key equivalence" '(3 120 10)
  (list (length equivalent) (alist-ref equivalent 22 #f same-last-digit?)
        (alist-ref equivalent 11 #f same-last-digit?)))
(smoke-finish)
