(import (scheme base) (pfds bounded-balance-tree) (patina compat smoke))
(define empty (make-bbtree <))
(check-equal "empty tree and lookup default" '(#t 0 #f missing)
  (list (bbtree? empty) (bbtree-size empty) (bbtree-contains? empty 1)
        (bbtree-ref empty 1 'missing)))
(define keys '(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16))
(define pairs (map (lambda (key) (cons key (* key 10))) keys))
(define original (alist->bbtree pairs <))
(check-equal "ascending insertion retains sorted associations"
  (list 16 pairs) (list (bbtree-size original) (bbtree->alist original)))
(check-equal "descending insertion retains the same associations"
  pairs (bbtree->alist (alist->bbtree (reverse pairs) <)))
(define replaced (bbtree-set original 8 #f))
(check-equal "replacement preserves size, membership and the source"
  '(16 #t #f 80)
  (list (bbtree-size replaced) (bbtree-contains? replaced 8)
        (bbtree-ref replaced 8 'missing) (bbtree-ref original 8)))
(define reduced
  (bbtree-delete (bbtree-delete (bbtree-delete original 1) 8) 16))
(check-equal "deletion preserves survivors and earlier versions"
  (list 13 '(2 3 4 5 6 7 9 10 11 12 13 14 15) keys)
  (list (bbtree-size reduced) (bbtree-keys (bbtree-delete reduced 99))
        (bbtree-keys original)))
(define calls '())
(define (increment old) (set! calls (cons old calls)) (+ old 1))
(define updated (bbtree-update original 2 increment 99))
(define extended (bbtree-update updated 20 increment 99))
(check-equal "update calls once with an existing value or default"
  '(21 100 (20 99) 17 20 missing)
  (list (bbtree-ref extended 2) (bbtree-ref extended 20) (reverse calls)
        (bbtree-size extended) (bbtree-ref original 2)
        (bbtree-ref original 20 'missing)))
(check-equal "rank tracks key ordering" '(0 7 15)
  (list (bbtree-index original 1) (bbtree-index original 8)
        (bbtree-index original 16)))
(define (indexed tree i)
  (call-with-values (lambda () (bbtree-ref/index tree i)) list))
(check-equal "indexed lookup returns key and value" '((1 10) (8 80) (16 160))
  (list (indexed original 0) (indexed original 7) (indexed original 15)))
(check-equal "fold directions follow key order" (list (reverse keys) keys)
  (list (bbtree-fold (lambda (key value acc) (cons key acc)) '() original)
        (bbtree-fold-right (lambda (key value acc) (cons key acc)) '() original)))
(define mapped (bbtree-map (lambda (value) (+ value 1)) original))
(check-equal "mapping preserves keys and earlier values"
  (list keys 81 80)
  (list (bbtree-keys mapped) (bbtree-ref mapped 8) (bbtree-ref original 8)))
(define left (alist->bbtree '((1 . left-1) (2 . left-2) (4 . left-4)) <))
(define right (alist->bbtree '((2 . right-2) (3 . right-3)) <))
(check-equal "union prefers the left value on duplicate keys"
  '((1 . left-1) (2 . left-2) (3 . right-3) (4 . left-4))
  (bbtree->alist (bbtree-union left right)))
(check-equal "difference removes shared keys" '((1 . left-1) (4 . left-4))
  (bbtree->alist (bbtree-difference left right)))
(check-equal "intersection keeps the left value" '((2 . left-2))
  (bbtree->alist (bbtree-intersection left right)))
(check-equal "empty operands for set operations"
  (list (bbtree->alist left) (bbtree->alist left) '())
  (list (bbtree->alist (bbtree-union empty left))
        (bbtree->alist (bbtree-difference left empty))
        (bbtree->alist (bbtree-intersection left empty))))
(check-equal "explicit traversal visits every node" 16
  (bbtree-traverse (lambda (key value left right count)
                     (right (left (+ count 1))))
                   0 original))
(check-error "indexed lookup rejects the end index" (bbtree-ref/index original 16))
(check-error "missing lookup without a default raises" (bbtree-ref original 99))
(smoke-finish)
