(import (scheme base) (pfds fingertree) (patina compat smoke))
(define (one value) 1)
(define (tree items) (list->fingertree items 0 + one))
(define empty (make-fingertree 0 + one))
(define (range start end)
  (if (= start end) '() (cons start (range (+ start 1) end))))
(define items (range 1 65))
(define original (tree items))
(check-equal "empty tree has the identity measure" '(#t #t 0 ())
  (list (fingertree? empty) (fingertree-empty? empty)
        (fingertree-measure empty) (fingertree->list empty)))
(check-equal "singletons can be added at either end" '((a) (b) 1 1)
  (let ((front (fingertree-cons 'a empty)) (rear (fingertree-snoc empty 'b)))
    (list (fingertree->list front) (fingertree->list rear)
          (fingertree-measure front) (fingertree-measure rear))))
(check-equal "list conversion retains order and measures converted values"
  (list items 64 #f)
  (list (fingertree->list original) (fingertree-measure original)
        (fingertree-empty? original)))
(check-equal "repeated rear insertion grows nested nodes" (list items 64 0)
  (let loop ((rest items) (t empty))
    (if (null? rest)
        (list (fingertree->list t) (fingertree-measure t) (fingertree-measure empty))
        (loop (cdr rest) (fingertree-snoc t (car rest))))))
(check-equal "front insertion preserves the original branch"
  (list (cons 0 items) (append items '(65)) items)
  (list (fingertree->list (fingertree-cons 0 original))
        (fingertree->list (fingertree-snoc original 65))
        (fingertree->list original)))
(check-equal "append joins two deep trees and adds their measures"
  (list (range 1 129) 128 items)
  (let ((joined (fingertree-append original (tree (range 65 129)))))
    (list (fingertree->list joined) (fingertree-measure joined)
          (fingertree->list original))))
(check-equal "append handles empty and singleton operands"
  (list items items (cons 0 items) (append items '(65)))
  (list (fingertree->list (fingertree-append empty original))
        (fingertree->list (fingertree-append original empty))
        (fingertree->list (fingertree-append (tree '(0)) original))
        (fingertree->list (fingertree-append original (tree '(65))))))
(check-equal "uncons returns the value before the remaining tree"
  (list 1 (range 2 65) 63 64)
  (call-with-values (lambda () (fingertree-uncons original))
    (lambda (first rest)
      (list first (fingertree->list rest) (fingertree-measure rest)
            (fingertree-measure original)))))
(check-equal "unsnoc returns the remaining tree before the value"
  (list (range 1 64) 64 63 64)
  (call-with-values (lambda () (fingertree-unsnoc original))
    (lambda (rest last)
      (list (fingertree->list rest) last (fingertree-measure rest)
            (fingertree-measure original)))))
(check-equal "draining the front repairs digits and ends at the identity" #t
  (let loop ((t original) (rest items))
    (and (= (fingertree-measure t) (length rest))
         (if (null? rest)
             (fingertree-empty? t)
             (call-with-values (lambda () (fingertree-uncons t))
               (lambda (first tail)
                 (and (= first (car rest)) (loop tail (cdr rest)))))))))
(check-equal "draining the rear repairs digits and ends at the identity" #t
  (let loop ((t original) (rest (reverse items)))
    (and (= (fingertree-measure t) (length rest))
         (if (null? rest)
             (fingertree-empty? t)
             (call-with-values (lambda () (fingertree-unsnoc t))
               (lambda (tail last)
                 (and (= last (car rest)) (loop tail (cdr rest)))))))))
(check-equal "fold directions visit every nested element in order"
  (list (reverse items) items)
  (list (fingertree-fold cons '() original)
        (fingertree-fold-right cons '() original)))
(check-equal "measured splits cover every boundary and preserve the source" #t
  (let loop ((n 0) (prefix '()) (suffix items))
    (and
      (call-with-values (lambda () (fingertree-split (lambda (m) (> m n)) original))
        (lambda (left right)
          (and (equal? (fingertree->list left) (reverse prefix))
               (equal? (fingertree->list right) suffix)
               (= (fingertree-measure left) n)
               (= (fingertree-measure right) (- 64 n))
               (equal? (fingertree->list original) items))))
      (or (null? suffix) (loop (+ n 1) (cons (car suffix) prefix) (cdr suffix))))))
(check-equal "split handles empty input and an unreached threshold" '((() ()) (64 0))
  (list
    (call-with-values (lambda () (fingertree-split (lambda (m) (> m 0)) empty))
      (lambda (left right) (list (fingertree->list left) (fingertree->list right))))
    (call-with-values (lambda () (fingertree-split (lambda (m) (> m 100)) original))
      (lambda (left right) (list (fingertree-measure left) (fingertree-measure right))))))
(check-equal "split3 separates the pivot from both measured halves"
  (list (range 1 33) 33 (range 34 65) 32 31)
  (call-with-values (lambda () (fingertree-split3 (lambda (m) (> m 32)) original))
    (lambda (left pivot right)
      (list (fingertree->list left) pivot (fingertree->list right)
            (fingertree-measure left) (fingertree-measure right)))))
(check-equal "split uses accumulated value measures rather than positions"
  '((1 2 3 4) (5 6 7 8) 10 26)
  (call-with-values
    (lambda () (fingertree-split (lambda (sum) (> sum 10))
                                (list->fingertree '(1 2 3 4 5 6 7 8) 0 + (lambda (x) x))))
    (lambda (left right)
      (list (fingertree->list left) (fingertree->list right)
            (fingertree-measure left) (fingertree-measure right)))))
(check-equal "noncommutative measures follow append and reversal order"
  (list items (reverse items) (range 1 129))
  (let* ((t (list->fingertree items '() append list))
         (other (list->fingertree (range 65 129) '() append list)))
    (list (fingertree-measure t) (fingertree-measure (fingertree-reverse t))
          (fingertree-measure (fingertree-append t other)))))
(check-equal "reversal preserves the source and the count measure"
  (list (reverse items) items 64)
  (let ((backwards (fingertree-reverse original)))
    (list (fingertree->list backwards) (fingertree->list original)
          (fingertree-measure backwards))))
(define (unexpected . args) (error "empty fold called its callback"))
(check-equal "empty folds preserve their base without callbacks" '(left right)
  (list (fingertree-fold unexpected 'left empty)
        (fingertree-fold-right unexpected 'right empty)))
(check-error "uncons rejects an empty tree" (fingertree-uncons empty))
(check-error "unsnoc rejects an empty tree" (fingertree-unsnoc empty))
(smoke-finish)
