(import (scheme base) (pfds deque) (patina compat smoke))
(check-equal "empty deque" '(#t #t 0)
  (let ((empty (make-deque)))
    (list (deque? empty) (deque-empty? empty) (deque-length empty))))
;; Enough elements to exercise rebalancing, not just the singleton cases.
(define items '(1 2 3 4 5 6 7 8 9 10 11 12))
(define original (list->deque items))
(define extended (enqueue-front (enqueue-rear original 13) 0))
(check-equal "insert at both ends" '(0 1 2 3 4 5 6 7 8 9 10 11 12 13)
  (deque->list extended))
(check-equal "remove front returns item and remaining deque"
  '(0 (1 2 3 4 5 6 7 8 9 10 11 12 13))
  (call-with-values (lambda () (dequeue-front extended))
    (lambda (item rest) (list item (deque->list rest)))))
(check-equal "remove rear returns item and remaining deque"
  '(13 (0 1 2 3 4 5 6 7 8 9 10 11 12))
  (call-with-values (lambda () (dequeue-rear extended))
    (lambda (item rest) (list item (deque->list rest)))))
(check-equal "updates preserve the original deque" items (deque->list original))
(define (drain remove deque)
  (if (deque-empty? deque)
      '()
      (call-with-values (lambda () (remove deque))
        (lambda (item rest) (cons item (drain remove rest))))))
(check-equal "drain through rotations from either end" (list items (reverse items))
  (list (drain dequeue-front original) (drain dequeue-rear original)))
(check-error "empty front removal" (dequeue-front (make-deque)))
(check-error "empty rear removal" (dequeue-rear (make-deque)))
(smoke-finish)
