(import (scheme base) (scheme write) (pfds heap))
(import (patina compat smoke))
(define original (list->heap '(5 1 3 1) <))
(define extended (heap-insert original 0))
(check-equal "ordered contents and duplicates" '(1 1 3 5) (heap->list original))
(check-equal "insert minimum" 0 (heap-min extended))
(check-equal "persistent size" '(4 5) (list (heap-size original) (heap-size extended)))
(check-equal "pop returns minimum and remaining heap" '(0 (1 1 3 5))
  (call-with-values (lambda () (heap-pop extended))
    (lambda (front rest) (list front (heap->list rest)))))
(check-equal "merge" '(1 1 2 3 4 5)
  (heap->list (heap-merge original (list->heap '(4 2) <))))
(check-error "empty minimum" (heap-min (make-heap <)))
(smoke-finish)
