(import (scheme base) (pfds set) (patina compat smoke))
;; Compare membership and size rather than relying on traversal order.
(define (members=? set items)
  (and (= (set-size set) (length items))
       (let loop ((rest items))
         (or (null? rest)
             (and (set-member? set (car rest)) (loop (cdr rest)))))))
(check-equal "empty set" '(#t 0 #f)
  (let ((empty (make-set <)))
    (list (set? empty) (set-size empty) (set-member? empty 1))))
(define original (list->set '(3 1 4 1 5 2) <))
(check-equal "construction removes duplicates" #t (members=? original '(1 2 3 4 5)))
(define changed (set-remove (set-insert original 6) 2))
(check-equal "insertion and removal preserve the source" '(#t #t)
  (list (members=? changed '(1 3 4 5 6)) (members=? original '(1 2 3 4 5))))
(define other (list->set '(4 5 6) <))
(check-equal "union" #t (members=? (set-union original other) '(1 2 3 4 5 6)))
(check-equal "intersection" #t (members=? (set-intersection original other) '(4 5)))
(check-equal "difference" #t (members=? (set-difference original other) '(1 2 3)))
(check-equal "subset and equality" '(#t #f #t)
  (list (proper-subset? (list->set '(1 3) <) original)
        (subset? other original) (set=? original (list->set '(5 4 3 2 1) <))))
(check-equal "mapping can merge elements" #t
  (members=? (set-map (lambda (x) (modulo x 2)) original) '(0 1)))
(check-equal "fold and list conversion visit each element" '(15 #t)
  (list (set-fold + 0 original)
        (set=? original (list->set (set->list original) <))))
(smoke-finish)
