(import (scheme base) (pfds sequence) (patina compat smoke))
(check-equal "empty sequence" '(#t #t 0)
  (let ((empty (make-sequence)))
    (list (sequence? empty) (sequence-empty? empty) (sequence-size empty))))
(define items '(1 2 3 4 5 6 7 8 9 10 11 12))
(define original (list->sequence items))
(check-equal "append and insert at both ends" '(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14)
  (sequence->list
    (sequence-append (sequence-cons 0 original) (sequence-snoc (sequence 13) 14))))
(define changed (sequence-set original 5 'new))
(check-equal "indexed update preserves the source" '(12 6 new 6)
  (list (sequence-size changed) (sequence-ref original 5)
        (sequence-ref changed 5) (sequence-ref original 5)))
(check-equal "split returns both halves" '((1 2 3 4 5) (6 7 8 9 10 11 12))
  (call-with-values (lambda () (sequence-split-at original 5))
    (lambda (left right) (list (sequence->list left) (sequence->list right)))))
(check-equal "take and drop clamp out-of-range positions" (list '() items items '())
  (list (sequence->list (sequence-take original -1))
        (sequence->list (sequence-drop original -1))
        (sequence->list (sequence-take original 20))
        (sequence->list (sequence-drop original 20))))
(check-equal "uncons returns first element then sequence" '(1 (2 3 4 5 6 7 8 9 10 11 12))
  (call-with-values (lambda () (sequence-uncons original))
    (lambda (first rest) (list first (sequence->list rest)))))
(check-equal "unsnoc returns sequence then last element" '((1 2 3 4 5 6 7 8 9 10 11) 12)
  (call-with-values (lambda () (sequence-unsnoc original))
    (lambda (rest last) (list (sequence->list rest) last))))
(check-equal "map and filter preserve order" '(20 40 60 80 100 120)
  (sequence->list (sequence-map (lambda (x) (* x 10))
                                (sequence-filter even? original))))
(check-equal "fold directions" (list (reverse items) items)
  (list (sequence-fold cons '() original) (sequence-fold-right cons '() original)))
(check-equal "reverse preserves the source" (list (reverse items) items)
  (list (sequence->list (sequence-reverse original)) (sequence->list original)))
(check-error "indexed read beyond the end" (sequence-ref original 12))
(check-error "empty removal" (sequence-uncons (make-sequence)))
(smoke-finish)
