(import (scheme base) (pfds difference-list) (patina compat smoke))
(check-equal "empty difference list" '(#t ())
  (let ((empty (dlist))) (list (dlist? empty) (dlist->list empty))))
(define original (list->dlist '(b c)))
(define joined (dlist-append original (dlist 'd 'e)))
(check-equal "append preserves order" '(b c d e) (dlist->list joined))
(define extended (dlist-snoc (dlist-cons 'a joined) 'f))
(check-equal "prepend and append elements" '(a b c d e f) (dlist->list extended))
(check-equal "branches preserve their sources" '((b c) (b c d e))
  (list (dlist->list original) (dlist->list joined)))
(check-equal "empty append on either side" '((b c) (b c))
  (list (dlist->list (dlist-append (dlist) original))
        (dlist->list (dlist-append original (dlist)))))
(define accumulated
  (let loop ((i 0) (result (dlist)))
    (if (= i 10) result (loop (+ i 1) (dlist-snoc result i)))))
(check-equal "composed appends can be materialized repeatedly"
  '((0 1 2 3 4 5 6 7 8 9) (0 1 2 3 4 5 6 7 8 9))
  (list (dlist->list accumulated) (dlist->list accumulated)))
(smoke-finish)
