(import (scheme base) (pfds hash-array-mapped-trie) (patina compat smoke))
;; Hash-table traversal order is unspecified; check associations and size.
(define (associations=? table pairs)
  (and (= (hamt-size table) (length pairs))
       (let loop ((rest pairs))
         (or (null? rest)
             (and (hamt-contains? table (caar rest))
                  (equal? (hamt-ref table (caar rest)) (cdar rest))
                  (loop (cdr rest)))))))
(define (identity x) x)
;; Keep independent regressions visible if an operation unexpectedly raises.
(define-syntax check-result
  (syntax-rules ()
    ((_ label expected body ...)
     (check-equal label expected
       (guard (ex (else 'unexpected-error)) body ...)))))
(define empty (make-hamt identity =))
(check-equal "empty map and lookup default" '(#t 0 #f missing)
  (list (hamt? empty) (hamt-size empty) (hamt-contains? empty 1)
        (hamt-ref empty 1 'missing)))
(check-equal "construction retains hash and equivalence procedures" '(#t #t)
  (list (eqv? identity (hamt-hash-function empty))
        (eqv? = (hamt-equivalence-predicate empty))))
(define original (alist->hamt '((1 . 10) (2 . 20) (3 . 30)) identity =))
(check-equal "insertion preserves the empty version" '(#t 0)
  (list (associations=? original '((1 . 10) (2 . 20) (3 . 30)))
        (hamt-size empty)))
(check-equal "replacement stores false without changing membership or source"
  '(3 #t #f 20)
  (let ((changed (hamt-set original 2 #f)))
    (list (hamt-size changed) (hamt-contains? changed 2)
          (hamt-ref changed 2 'missing) (hamt-ref original 2))))
(check-equal "deletion and absent deletion preserve the source" '(#t #t)
  (list (associations=? (hamt-delete (hamt-delete original 2) 99)
                        '((1 . 10) (3 . 30)))
        (associations=? original '((1 . 10) (2 . 20) (3 . 30)))))
(check-result "update invokes its callback once on existing and absent keys"
  '(21 100 (20 99) 4 20 missing)
  (let* ((calls '())
         (increment (lambda (old) (set! calls (cons old calls)) (+ old 1)))
         (changed (hamt-update original 2 increment 99))
         (extended (hamt-update changed 4 increment 99)))
    (list (hamt-ref extended 2) (hamt-ref extended 4) (reverse calls)
          (hamt-size extended) (hamt-ref original 2)
          (hamt-ref original 4 'missing))))
(check-result "map and fold visit root leaves once" '(#t 66 20)
  (list (associations=? (hamt-map (lambda (v) (+ v 1)) original)
                        '((1 . 11) (2 . 21) (3 . 31)))
        (hamt-fold (lambda (k v acc) (+ k v acc)) 0 original)
        (hamt-ref original 2)))
(check-result "alist construction prefers the leftmost duplicate" #t
  (associations=? (alist->hamt '((1 . first) (2 . other) (1 . last)) identity =)
                  '((1 . first) (2 . other))))
(define (constant-hash key) 33)
(define collisions
  (alist->hamt '((1 . 10) (2 . 20) (3 . 30)) constant-hash =))
(check-result "equal hash codes retain distinct keys" '(#t #t #t)
  (list (associations=? collisions '((1 . 10) (2 . 20) (3 . 30)))
        (associations=? (hamt-set collisions 2 200) '((1 . 10) (2 . 200) (3 . 30)))
        (associations=? collisions '((1 . 10) (2 . 20) (3 . 30)))))
(check-result "collision updates distinguish a value from the default" '(21 100)
  (let ((changed (hamt-update collisions 2 (lambda (v) (+ v 1)) 99)))
    (list (hamt-ref changed 2)
          (hamt-ref (hamt-update changed 4 (lambda (v) (+ v 1)) 99) 4))))
(check-result "collision map and fold visit all values" '(#t 60)
  (list (associations=? (hamt-map (lambda (v) (+ v 1)) collisions)
                        '((1 . 11) (2 . 21) (3 . 31)))
        (hamt-fold (lambda (k v acc) (+ v acc)) 0 collisions)))
(check-result "collision deletion shrinks to a leaf and then an empty map"
  '(#t #t 0 3)
  (let* ((two (hamt-delete collisions 2))
         (one (hamt-delete two 1)))
    (list (associations=? two '((1 . 10) (3 . 30)))
          (associations=? (hamt-delete one 99) '((3 . 30)))
          (hamt-size (hamt-delete one 3)) (hamt-size collisions))))
;; These hashes share the first five bits and branch at later levels.
(define nested-pairs '((1 . 10) (33 . 20) (225 . 30) (993 . 40)))
(check-result "shared low hash bits retain both keys" #t
  (associations=? (alist->hamt '((1 . 10) (33 . 20)) identity =)
                  '((1 . 10) (33 . 20))))
(check-result "sparse subtrie replacement preserves its siblings and source"
  '(#t #t)
  (let* ((table (alist->hamt nested-pairs identity =))
         (changed (hamt-set table 225 300)))
    (list (associations=? changed '((1 . 10) (33 . 20) (225 . 300) (993 . 40)))
          (associations=? table nested-pairs))))
(check-result "sparse subtrie deletion preserves siblings" '(#t #t)
  (let ((table (alist->hamt nested-pairs identity =)))
    (list (associations=? (hamt-delete table 225) '((1 . 10) (33 . 20) (993 . 40)))
          (associations=? (hamt-delete table 65) nested-pairs))))
(check-result "deep prefixes and bignum hashes branch correctly" #t
  (let ((pairs (list (cons 1 10) (cons 1025 20) (cons 32769 30)
                     (cons (+ (expt 2 80) 1) 40))))
    (associations=? (alist->hamt pairs identity =) pairs)))
(check-result "a collision bucket can become a nested branch" '(#t #t)
  (let* ((hash (lambda (k) (if (< k 3) 33 k)))
         (table (hamt-set (hamt-set (make-hamt hash =) 1 10) 2 20))
         (changed (hamt-set table 65 30)))
    (list (associations=? changed '((1 . 10) (2 . 20) (65 . 30)))
          (associations=? table '((1 . 10) (2 . 20))))))
(check-result "mapping nested nodes preserves keys and source values" '(#t #t)
  (let ((table (alist->hamt nested-pairs identity =)))
    (list (associations=? (hamt-map (lambda (v) (+ v 1)) table)
                          '((1 . 11) (33 . 21) (225 . 31) (993 . 41)))
          (associations=? table nested-pairs))))
(check-result "folding nested nodes visits each association once" '(4 1252 100)
  (hamt-fold (lambda (k v acc)
               (list (+ 1 (car acc)) (+ k (cadr acc)) (+ v (car (cddr acc)))))
             '(0 0 0) (alist->hamt nested-pairs identity =)))
(check-result "nested alist conversion retains every association" #t
  (let ((pairs (hamt->alist (alist->hamt nested-pairs identity =))))
    (and (= (length pairs) 4)
         (associations=? (alist->hamt pairs identity =) nested-pairs))))
(check-result "deleting every nested key allows reinsertion" '(0 #t)
  (let loop ((table (alist->hamt nested-pairs identity =)) (rest nested-pairs))
    (if (null? rest)
        (list (hamt-size table) (associations=? (hamt-set table 33 200) '((33 . 200))))
        (loop (hamt-delete table (caar rest)) (cdr rest)))))
(check-result "mixed persistent operations agree with an alist model" #t
  (let ()
    (define (without pairs key)
      (cond ((null? pairs) '())
            ((= key (caar pairs)) (cdr pairs))
            (else (cons (car pairs) (without (cdr pairs) key)))))
    (define (put pairs key value) (cons (cons key value) (without pairs key)))
    (define (sum pairs)
      (if (null? pairs) 0 (+ (cdar pairs) (sum (cdr pairs)))))
    (let hashes ((rest (list identity constant-hash
                            (lambda (k) (+ 1 (* 32 (modulo k 7))))
                            (lambda (k) (+ 1 (* 1024 k)))
                            (lambda (k) (+ 1 (* (expt 2 80) k))))))
      (or (null? rest)
          (and
            (let loop ((step 0) (table (make-hamt (car rest) =)) (model '()))
              (or (= step 96)
                  (let* ((key (modulo (+ (* step 17) (truncate-quotient step 7)) 32))
                         (op (modulo step 5))
                         (old (assv key model))
                         (next-model
                           (case op
                             ((0 1) (put model key step))
                             ((2) (put model key (+ 7 (if old (cdr old) 0))))
                             ((3) (without model key))
                             (else (map (lambda (p) (cons (car p) (+ 1 (cdr p)))) model))))
                         (next
                           (case op
                             ((0 1) (hamt-set table key step))
                             ((2) (hamt-update table key (lambda (v) (+ 7 v)) 0))
                             ((3) (hamt-delete table key))
                             (else (hamt-map (lambda (v) (+ 1 v)) table)))))
                    (and (associations=? next next-model)
                         (associations=? table model)
                         (= (sum next-model)
                            (hamt-fold (lambda (k v acc) (+ v acc)) 0 next))
                         (loop (+ step 1) next next-model)))))
            (hashes (cdr rest)))))))
(check-error "missing lookup without a default raises" (hamt-ref original 99))
(smoke-finish)
