(import (scheme base) (rebottled pstk) (patina compat smoke))
;; Replace only the exported transport binding, then run the pinned command
;; builders and widget cache. No subprocess, GUI or Tcl interpreter is started.
(define saved-eval tk-eval)
(define commands '())
(define response "")
(define (capture cmd) (set! commands (cons cmd commands)) response)
(define (command thunk) (set! commands '()) (thunk) (car commands))
(set! tk-eval capture)
(check-equal "simple command" "bell" (command (lambda () (tk/bell))))
(check-equal "symbol and numeric arguments" "after 10 update" (command (lambda () (tk/after 10 'update))))
(check-equal "options and booleans" "wm -resizable 1 0" (command (lambda () (tk/wm 'resizable: #t #f))))
(check-equal "empty list argument" "bind .w {}" (command (lambda () (tk/bind '.w '()))))
(check-equal "list arguments retain grouping" "pack {a b}" (command (lambda () (tk/pack '(a b)))))
(check-equal "string escaping protects Tcl substitution" "clipboard \"a\\u0024b\\u005bc\\]\\\"d\\\\e\""
  (command (lambda () (tk/clipboard "a$b[c]\"d\\e"))))
(check-equal "numeric strings stay numeric" "tk scaling 1.5" (command (lambda () (tk/scaling "1.5"))))
(check-equal "command return value is forwarded" "answer" (begin (set! response "answer") (tk/bell)))
(check-equal "variable setter names scoped variable" "set ::scmVar(x) {hello}" (command (lambda () (tk-set-var! 'x "hello"))))
(check-equal "variable getter names scoped variable" "set ::scmVar(x)" (command (lambda () (tk-get-var 'x))))
(check-equal "variable constructor returns Tcl name" "::scmVar(x)" (tk-var 'x))
(check-equal "theme names are split" '("light" "dark") (begin (set! response "light dark") (ttk/available-themes)))
(check-equal "missing widget returns false" #f (begin (set! response (string-copy "0")) (tk-id->widget '.missing)))
(set! response "1")
(define widget (tk-id->widget '.present))
(check-equal "widget reports its id" ".present" (widget 'get-id))
(check-equal "widget lookup reuses cached procedure" #t (eq? widget (tk-id->widget '.present)))
(check-equal "widget argument serializes as its path" "pack .present" (command (lambda () (tk/pack widget))))
(check-equal "widget command serializes options" ".present configure -text \"hi\"" (command (lambda () (widget 'configure 'text: "hi"))))
(check-equal "configured option is cached" "hi" (widget 'cget 'text:))
(check-equal "with-lock executes callback exactly once" 1 (let ((n 0)) (tk-with-lock (lambda () (set! n (+ n 1)))) n))
(check-equal "missing widget after a cached widget returns false" #f
  (begin (set! response (string-copy "0")) (tk-id->widget '.absent)))
(check-equal "false text also rejects a missing widget" #f
  (begin (set! response (string-copy "false")) (tk-id->widget '.absent-false)))
(set! response "1")
(define another-widget (tk-id->widget '.another))
(check-equal "a second distinct widget is constructed" ".another" (another-widget 'get-id))
(check-equal "older cache entry survives newer widget insertion" #t (eq? widget (tk-id->widget '.present)))
(set! tk-eval saved-eval)
(smoke-finish)
