(import (scheme base) (prefix (slib time-zone) z:) (prefix (slib time-core) t:)
        (patina compat time-fixtures) (patina compat smoke))
(define-syntax observed
  (syntax-rules () ((_ expr) (guard (ex (else 'unexpected-error)) expr))))
(check-equal "zero offset parses as a fixed zone" '#(tz:fixed "UTC0" "UTC" 0) (z:time-zone "UTC0"))
(check-equal "positive offsets are seconds west of Greenwich" '(0 18000 "EST")
  (t:tz:params 0 (z:time-zone "EST5")))
(check-equal "signed hour-minute-second offsets retain their sign" '(0 -19815 "IST")
  (t:tz:params 0 (z:time-zone "IST-5:30:15")))
(check-equal "explicit positive signs are accepted" '(0 19800 "ABC")
  (t:tz:params 0 (z:time-zone "ABC+5:30")))
(check-equal "a parsed timezone can be passed through unchanged" #t
  (let ((zone (z:time-zone "UTC0"))) (eq? zone (z:time-zone zone))))
(check-equal "DST offset defaults to one hour ahead of standard" '("EST" "EDT" 18000 14400)
  (let ((zone (z:time-zone "EST5EDT")))
    (map (lambda (i) (vector-ref zone i)) '(2 3 4 5))))
(check-equal "explicit DST offsets are preserved" '(18000 12600)
  (let ((zone (z:time-zone "EST5EDT3:30")))
    (list (vector-ref zone 4) (vector-ref zone 5))))
(check-equal "month-week-day rules preserve explicit and default times" '((3 2 0 7200) (11 1 0 7200))
  (let ((zone (z:time-zone "EST5EDT,M3.2.0/2,M11.1.0")))
    (list (vector-ref zone 6) (vector-ref zone 7))))
(check-equal "Julian transition dates parse separately from ordinal dates" '((#f #f 60 3600) (#f #f 300 7200))
  (observed (let ((zone (z:time-zone "STD0DST,J60/1,J300")))
    (list (vector-ref zone 6) (vector-ref zone 7)))))
(check-equal "zero-based ordinal rules include day zero" '((#f #t 0 0) (#f #t 365 82800))
  (observed (let ((zone (z:time-zone "STD0DST,0/0,365/23")))
    (list (vector-ref zone 6) (vector-ref zone 7)))))
(check-equal "parsed rules drive the actual transition boundary" '((0 18000 "EST") (1 14400 "EDT"))
  (let ((zone (z:time-zone "EST5EDT,M3.2.0/2,M11.1.0/2")))
    (map (lambda (t) (t:tz:params t zone)) '(1710053999 1710054000))))
(check-equal "invalid empty zone strings return false" #f (observed (z:time-zone "")))
(check-equal "out-of-range offsets return false" '(#f #f #f)
  (map (lambda (s) (observed (z:time-zone s))) '("UTC24" "UTC1:60" "UTC1:2:60")))
(check-equal "incomplete offsets return false" '(#f #f)
  (map (lambda (s) (observed (z:time-zone s))) '("UTC1:" "UTC1:2:")))
(check-equal "invalid transition fields return false" '(#f #f #f #f)
  (map (lambda (s) (observed (z:time-zone s)))
       '("STD0DST,M13.1.0,M11.1.0" "STD0DST,M3.0.0,M11.1.0"
         "STD0DST,M3.1.7,M11.1.0" "STD0DST,M3.1,M11.1.0")))
(check-equal "trailing transition junk is rejected" #f
  (observed (z:time-zone "STD0DST,M3.2.0/2junk,M11.1.0/2")))
(check-equal "read-tzfile wraps a binary fixture as a zone" '(tz:file 3 2)
  (call-with-tzif #f (lambda (path)
    (let ((zone (z:read-tzfile path)))
      (list (vector-ref zone 0) (vector-length (vector-ref zone 4)) (vector-length (vector-ref zone 2)))))))
(check-equal "colon syntax loads explicit timezone paths and resolves names" '(1 14400 "DST")
  (call-with-tzif #f (lambda (path)
    (t:tz:params 200 (z:time-zone (string-append ":" path))))))
(check-error "a missing explicit timezone file raises an error"
  (let ((path (call-with-binary-fixture #u8() (lambda (path) path)))) (z:read-tzfile path)))
(check-equal "Julian and ordinal day ranges are validated" '(#f #f #f)
  (map (lambda (s) (observed (z:time-zone s)))
       '("STD0DST,J0,J300" "STD0DST,J366,J300" "STD0DST,366,300")))
(check-equal "incomplete transition times are rejected" '(#f #f #f)
  (map (lambda (s) (observed (z:time-zone s)))
       '("STD0DST,M3.2.0/,M11.1.0" "STD0DST,M3.2.0/1:,M11.1.0"
         "STD0DST,M3.2.0/1:2:,M11.1.0")))
(check-equal "invalid daylight offsets cannot create a rule containing false" '(#f #f)
  (map (lambda (s) (observed (z:time-zone s))) '("STD0DST24" "STD0DST1:")))
(check-equal "complete offset fields accept leading zeros and upper bounds" '(0 86399 "ABC")
  (t:tz:params 0 (z:time-zone "ABC+023:059:059")))
(smoke-finish)
