(import (scheme base) (prefix (slib filename) f:) (patina compat smoke))
(define-syntax observed
  (syntax-rules () ((_ expr) (guard (ex (else 'unexpected-error)) expr))))
(define (matches pattern s) (and ((f:filename:match?? pattern) s) #t))
(check-equal "literal matches are anchored" '(#t #f #f) (map (lambda (s) (matches "a.scm" s)) '("a.scm" "xa.scm" "a.scmx")))
(check-equal "stars include empty strings, separators and dotfiles" '(#t #t #t)
  (map (lambda (s) (matches "*" s)) '("" "a/b" ".hidden")))
(check-equal "question marks match exactly one character" '(#t #f #f)
  (map (lambda (s) (matches "a?c" s)) '("abc" "ac" "abbc")))
(check-equal "ranges include endpoints" '(#t #t #f)
  (map (lambda (s) (matches "[a-c]" s)) '("a" "c" "d")))
(check-equal "negated ranges exclude their set" '(#t #f #t)
  (list (matches "[!a-c]" "z") (matches "[^a-c]" "b") (matches "[-a]" "-")))
(check-equal "empty patterns match only empty strings" '(#t #f)
  (list (matches "" "") (matches "" "a")))
(check-equal "case-insensitive matches preserve wildcard behavior" '(#t #f)
  (list (and ((f:filename:match-ci?? "A[BC]*.SCM") "acfile.scm") #t) (matches "A*" "abc")))
(check-equal "wildcard substitution captures ranges and suffixes" "scm5c4_10.htm"
  ((f:filename:substitute?? "scm_[0-9]*.html" "scm5c4_??.htm") "scm_10.html"))
(check-equal "greedy wildcard captures follow the documented example" "banaNA"
  ((f:filename:substitute?? "*na*" "?NA?") "banana"))
(check-equal "procedure substitution gets captures in order" '("A" "B" "Z")
  ((f:filename:substitute?? "?*?" list) "ABZ"))
(check-equal "nonmatching substitutions return false" #f ((f:filename:substitute?? "*.scm" "*.rs") "x.txt"))
(check-equal "case-insensitive substitution preserves captured case" "Hello.rs"
  ((f:filename:substitute-ci?? "*.SCM" "*.rs") "Hello.scm"))
(check-equal "suffix replacement handles strings and lists" '("a.rs" ("b.rs" "c.rs"))
  (list (f:replace-suffix "a.scm" ".scm" ".rs") (f:replace-suffix '("b.scm" "c.scm") ".scm" ".rs")))
(check-error "missing suffix is an error" (f:replace-suffix "a.txt" ".scm" ".rs"))
(check-error "unclosed match sets are rejected" (f:filename:match?? "[ab"))
(check-error "template wildcard counts must agree" (f:filename:substitute?? "*" "??"))
(check-equal "zero temporary names call the callback without arguments" 0
  (f:call-with-tmpnam (lambda args (length args)) 0))
(check-equal "temporary-name callback preserves multiple return values" '(a b)
  (observed (call-with-values (lambda () (f:call-with-tmpnam (lambda () (values 'a 'b)) 0)) list)))
(check-equal "temporary-name callback preserves zero return values" '()
  (observed (call-with-values (lambda () (f:call-with-tmpnam (lambda () (values)) 0)) list)))
(smoke-finish)
