(import (scheme base) (prefix (slib color) c:) (patina compat smoke))
(define (observe thunk) (guard (ex (else 'unexpected-error)) (thunk)))
(define red (c:color:sRGB 255 0 0))
(check-equal "color predicate distinguishes records and encodings" '(#t #t #f #f)
  (list (c:color? red) (c:color? red 'sRGB) (c:color? red 'CIEXYZ) (c:color? '(255 0 0))))
(check-equal "sRGB constructor retains coordinates and precision" '(sRGB 8 (255 0 0))
  (list (c:color-space red) (c:color-precision red) (c:color->sRGB red)))
(check-equal "packed integer colors unpack channels" '(18 52 86)
  (c:color->sRGB (c:xRGB->color #x123456)))
(check-equal "packing a color preserves all channels" #x123456
  (c:color->xRGB (c:sRGB->color '(18 52 86))))
(check-equal "invalid sRGB channels and lengths return false" '(#f #f #f)
  (list (c:sRGB->color '(256 0 0)) (c:sRGB->color '(-1 0 0)) (c:sRGB->color '(1 2))))
(check-error "positional constructor rejects an invalid channel" (c:color:sRGB 256 0 0))
(check-error "unknown spaces are rejected" (c:make-color 'unknown '(1 2 3)))
(check-equal "make-color dispatches linear RGB and XYZ" '(RGB709 CIEXYZ)
  (list (c:color-space (c:make-color 'RGB709 '(0.2 0.4 0.6)))
        (c:color-space (c:make-color 'CIEXYZ '(0.2 0.3 0.4)))))
(check-equal "extended colors retain precision" '(e-sRGB 10 (0 128 255))
  (let ((color (c:make-color 'e-sRGB 10 '(384 640 894))))
    (list (c:color-space color) (c:color-precision color) (c:color->sRGB color))))
(check-equal "conversion through XYZ retains sRGB channels" '(255 0 0)
  (c:color->sRGB (c:convert-color red 'CIEXYZ)))
(check-equal "conversion through each perceptual space retains sRGB channels" '((255 0 0) (255 0 0) (255 0 0))
  (map (lambda (space) (c:color->sRGB (c:convert-color red space))) '(L*a*b* L*u*v* L*C*h)))
(check-equal "extended precision conversion preserves color" '(16 (255 0 0))
  (let ((color (c:convert-color red 'e-sRGB 16)))
    (list (c:color-precision color) (c:color->sRGB color))))
(check-equal "ordinary colors use the D65 whitepoint" #t
  (eq? c:D65 (c:color-white-point red)))
(check-equal "perceptual colors expose their explicit whitepoint" #t
  (observe (lambda ()
    (= 0 (c:CIE:DE* c:D50 (c:color-white-point (c:make-color 'L*a*b* '(50 0 0) c:D50)))))))
(check-equal "sRGB has an exact textual representation" "sRGB:255/0/0" (c:color->string red))
(check-equal "text parser accepts hexadecimal RGB" '(255 0 128)
  (c:color->sRGB (c:string->color "#ff0080")))
(check-equal "text round trips sRGB including zero channels" '(255 0 0)
  (observe (lambda () (c:color->sRGB (c:string->color (c:color->string red))))))
(check-equal "text round trips extended precision" '(10 (0 128 255))
  (observe (lambda ()
    (let* ((color (c:make-color 'e-sRGB 10 '(384 640 894)))
           (copy (c:string->color (c:color->string color))))
      (list (c:color-precision copy) (c:color->sRGB copy))))))
(check-equal "unrecognized color text returns false" #f (c:string->color "not-a-color"))
(check-equal "Euclidean difference measures neutral lightness" #t
  (< (abs (- 10 (c:CIE:DE* (c:make-color 'L*a*b* '(50 0 0))
                            (c:make-color 'L*a*b* '(60 0 0))))) 1e-9))
(check-equal "CIE94 difference dispatches through color records" #t
  (< (abs (c:CIE:DE*94 red red)) 1e-9))
(check-equal "CMC identity difference is zero" #t (< (abs (c:CMC:DE* red red)) 1e-9))
(check-error "conversion rejects values other than colors" (c:convert-color 'bad 'sRGB))
(check-error "conversion rejects unexpected options for sRGB" (c:convert-color red 'sRGB 8))
(check-equal "0x color syntax decodes a six-character string" '(18 52 86)
  (observe (lambda () (c:color->sRGB (c:string->color "0x123456")))))
(check-equal "each perceptual encoding exposes an explicit whitepoint" '(#t #t #t)
  (map (lambda (space)
         (observe (lambda ()
           (= 0 (c:CIE:DE* c:D50 (c:color-white-point (c:make-color space '(50 0 0) c:D50)))))))
       '(L*a*b* L*u*v* L*C*h)))
(check-equal "text round trips XYZ and all perceptual encodings" '(CIEXYZ L*a*b* L*u*v* L*C*h RGB709)
  (map (lambda (space)
         (observe (lambda ()
           (c:color-space (c:string->color
             (c:color->string (c:convert-color red space)))))))
       '(CIEXYZ L*a*b* L*u*v* L*C*h RGB709)))
(smoke-finish)
