(import (scheme base) (slib line-io) (patina compat smoke))
(define input (open-input-string "abc\n\ntail"))
(define buffer (make-string 8 #\.))
(check-equal "read line length" 3 (read-line! buffer input))
(check-equal "read line mutates only the filled prefix" "abc....." buffer)
(check-equal "empty line has zero length" 0 (read-line! buffer input))
(check-equal "final line needs no newline" 4 (read-line! buffer input))
(check-equal "final line contents" "tail...." buffer)
(check-equal "read past final line returns EOF" #t (eof-object? (read-line! buffer input)))
(define output (open-output-string))
(write-line "first" output)
(parameterize ((current-output-port output)) (write-line "second"))
(check-equal "explicit and current output ports" "first\nsecond\n"
  (get-output-string output))
(smoke-finish)
