(import (scheme base) (prefix (slib common-list-functions) l:) (patina compat smoke))
(check-equal "adjoin inserts a missing element" '(a b c) (l:adjoin 'a '(b c)))
(check-equal "adjoin reuses the list when the element is already present" #t
  (let ((items (list 'a 'b))) (eq? items (l:adjoin 'b items))))
(check-equal "adjoin works on an empty list" '(a) (l:adjoin 'a '()))
(check-equal "left fold passes accumulator before the item" '(((seed a) b) c)
  (l:fold-left list 'seed '(a b c)))
(check-equal "right fold passes the item before its accumulated tail" '(a (b (c seed)))
  (l:fold-right list 'seed '(a b c)))
(check-equal "empty folds return their seed without invoking the callback" '(left right 0)
  (let ((calls 0))
    (let ((f (lambda (x y) (set! calls (+ calls 1)) (list x y))))
      (list (l:fold-left f 'left '()) (l:fold-right f 'right '()) calls))))
(check-equal "positions select the first match and report absence" '(0 1 #f #f)
  (list (l:position 'a '(a b a)) (l:position 'b '(a b a))
        (l:position 'z '(a b a)) (l:position 'a '())))
(check-equal "reduce uses the first element as the left-fold seed" '((a b) c)
  (l:reduce list '(a b c)))
(check-equal "reduce has defined empty and singleton cases" '(() a 0)
  (let ((calls 0))
    (let ((f (lambda (x y) (set! calls (+ calls 1)) (list x y))))
      (list (l:reduce f '()) (l:reduce f '(a)) calls))))
(check-equal "reduce visits each remaining element once" '(10 3)
  (let ((calls 0))
    (let ((sum (l:reduce (lambda (x y) (set! calls (+ calls 1)) (+ x y)) '(1 2 3 4))))
      (list sum calls))))
(smoke-finish)
