(import (scheme base) (prefix (slib dynamic) d:) (patina compat smoke))
(define x (d:make-dynamic 'outer))
(define y (d:make-dynamic 'other))
(check-equal "dynamic predicate distinguishes handles from ordinary values" '(#t #f)
  (list (d:dynamic? x) (d:dynamic? 'outer)))
(check-equal "independent dynamics keep independent values" '(outer other)
  (list (d:dynamic-ref x) (d:dynamic-ref y)))
(check-equal "assignment changes only the selected dynamic" '(changed other)
  (begin (d:dynamic-set! x 'changed) (list (d:dynamic-ref x) (d:dynamic-ref y))))
(check-equal "temporary binding returns its result and restores the outer value" '(inner changed)
  (let ((result (d:call-with-dynamic-binding x 'inner (lambda () (d:dynamic-ref x)))))
    (list result (d:dynamic-ref x))))
(check-equal "nested bindings restore the immediately enclosing value" '((first second first) changed)
  (let ((result (d:call-with-dynamic-binding x 'first
    (lambda () (let* ((before (d:dynamic-ref x))
                     (middle (d:call-with-dynamic-binding x 'second (lambda () (d:dynamic-ref x)))))
      (list before middle (d:dynamic-ref x)))))))
    (list result (d:dynamic-ref x))))
(check-equal "assignment inside a temporary binding does not change the outer value" '(updated changed)
  (let ((result (d:call-with-dynamic-binding x 'inner
    (lambda () (d:dynamic-set! x 'updated) (d:dynamic-ref x)))))
    (list result (d:dynamic-ref x))))
(check-equal "binding forwards multiple values" '(a b)
  (call-with-values (lambda () (d:call-with-dynamic-binding x 'inner (lambda () (values 'a 'b)))) list))
(check-equal "binding forwards zero values" '()
  (call-with-values (lambda () (d:call-with-dynamic-binding x 'inner (lambda () (values)))) list))
(check-equal "exception escape restores the outer value" '(caught changed)
  (let ((result (guard (ex (else 'caught))
    (d:call-with-dynamic-binding x 'inner (lambda () (error "test exception"))))))
    (list result (d:dynamic-ref x))))
(check-equal "continuation escape restores the outer value" '(inner changed)
  (let ((result (call/cc (lambda (exit)
    (d:call-with-dynamic-binding x 'inner (lambda () (exit (d:dynamic-ref x))))))))
    (list result (d:dynamic-ref x))))
(check-equal "continuation reentry restores the saved binding and its mutation" '((inner updated) changed)
  (let ((resume #f) (again #f) (seen '()))
    (d:call-with-dynamic-binding x 'inner
      (lambda ()
        (call/cc (lambda (k) (set! resume k)))
        (set! seen (cons (d:dynamic-ref x) seen))
        (d:dynamic-set! x 'updated)))
    (if (not again) (begin (set! again #t) (resume 'resume)))
    (list (reverse seen) (d:dynamic-ref x))))
(check-error "dynamic-ref rejects ordinary objects" (d:dynamic-ref 'not-a-dynamic))
(check-error "dynamic-set rejects ordinary objects" (d:dynamic-set! 'not-a-dynamic 1))
(smoke-finish)
