(import (scheme base) (prefix (srfi 63) a:) (prefix (slib array-for-each) f:)
        (patina compat smoke))
(define (observe thunk) (guard (ex (else 'unexpected-error)) (thunk)))
(define (grid) (a:list->array 2 '#() '((1 2 3) (4 5 6))))
(check-equal "mapping allocates a new array of the input shape" '(((2 4 6) (8 10 12)) ((1 2 3) (4 5 6)))
  (let* ((input (grid)) (result (f:array-map '#() (lambda (x) (* 2 x)) input)))
    (list (a:array->list result) (a:array->list input))))
(check-equal "mapping combines corresponding cells from multiple arrays" '((11 22 33) (44 55 66))
  (a:array->list (f:array-map '#() + (grid) (a:list->array 2 '#() '((10 20 30) (40 50 60))))))
(check-equal "destructive mapping permits the destination as an input" '((2 3 4) (5 6 7))
  (let ((input (grid)))
    (f:array-map! input (lambda (x) (+ x 1)) input) (a:array->list input)))
(check-equal "mapping visits only the destination's dimensions" '(1 2)
  (let ((dest (a:make-array '#(0) 2)))
    (f:array-map! dest (lambda (x) x) '#(1 2 3)) (a:array->list dest)))
(check-equal "for-each visits tuples in row-major order" '((1 10) (2 20) (3 30) (4 40) (5 50) (6 60))
  (let ((seen '()))
    (f:array-for-each (lambda (x y) (set! seen (cons (list x y) seen)))
      (grid) (a:list->array 2 '#() '((10 20 30) (40 50 60))))
    (reverse seen)))
(check-equal "array-indexes records each cell's coordinates" '(((0 0) (0 1) (0 2)) ((1 0) (1 1) (1 2)))
  (a:array->list (f:array-indexes (grid))))
(check-equal "index iteration visits every coordinate once" '((1 1 1) (1 1 1))
  (let ((seen (a:make-array '#(0) 2 3)))
    (f:array-index-for-each seen
      (lambda (i j) (a:array-set! seen (+ 1 (a:array-ref seen i j)) i j)))
    (a:array->list seen)))
(check-equal "index mapping receives coordinates in dimension order" '((0 1 2) (10 11 12))
  (let ((dest (a:make-array '#(0) 2 3)))
    (f:array-index-map! dest (lambda (i j) (+ (* 10 i) j))) (a:array->list dest)))
(check-equal "empty dimensions invoke no callbacks" 0
  (let ((empty (a:make-array '#(0) 2 0)) (calls 0))
    (define (visit . xs) (set! calls (+ calls 1)) 0)
    (f:array-map! empty visit empty) (f:array-for-each visit empty)
    (f:array-index-for-each empty visit) (f:array-index-map! empty visit)
    calls))
(check-equal "rank-zero mapping calls its procedure once" '(10 1)
  (observe (lambda ()
    (let ((scalar (a:make-array '#(9))) (calls 0))
      (let ((result (f:array-map '#() (lambda (x) (set! calls (+ calls 1)) (+ x 1)) scalar)))
        (list (a:array-ref result) calls))))))
(check-equal "rank-zero for-each visits the scalar element" '(9)
  (observe (lambda ()
    (let ((seen '()))
      (f:array-for-each (lambda (x) (set! seen (cons x seen))) (a:make-array '#(9))) seen))))
(check-equal "destructive scalar mapping combines corresponding inputs" 13
  (observe (lambda ()
    (let ((dest (a:make-array '#(0))))
      (f:array-map! dest + (a:make-array '#(9)) (a:make-array '#(4))) (a:array-ref dest)))))
(check-equal "scalar iteration passes one tuple of all inputs" '((9 4))
  (observe (lambda ()
    (let ((seen '()))
      (f:array-for-each (lambda xs (set! seen (cons xs seen)))
        (a:make-array '#(9)) (a:make-array '#(4))) seen))))
(check-equal "rank-zero index operations use an empty coordinate list" '(() 7)
  (let ((scalar (a:make-array '#(0))))
    (let ((indexes (a:array-ref (f:array-indexes scalar))))
      (f:array-index-map! scalar (lambda () 7)) (list indexes (a:array-ref scalar)))))
(check-equal "array copying preserves source contents" '((1 2 3) (1 2 3))
  (let ((source (vector 1 2 3)) (dest (vector 0 0 0)))
    (f:array:copy! dest source) (list (vector->list dest) (vector->list source))))
(check-equal "copying into a larger destination leaves its other cells intact" '((1 2 9) (3 4 9) (9 9 9))
  (observe (lambda ()
    (let ((dest (a:make-array '#(9) 3 3)))
      (f:array:copy! dest (a:list->array 2 '#() '((1 2) (3 4)))) (a:array->list dest)))))
(check-equal "copying an empty source changes no destination cells" '(9 9)
  (observe (lambda ()
    (let ((dest (vector 9 9))) (f:array:copy! dest '#()) (vector->list dest)))))
(check-equal "copying scalar arrays visits their single element" 7
  (observe (lambda ()
    (let ((dest (a:make-array '#(0))))
      (f:array:copy! dest (a:make-array '#(7))) (a:array-ref dest)))))
(smoke-finish)
