(import (scheme base) (scheme file) (prefix (slib common) c:)
        (patina compat time-fixtures) (patina compat smoke))
(define-syntax observed
  (syntax-rules () ((_ expr) (guard (ex (else 'unexpected-error)) expr))))
(check-equal "identity preserves object identity" #t
  (let ((x (vector 1))) (eq? x (c:identity x))))
(check-equal "exchanger returns the old value and retains the new one" '(first second)
  (let* ((exchange (c:make-exchanger 'first)) (a (exchange 'second)) (b (exchange 'third)))
    (list a b)))
(check-equal "generated temporary symbols are distinct" #t
  (let ((a (c:gentemp)) (b (c:gentemp))) (and (symbol? a) (symbol? b) (not (eq? a b)))))
(check-equal "temporary pathnames are distinct strings" #t
  (let ((a (c:tmpnam)) (b (c:tmpnam))) (and (string? a) (string? b) (not (string=? a b)))))
(check-equal "default output dimensions are stable with or without a port" '(24 79 24 79)
  (list (c:output-port-height) (c:output-port-width)
        (c:output-port-height (current-output-port)) (c:output-port-width (current-output-port))))
(check-equal "known numerical features and absent object hashing are explicit" '(#t #t #t #t #t #f)
  (map c:provided? '(array bignum complex inexact real object-hash)))
(check-error "unknown feature names are rejected" (c:provided? 'unknown-feature))
(check-equal "base-table registration preserves precedence and parameter extent" '((second first) ())
  (let ((inside (parameterize ((c:base-table-implementations '()))
    (c:add-base-table-implementation 'first)
    (c:add-base-table-implementation 'second)
    (c:base-table-implementations))))
    (list inside (c:base-table-implementations))))
(check-equal "load-pathname extent forwards multiple return values" '(one two)
  (call-with-values (lambda () (c:with-load-pathname "sample.scm" (lambda () (values 'one 'two)))) list))
(check-equal "warnings use the dynamically selected error port" "Warn:  marker 3\n"
  (let ((port (open-output-string)))
    (parameterize ((current-error-port port)) (c:slib:warn 'marker 3)) (get-output-string port)))
(check-equal "procedure-first port call returns its result and closes every port" '(#\x #f #f)
  (let* ((in (open-input-string "x")) (out (open-output-string))
         (result (c:call-with-open-ports (lambda (in out) (read-char in)) in out)))
    (list result (input-port-open? in) (output-port-open? out))))
(check-equal "procedure-last port call preserves argument order" '(#\a #\b #f #f)
  (let* ((a (open-input-string "a")) (b (open-input-string "b"))
         (result (c:call-with-open-ports a b (lambda (a b) (list (read-char a) (read-char b))))))
    (append result (list (input-port-open? a) (input-port-open? b)))))
(check-equal "port calls preserve zero return values" '()
  (observed (call-with-values (lambda () (c:call-with-open-ports (lambda () (values)))) list)))
(check-equal "port calls preserve multiple return values and close their ports" '((one two) #f)
  (let* ((in (open-input-string ""))
         (result (observed (call-with-values
           (lambda () (c:call-with-open-ports in (lambda (in) (values 'one 'two)))) list))))
    (let ((open? (input-port-open? in))) (close-port in) (list result open?))))
(check-equal "binary file input preserves all octets" '(0 127 128 255)
  (call-with-binary-fixture #u8(0 127 128 255)
    (lambda (path) (c:call-with-open-ports (c:open-file path 'rb)
      (lambda (in) (let loop ((n 4) (xs '()))
        (if (zero? n) (reverse xs) (loop (- n 1) (cons (read-u8 in) xs)))))))))
(check-equal "text input opens the same fixture in character mode" "abc"
  (call-with-binary-fixture #u8(97 98 99)
    (lambda (path) (c:call-with-open-ports (c:open-file path 'r) (lambda (in) (read-string 3 in))))))
(check-equal "opening a removed fixture for input returns false" '(#f #f)
  (let ((path (call-with-binary-fixture #u8() (lambda (path) path))))
    (list (c:open-file path 'r) (c:open-file path 'rb))))
(check-error "invalid file modes are rejected" (c:open-file "unused" 'invalid))
(smoke-finish)
