(import (scheme base) (prefix (slib chapter-order) c:) (patina compat smoke))
(check-equal "numeric runs sort by chapter length" #t (c:chap:string<? "a.9" "a.10"))
(check-equal "alphabetic runs sort by chapter length" #t (c:chap:string<? "4c" "4aa"))
(check-equal "embedded numeric chapter examples" #t (c:chap:string<? "Revised^{3.99}" "Revised^{4}"))
(check-equal "equal strings are non-strict only" '(#f #f #t #t)
  (list (c:chap:string<? "a.10" "a.10") (c:chap:string>? "a.10" "a.10")
        (c:chap:string<=? "a.10" "a.10") (c:chap:string>=? "a.10" "a.10")))
(check-equal "empty and prefix comparisons" '(#t #f #t)
  (list (c:chap:string<? "" "a") (c:chap:string<? "a" "") (c:chap:string<? "a" "a.1")))
(check-equal "reverse comparison agrees" '(#t #f) (list (c:chap:string>? "10" "9") (c:chap:string<=? "10" "9")))
(check-equal "numeric successors carry" '("10" "100" "a.10" "a.100")
  (map c:chap:next-string '("9" "99" "a.9" "a.99")))
(check-equal "alphabetic successors carry within their run" '("aa" "aaa" "AA" "4aa" "4AA")
  (map c:chap:next-string '("z" "zz" "Z" "4z" "4Z")))
(check-equal "successors preserve trailing punctuation" "Revised^{5}" (c:chap:next-string "Revised^{4}"))
(check-equal "strings without alphanumerics gain zero" '("0" "--0") (map c:chap:next-string '("" "--")))
(check-equal "successor leaves input unchanged" '("a.10" "a.9")
  (let ((s (string-copy "a.9"))) (list (c:chap:next-string s) s)))
(check-equal "successors remain strictly ordered through carries" #t
  (let loop ((s "a.8") (n 120))
    (or (zero? n) (let ((next (c:chap:next-string s)))
      (and (c:chap:string<? s next) (not (c:chap:string<? next s)) (loop next (- n 1)))))))
(smoke-finish)
