(import (scheme base) (scheme char) (prefix (slib alist) a:) (patina compat smoke))
(define (fresh) (list (cons 'a 1) (cons 'b 2) (cons 'c 3)))
(check-equal "association lookup returns the first matching pair" '(a . 1)
  ((a:predicate->asso eq?) 'a '((a . 1) (a . 2))))
(check-equal "structural keys and missing keys" '(((a b) . 3) #f #f)
  (let ((find (a:predicate->asso equal?)))
    (list (find (list 'a 'b) '(((a b) . 3))) (find 'x '((a . 1))) (find 'x '()))))
(check-equal "custom equality is used for lookup" '("One" . 1)
  ((a:predicate->asso string-ci=?) "ONE" '(("One" . 1) ("Two" . 2))))
(check-equal "numeric equality respects exact and inexact equivalents" '(1 . found)
  ((a:predicate->asso =) 1.0 '((1 . found))))
(check-equal "numeric inquirers use the supplied equality" 'found
  ((a:alist-inquirer =) '((1 . found)) 1.0))
(check-equal "numeric association replaces an equivalent key instead of inserting" '(1 new)
  (let ((result ((a:alist-associator =) (list (cons 1 'old)) 1.0 'new)))
    (list (length result) ((a:alist-inquirer =) result 1))))
(check-equal "inquirers return values, including false, or false for absence" '(1 #f #f)
  (let ((get (a:alist-inquirer eq?)))
    (list (get '((a . 1)) 'a) (get '((a . #f)) 'a) (get '((a . 1)) 'z))))
;; Associators and removers may mutate: always use their returned alist.
(check-equal "association inserts new keys and replaces existing values" '((b . 2) (a . 3))
  (let ((put (a:alist-associator eq?)))
    (put (put (put '() 'a 1) 'b 2) 'a 3)))
(check-equal "association replacement honors a custom predicate" '(1 9)
  (let* ((put (a:alist-associator string-ci=?))
         (result (put (put '() "Key" 1) "KEY" 9)))
    (list (length result) ((a:alist-inquirer string-ci=?) result "key"))))
(check-equal "removing head, middle, tail, missing and empty entries"
  '(((b . 2) (c . 3)) ((a . 1) (c . 3)) ((a . 1) (b . 2)) ((a . 1) (b . 2) (c . 3)) ())
  (let ((remove (a:alist-remover eq?)))
    (list (remove (fresh) 'a) (remove (fresh) 'b) (remove (fresh) 'c)
          (remove (fresh) 'z) (remove '() 'z))))
(check-equal "removal honors custom equality" '(("b" . 2))
  ((a:alist-remover string-ci=?) (list (cons "A" 1) (cons "b" 2)) "a"))
(check-equal "mapping receives keys and values and allocates new associations"
  '(((a a 1) (b b 2) (c c 3)) ((a . 1) (b . 2) (c . 3)) #f #f)
  (let* ((original (fresh)) (mapped (a:alist-map (lambda (k v) (list k v)) original)))
    (list mapped original (eq? original mapped) (eq? (car original) (car mapped)))))
(check-equal "iteration visits every key/value pair in order" '((a 1) (b 2) (c 3))
  (let ((seen '()))
    (a:alist-for-each (lambda (k v) (set! seen (cons (list k v) seen))) (fresh))
    (reverse seen)))
(check-equal "empty mapping and iteration do not call their callbacks" '(() 0)
  (let ((calls 0))
    (let ((f (lambda (k v) (set! calls (+ calls 1)) v)))
      (a:alist-for-each f '()) (list (a:alist-map f '()) calls))))
(smoke-finish)
