(import (scheme base) (prefix (slib scanf) s:) (patina compat smoke))
(define-syntax observed
  (syntax-rules () ((_ expr) (guard (ex (else 'unexpected-error)) expr))))
(check-equal "decimal fields preserve signs" '(12 -7 3) (s:scanf-read-list "%d %d %d" "12 -7 +3"))
(check-equal "octal and hexadecimal fields" '(63 255) (s:scanf-read-list "%o %x" "77 ff"))
(check-equal "radix-selecting integer fields" '(16 8 19) (s:scanf-read-list "%i %i %i" "0x10 010 19"))
(check-equal "a standalone radix-selecting zero is a number" '(0) (s:scanf-read-list "%i" "0"))
(check-equal "floating point fields include signed exponents" '(1.25 -250.0) (s:scanf-read-list "%f %e" "1.25 -2.5e2"))
(check-equal "field width bounds input consumption" '(12 345) (s:scanf-read-list "%2d%d" "12345"))
(check-equal "literal matching and percent escapes" '(7) (s:scanf-read-list "value=%d%%" "value=7%"))
(check-equal "suppressed fields consume without returning a value" '(9) (s:scanf-read-list "%*d %d" "8 9"))
(check-equal "string and character fields" '("word" "xy") (s:scanf-read-list "%s %2c" "word xy"))
(check-equal "character fields preserve whitespace" '(" a") (s:scanf-read-list "%2c" " a"))
(check-equal "ranges and inverted scan sets" '("abc" "123") (s:scanf-read-list "%[a-z]%[^x]" "abc123x"))
(check-equal "numeric fields require explicit format whitespace" '() (s:scanf-read-list "%d" "  12"))
(check-equal "string fields require explicit format whitespace" '() (s:scanf-read-list "%s" "  word"))
(check-equal "character counts include literal and format whitespace" '(7 4) (s:scanf-read-list " x%d%n" "  x7"))
(check-equal "a mismatch returns the fields already assigned" '(1) (s:scanf-read-list "%d,%d" "1;x"))
(check-equal "a mismatch leaves the next input character available" '(() #\x)
  (let ((p (open-input-string "x")))
    (let ((xs (s:scanf-read-list "%d" p))) (list xs (read-char p)))))
(check-equal "empty input returns EOF" #t (eof-object? (s:scanf-read-list "%d" "")))
(check-equal "value mode prefixes the number of values" '(2 12 "word")
  (call-with-values (lambda () (s:scanf-read-values "%d %s" "12 word")) list))
(check-error "unknown conversion directives are errors" (s:scanf-read-list "%q" "abc"))
(check-error "unclosed scan sets are errors" (s:scanf-read-list "%[ab" "abc"))
;; SLIB deliberately differs from C scanf: leading input whitespace is skipped
;; only when the format contains whitespace (SLIB Standard Formatted Input).
(check-equal "explicit whitespace permits leading spaces for numbers" '(12)
  (s:scanf-read-list " %d" "  12"))
(check-equal "explicit whitespace permits leading spaces for strings" '("word")
  (s:scanf-read-list " %s" "  word"))
(check-equal "signed and delimited zeros remain valid integer fields" '((0) (0) (0))
  (map (lambda (s) (s:scanf-read-list "%i" s)) '("-0" "+0" "0,")))
(check-equal "a one-character radix field leaves a following x unread" '(0 #\x)
  (observed (let ((p (open-input-string "0x10")))
    (let ((xs (s:scanf-read-list "%1i" p))) (list (car xs) (read-char p))))))
(smoke-finish)
