(import (scheme base) (prefix (slib queue) q:) (patina compat smoke))
(check-equal "fresh queues are empty and have a distinct type" '(#t #t #f)
  (let ((q (q:make-queue))) (list (q:queue? q) (q:queue-empty? q) (q:queue? '()))))
(check-equal "enqueue returns the queue and sets both ends" '(#t a a)
  (let ((q (q:make-queue)))
    (let ((same? (eq? q (q:enqueue! q 'a))))
      (list same? (q:queue-front q) (q:queue-rear q)))))
(check-equal "FIFO removal updates both ends and emptiness" '(a b c #t)
  (let ((q (q:make-queue)))
    (for-each (lambda (x) (q:enqueue! q x)) '(a b c))
    (let* ((a (q:dequeue! q)) (b (q:dequeue! q)) (c (q:dequeue! q)))
      (list a b c (q:queue-empty? q)))))
(check-equal "front pushes and pops implement a stack" '(c b a)
  (let ((q (q:make-queue)))
    (for-each (lambda (x) (q:queue-push! q x)) '(a b c))
    (let* ((c (q:queue-pop! q)) (b (q:queue-pop! q)) (a (q:queue-pop! q))) (list c b a))))
(check-equal "front and rear additions can be mixed" '(#t a d (a b c d) #t)
  (let ((q (q:make-queue)))
    (q:enqueue! q 'b) (q:enqueue! q 'c)
    (let ((same? (eq? q (q:queue-push! q 'a))))
      (q:enqueue! q 'd)
      (let* ((front (q:queue-front q)) (rear (q:queue-rear q)) (all (q:dequeue-all! q)))
        (list same? front rear all (q:queue-empty? q))))))
(check-equal "draining a queue permits reuse without altering the returned list" '((a b) c c (c))
  (let ((q (q:make-queue)))
    (q:enqueue! q 'a) (q:enqueue! q 'b)
    (let ((old (q:dequeue-all! q)))
      (q:queue-push! q 'c)
      (let* ((front (q:queue-front q)) (rear (q:queue-rear q)) (all (q:dequeue-all! q)))
        (list old front rear all)))))
(check-equal "removing a singleton clears the rear before reuse" '(b b)
  (let ((q (q:make-queue)))
    (q:queue-push! q 'a) (q:dequeue! q) (q:enqueue! q 'b)
    (list (q:queue-front q) (q:queue-rear q))))
(check-error "empty front access raises" (q:queue-front (q:make-queue)))
(check-error "empty rear access raises" (q:queue-rear (q:make-queue)))
(check-error "empty dequeue raises" (q:dequeue! (q:make-queue)))
(check-error "empty stack pop raises" (q:queue-pop! (q:make-queue)))
(smoke-finish)
