(import (scheme base) (prefix (slib soundex) s:) (patina compat smoke))
(check-equal "standard matching surnames" '("R163" "R163") (map s:soundex '("Robert" "Rupert")))
(check-equal "a distinct surname remains distinct" "R150" (s:soundex "Rubin"))
(check-equal "consonants are mapped to their numeric groups" "P236" (s:soundex "Pfister"))
(check-equal "adjacent equal consonant groups collapse" "T522" (s:soundex "Tymczak"))
(check-equal "vowels separate repeated groups in the original algorithm" "B110" (s:soundex "Babab"))
(check-equal "case is ignored" "R163" (s:soundex "rObErT"))
(check-equal "punctuation and digits are filtered" "R163" (s:soundex "R-o1bert!"))
(check-equal "short names are zero padded" '("A000" "B000") (map s:soundex '("A" "B")))
(check-equal "empty or nonalphabetic input yields an empty string" '("" "") (map s:soundex '("" "123-!?")))
(check-equal "long codes are truncated to four characters" "W252" (s:soundex "Washington"))
(smoke-finish)
