(import (scheme base) (prefix (srfi 63) a:) (prefix (slib subarray) s:)
        (patina compat smoke))
(define (observe thunk) (guard (ex (else 'unexpected-error)) (thunk)))
(define (grid) (a:list->array 2 '#() '((a b c) (d e f))))
(check-equal "selecting a row reduces the rank" '(1 (3) (d e f))
  (let ((row (s:subarray (grid) 1)))
    (list (a:array-rank row) (a:array-dimensions row) (a:array->list row))))
(check-equal "selecting a column fixes the second coordinate" '(b e)
  (a:array->list (s:subarray (grid) #f 1)))
(check-equal "range endpoints are inclusive" '((b c) (e f))
  (a:array->list (s:subarray (grid) #f '(1 2))))
(check-equal "descending ranges reflect an axis" '((c b) (f e))
  (a:array->list (s:subarray (grid) #f '(2 1))))
(check-equal "omitted selectors preserve the remaining dimensions" '((a b c) (d e f))
  (a:array->list (s:subarray (grid))))
(check-equal "fixing every coordinate produces a scalar view" '(0 () e)
  (let ((scalar (s:subarray (grid) 1 1)))
    (list (a:array-rank scalar) (a:array-dimensions scalar) (a:array-ref scalar))))
(check-equal "mutations propagate in both directions through a reflected view" '(x y)
  (let* ((source (grid)) (view (s:subarray source #f '(2 1))))
    (a:array-set! view 'x 0 0) (a:array-set! source 'y 1 1)
    (list (a:array-ref source 0 2) (a:array-ref view 1 1))))
(check-equal "nested subarrays compose their offsets" '(d e)
  (a:array->list (s:subarray (s:subarray (grid) 1) '(0 1))))
(check-equal "positive and negative trims remove opposite ends" '((1 2 3 4) (0 1 2 3))
  (list (a:array->list (s:array-trim '#(0 1 2 3 4) 1))
        (a:array->list (s:array-trim '#(0 1 2 3 4) -1))))
(check-equal "multidimensional trims preserve the untrimmed coordinates" '((d e))
  (a:array->list (s:array-trim (grid) 1 -1)))
(check-equal "a trimmed array shares its source" '(0 x 2)
  (let* ((source (vector 0 1 2)) (view (s:array-trim source 1)))
    (a:array-set! view 'x 0) (vector->list source)))
(check-equal "zero trims preserve an empty dimension" '(0)
  (observe (lambda () (a:array-dimensions (s:array-trim '#() 0)))))
(check-equal "trimming an entire axis produces an empty view" '((0) (0))
  (observe (lambda ()
    (list (a:array-dimensions (s:array-trim '#(1 2 3) 3))
          (a:array-dimensions (s:array-trim '#(1 2 3) -3))))))
(check-equal "omitted trims preserve an empty multidimensional shape" '(2 0 3)
  (a:array-dimensions (s:array-trim (a:make-array '#(0) 2 0 3))))
(check-equal "an empty trimmed view has no accessible element" #f
  (a:array-in-bounds? (s:array-trim '#(1 2 3) 3) 0))
(check-equal "trimming a scalar preserves its shared element" '(0 7)
  (let* ((source (a:make-array '#(0))) (view (s:array-trim source)))
    (a:array-set! view 7) (list (a:array-rank view) (a:array-ref source))))
(check-error "trims cannot remove more cells than an axis contains" (s:array-trim '#(1 2 3) 4))
(check-error "subarrays reject too many selectors" (s:subarray (grid) #f #f #f))
(check-error "trimming rejects too many dimensions" (s:array-trim '#(1 2) 0 0))
(smoke-finish)
