(import (scheme base) (prefix (slib uri) u:) (patina compat smoke))
(define-syntax observed
  (syntax-rules () ((_ expr) (guard (ex (else 'unexpected-error)) expr))))
(check-equal "URI components escape reserved ASCII bytes" "a%20b%2fc%25" (u:uric:encode "a b/c%"))
(check-equal "explicitly allowed separators remain literal" "a/b%20c" (u:uric:encode "a/b c" "/"))
(check-equal "percent decoding accepts both hex cases" "a b/c" (u:uric:decode "a%20b%2Fc"))
(check-equal "encoding and decoding round trip ASCII punctuation" "a b/?#%&=" (u:uric:decode (u:uric:encode "a b/?#%&=")))
(check-equal "empty URI components round trip" '("" "") (list (u:uric:encode "") (u:uric:decode "")))
(check-equal "URI construction accepts all five components" "http://example.test/a%20b?q=1#part"
  (u:make-uri 'http "example.test" "/a b" "q=1" "part"))
(check-equal "URI construction with a host-only authority tuple" "http://example.test/x"
  (u:make-uri 'http '(#f "example.test" #f) "/x" #f #f))
(check-equal "URI construction supports userinfo and ports" "ftp://user@example.test:21/x"
  (u:make-uri 'ftp '("user" "example.test" 21) "/x" #f #f))
(check-equal "URI shorthand constructs fragments and empty references" '("#part" "")
  (list (u:make-uri "part") (u:make-uri)))
(check-equal "paths retain empty components and encode spaces" "/a%20b/" (u:uri:make-path '("" "a b" "")))
(check-equal "URI parser separates all components" '(http "example.test" ("" "a b") "q=1" "part")
  (observed (u:uri->tree "http://example.test/a%20b?q=1#part")))
(check-equal "authority parsing accepts userinfo without a port" '(ftp ("user" "example.test" #f) ("" "x") #f #f)
  (observed (u:uri->tree "ftp://user@example.test/x")))
(check-equal "relative URI resolution handles parent segments" '(http "example.test" ("" "c") #f #f)
  (observed (u:uri->tree "../c" '(http "example.test" ("" "a" "b") #f #f))))
(check-equal "fragment references retain the base path and query" '(http "example.test" ("" "a") "q=1" "new")
  (observed (u:uri->tree "#new" '(http "example.test" ("" "a") "q=1" "old"))))
(check-equal "field splitting retains empty components" '("" "a" "" "b" "") (u:uri:split-fields "/a//b/" #\/))
(check-equal "query decoding normalizes names and decodes plus" '((city "New York") (name "A B"))
  (u:uri:decode-query "Name=A+B&City=New%20York"))
(check-equal "typed path keys use coercion" '(12 item) (u:uri:path->keys '("12" "item") '(number symbol)))
(check-equal "path key arity mismatches return false" #f (u:uri:path->keys '("12") '(number symbol)))
(check-equal "absolute URI and path predicates" '(#t #f #t #f)
  (list (u:absolute-uri? "http://example.test/x") (u:absolute-uri? "relative/path")
        (and (u:absolute-path? "/x") #t) (u:absolute-path? "x")))
(check-equal "glob and null directory predicates" '(#t #f #t #f)
  (list (u:glob-pattern? "a[bc]") (u:glob-pattern? "abc") (and (u:null-directory? "./") #t) (u:null-directory? "sub")))
(check-equal "absolute file URI conversion" "file:/tmp/a" (u:path->uri "/tmp/a"))
(check-equal "HTML helpers preserve their documented spelling" '("<A NAME=\"(section%207)\"></A>" "<A HREF=\"#x\">text</A>" "<BASE HREF=\"/root/\">" "<ISINDEX PROMPT=\"Find\">")
  (list (u:html:anchor "(section 7)") (u:html:link "#x" "text") (u:html:base "/root/") (u:html:isindex "Find")))
(check-equal "FTP URL parsing extracts credentials and path" '("user" "pass" "example.test" "dir/file")
  (u:parse-ftp-address "ftp://user:pass@example.test/dir/file"))
(check-equal "missing FTP address is false" #f (u:parse-ftp-address #f))
(smoke-finish)
