(import (scheme base) (prefix (slib xml-parse) x:) (patina compat smoke))
(define (parse text) (x:ssax:xml->sxml (open-input-string text) '()))
(check-equal "empty elements become SXML nodes" '(*TOP* (root)) (parse "<root/>"))
(check-equal "nested content and attributes survive parsing" '(*TOP* (root (@ (id "x")) (child "text"))) (parse "<root id='x'><child>text</child></root>"))
(check-equal "named and numeric character references are decoded" '(*TOP* (r "<&AA")) (parse "<r>&lt;&amp;&#65;&#x41;</r>"))
(check-equal "CDATA text is not parsed as markup" '(*TOP* (r "a<b&c")) (parse "<r><![CDATA[a<b&c]]></r>"))
(check-equal "comments do not become element content" '(*TOP* (r "ab")) (parse "<r>a<!--hidden-->b</r>"))
(check-equal "insignificant whitespace between elements is dropped" '(*TOP* (r (a) (b))) (parse "<r> \n<a/> \n<b/> </r>"))
(check-equal "default namespaces qualify elements" '(*TOP* (urn:test:r (urn:test:c))) (parse "<r xmlns='urn:test'><c/></r>"))
(check-equal "unprefixed attributes remain outside the default namespace" '(*TOP* (urn:test:r (@ (id "x")))) (parse "<r xmlns='urn:test' id='x'/>"))
(check-equal "QName reader splits prefix and local name" '(ns . item) (x:ssax:read-QName (open-input-string "ns:item ")))
(check-equal "NCName reader leaves its delimiter unread" '(some-name #\:) (let* ((in (open-input-string "some-name:")) (name (x:ssax:read-NCName in))) (list name (peek-char in))))
(check-equal "fragment collection merges adjacent strings" '("ab" (x) "c") (x:ssax:reverse-collect-str '("c" (x) "b" "a")))
(check-equal "attribute insertion preserves sorted order" '((a . "1") (b . "2") (c . "3")) (x:attlist-add '((a . "1") (c . "3")) '(b . "2")))
(check-equal "duplicate attribute insertion returns false" #f (x:attlist-add '((a . "1") (b . "2")) '(b . "3")))
(check-equal "removing an attribute returns the entry and remainder" '((a . "1") ((b . "2"))) (call-with-values (lambda () (x:attlist-remove-top '((a . "1") (b . "2")))) list))
(check-error "mismatched closing tags are rejected" (parse "<a></b>"))
(check-error "duplicate attributes are rejected" (parse "<r a='1' a='2'/>"))
(check-error "unbound namespace prefixes are rejected" (parse "<p:r/>"))
(check-error "unknown entities are rejected" (parse "<r>&unknown;</r>"))
(smoke-finish)
