(import (scheme base) (prefix (slib math-integer) i:) (patina compat smoke))
(define (observe thunk) (guard (ex (else 'unexpected-error)) (thunk)))
(check-equal "integer powers preserve signs and the zero exponent" '(1024 -27 1 0)
  (list (i:integer-expt 2 10) (i:integer-expt -3 3)
        (i:integer-expt 0 0) (i:integer-expt 0 4)))
(check-equal "negative powers of units are still exact integers" '(1 -1 1)
  (observe (lambda ()
    (list (i:integer-expt 1 -3) (i:integer-expt -1 -3) (i:integer-expt -1 -2)))))
(check-error "nonintegral powers are rejected" (i:integer-expt 2 -1))
(check-error "inexact power operands are rejected" (i:integer-expt 2.0 3))
(check-error "zero cannot be raised to a negative power" (i:integer-expt 0 -1))
(check-equal "integer logarithms bracket exact powers" '(0 9 10 10 3)
  (list (i:integer-log 2 1) (i:integer-log 2 1023) (i:integer-log 2 1024)
        (i:integer-log 2 1025) (i:integer-log 10 9999)))
(check-error "logarithm bases must exceed one" (i:integer-log 1 10))
(check-error "integer logarithms reject zero" (i:integer-log 2 0))
(check-equal "integer square roots bracket squares and table boundaries" '(0 1 4 5 5 9 10)
  (map i:integer-sqrt '(0 1 24 25 26 99 100)))
(check-equal "square roots and logarithms support bignums" '(12345678901234567890 120)
  (list (i:integer-sqrt 152415787532388367501905199875019052100)
        (i:integer-log 2 (expt 2 120))))
(check-error "integer square roots reject negatives" (i:integer-sqrt -1))
(check-error "integer square roots reject inexact integers" (i:integer-sqrt 4.0))
(check-equal "quotient, remainder and modulo retain their sign conventions"
  '((-2 -1 2) (-2 1 -2) (2 -1 -1))
  (map (lambda (args)
         (list (apply i:quotient args) (apply i:remainder args) (apply i:modulo args)))
       '((-7 3) (7 -3) (-7 -3))))
(check-error "exact quotient rejects inexact operands" (i:quotient 7.0 3))
(check-error "exact remainder rejects rational operands" (i:remainder 7/2 3))
(check-error "exact modulo rejects a zero divisor" (i:modulo 7 0))
(check-equal "rounded quotients choose even ties for every sign" '(2 2 -2 -2 -2 -2 2 2)
  (map (lambda (args) (apply i:round-quotient args))
       '((3 2) (5 2) (-3 2) (-5 2) (3 -2) (5 -2) (-3 -2) (-5 -2))))
(check-equal "rounded quotients choose the nearest integer away from ties" '(2 3 -2 -3)
  (map (lambda (n) (i:round-quotient n 3)) '(7 8 -7 -8)))
(smoke-finish)
