(import (scheme base) (prefix (slib byte) b:) (patina compat smoke))
(define-syntax observed
  (syntax-rules () ((_ expr) (guard (ex (else 'unexpected-error)) expr))))
(check-equal "constructors retain byte values and lengths" '(0 128 255)
  (b:bytes->list (b:bytes 0 128 255)))
(check-equal "filled byte arrays" '(7 7 7) (b:bytes->list (b:make-bytes 3 7)))
(check-equal "empty byte constructors" '(0 () "")
  (observed (list (b:bytes-length (b:bytes)) (b:bytes->list (b:make-bytes 0))
        (b:bytes->string (b:bytes)))))
(check-equal "list conversion copies its input" '(1 2 3)
  (let* ((xs (list 1 2 3)) (bs (b:list->bytes xs)))
    (set-car! xs 9) (b:bytes->list bs)))
(check-equal "byte setters update only the selected cell" '(1 255 3)
  (let ((bs (b:bytes 1 2 3))) (b:byte-set! bs 1 255) (b:bytes->list bs)))
(check-equal "ASCII string round trip" "A\nZ"
  (b:bytes->string (b:string->bytes "A\nZ")))
(check-equal "copying retains data and separates storage" '((9 2 3) (1 2 3))
  (observed (let* ((bs (b:bytes 1 2 3)) (copy (b:bytes-copy bs)))
    (b:byte-set! copy 0 9) (list (b:bytes->list copy) (b:bytes->list bs)))))
(check-equal "empty byte copying" '() (observed (b:bytes->list (b:bytes-copy (b:bytes)))))
(check-equal "slices use an exclusive end and copy storage" '((8 3) (1 2 3 4) ())
  (let* ((bs (b:bytes 1 2 3 4)) (slice (b:subbytes bs 1 3)))
    (b:byte-set! slice 0 8)
    (list (b:bytes->list slice) (b:bytes->list bs) (b:bytes->list (b:subbytes bs 2 2)))))
(check-equal "destructive reversal preserves the array identity" '(#t (4 3 2 1))
  (let ((bs (b:bytes 1 2 3 4)))
    (let ((answer (b:bytes-reverse! bs))) (list (eq? answer bs) (b:bytes->list bs)))))
(check-equal "copying reversal leaves the original intact" '((3 2 1) (1 2 3))
  (observed (let ((bs (b:bytes 1 2 3)))
    (list (b:bytes->list (b:bytes-reverse bs)) (b:bytes->list bs)))))
(check-equal "singleton and empty reversal" '((7) ())
  (observed (map (lambda (xs) (b:bytes->list (b:bytes-reverse! (b:list->bytes xs)))) '((7) ()))))
;; The pinned adapter implements byte I/O with character ports. Exercise ASCII
;; string ports here; this does not claim binary-port or non-ASCII fidelity.
(check-equal "single byte reading and EOF" '(65 #t)
  (let ((p (open-input-string "A")))
    (let ((first (b:read-byte p))) (list first (eof-object? (b:read-byte p))))))
(check-equal "single byte writing" "AZ"
  (let ((p (open-output-string))) (b:write-byte 65 p) (b:write-byte 90 p) (get-output-string p)))
(check-equal "big-endian reads stop at EOF" '(65 66) (b:bytes->list (b:read-bytes 5 (open-input-string "AB"))))
(check-equal "empty reads consume no input" '(() #\A)
  (let ((p (open-input-string "A")))
    (let ((bs (b:read-bytes 0 p))) (list (b:bytes->list bs) (read-char p)))))
(check-equal "little-endian reads reverse complete input" '(67 66 65)
  (b:bytes->list (b:read-bytes -3 (open-input-string "ABC"))))
(check-equal "writing counts and forward/reverse slices" '(2 2 "BCDC")
  (let ((p (open-output-string)) (bs (b:string->bytes "ABCD")))
    (let* ((forward (b:subbytes-write bs 1 3 p)) (reverse (b:subbytes-write bs 4 2 p)))
      (list forward reverse (get-output-string p)))))
(check-equal "signed write counts select byte order" "ABBA"
  (let ((p (open-output-string)) (bs (b:string->bytes "AB")))
    (b:write-bytes bs 2 p) (b:write-bytes bs -2 p) (get-output-string p)))
(check-equal "offset reads return a count and preserve other cells" '(2 (9 65 66 9))
  (let ((bs (b:make-bytes 4 9)))
    (let ((n (b:subbytes-read! bs 1 3 (open-input-string "AB")))) (list n (b:bytes->list bs)))))
(check-equal "empty offset reads return zero" 0
  (b:subbytes-read! (b:make-bytes 4 9) 2 2 (open-input-string "A")))
(check-equal "short offset reads report consumed bytes" '(1 (9 9 65 9))
  (let ((bs (b:make-bytes 4 9)))
    (let ((n (b:subbytes-read! bs 2 4 (open-input-string "A")))) (list n (b:bytes->list bs)))))
(check-equal "reverse reads terminate at EOF and retain only available bytes" '(66 65)
  (b:bytes->list (b:read-bytes -5 (open-input-string "AB"))))
(check-equal "reverse reads of empty input return empty bytes" '()
  (b:bytes->list (b:read-bytes -3 (open-input-string ""))))
(check-equal "short reverse slices report counts and preserve surrounding bytes" '(2 (9 9 66 65 9))
  (let ((bs (b:make-bytes 5 9)))
    (let ((n (b:subbytes-read! bs 4 1 (open-input-string "AB"))))
      (list n (b:bytes->list bs)))))
(smoke-finish)
