(import (scheme base) (slib string-search) (patina compat smoke))
(check-equal "forward and reverse character searches" '(1 0 3 4)
  (list (string-index "aBaBa" #\B) (string-index-ci "aBaBa" #\A)
        (string-reverse-index "aBaBa" #\B)
        (string-reverse-index-ci "aBaBa" #\A)))
(check-equal "substring match after partial matches" 8
  (substring? "needle" "needlingneedle"))
(check-equal "case-insensitive substring" 2 (substring-ci? "AbC" "xxaBc!"))
(check-equal "absent and empty patterns" '(#f 0)
  (list (substring? "missing" "text") (substring? "" "text")))
(define overlap (open-input-string "xxabababac!"))
(define consumed (find-string-from-port? "ababac" overlap))
(check-equal "port search backtracks and stops after the match" '(10 #\!)
  (list consumed (read-char overlap)))
(define limited (open-input-string "xxneedle"))
(define found (find-string-from-port? "needle" limited 3))
(check-equal "bounded search leaves the next character unread" '(#f #\e)
  (list found (read-char limited)))
(define delimited (open-input-string "one|two"))
(define past-delimiter (find-string-from-port? "two" delimited #\|))
(check-equal "delimiter stops search without consuming the delimiter" '(#f #\|)
  (list past-delimiter (read-char delimited)))
(check-equal "multiple substitutions" "green gold green"
  (string-subst "red blue red" "red" "green" "blue" "gold"))
(check-equal "newline counting" 2 (count-newlines "one\ntwo\nthree"))
(smoke-finish)
