(import (scheme base) (prefix (srfi 63) a:) (prefix (slib determinant) m:)
        (patina compat smoke))
(define (observe thunk) (guard (ex (else 'unexpected-error)) (thunk)))
(define square '((1 2) (3 4)))
(check-equal "matrix conversion preserves rectangular rows" '((1 2 3) (4 5 6))
  (m:matrix->lists (m:matrix->array '((1 2 3) (4 5 6)))))
(check-equal "an existing rank-two array is reused by conversion" #t
  (let ((array (m:matrix->array square))) (eq? array (m:matrix->array array))))
(check-equal "singleton and two-by-two determinants are exact" '(7 -2)
  (list (m:determinant '((7))) (m:determinant square)))
(check-equal "three-by-three determinant includes cofactor signs" -306
  (m:determinant '((6 1 1) (4 -2 5) (2 8 7))))
(check-equal "linearly dependent rows give a zero determinant" 0
  (m:determinant '((1 2 3) (4 5 6) (7 8 9))))
(check-equal "transposition swaps rectangular dimensions" '((1 4) (2 5) (3 6))
  (m:transpose '((1 2 3) (4 5 6))))
(check-equal "array transposition returns a separate array" '((3 2) ((x 3) (1 4) (2 5)) ((0 1 2) (3 4 5)))
  (let* ((source (m:matrix->array '((0 1 2) (3 4 5)))) (result (m:transpose source)))
    (a:array-set! result 'x 0 0)
    (list (a:array-dimensions result) (m:matrix->lists result) (m:matrix->lists source))))
(check-equal "matrix addition and subtraction operate elementwise" '(((6 8) (10 12)) ((-4 -4) (-4 -4)))
  (list (m:matrix:sum square '((5 6) (7 8))) (m:matrix:difference square '((5 6) (7 8)))))
(check-equal "rectangular products contract the shared dimension" '((58 64) (139 154))
  (m:matrix:product '((1 2 3) (4 5 6)) '((7 8) (9 10) (11 12))))
(check-equal "scalar multiplication works on either side" '(((2 4) (6 8)) ((2 4) (6 8)))
  (list (m:matrix:product 2 square) (m:matrix:product square 2)))
(check-equal "matrix inverse retains exact rational entries" '((-2 1) (3/2 -1/2))
  (m:matrix:inverse square))
(check-equal "inverse multiplication yields the identity" '((1 0) (0 1))
  (m:matrix:product square (m:matrix:inverse square)))
(check-equal "array inverses preserve the array representation" '(2 ((-2 1) (3/2 -1/2)))
  (let ((inverse (m:matrix:inverse (m:matrix->array square))))
    (list (a:array-rank inverse) (m:matrix->lists inverse))))
(check-equal "singular matrices have no inverse" #f (m:matrix:inverse '((1 2) (2 4))))
(check-equal "a singleton matrix has a reciprocal inverse" '((1/7))
  (observe (lambda () (m:matrix:inverse '((7))))))
(check-equal "singleton array inverses preserve shape and exactness" '((1 1) ((1/7)))
  (observe (lambda ()
    (let ((inverse (m:matrix:inverse (m:matrix->array '((7))))))
      (list (a:array-dimensions inverse) (m:matrix->lists inverse))))))
(check-error "matrix conversion rejects nonmatrices" (m:matrix->lists 'not-a-matrix))
(smoke-finish)
