(import (scheme base) (scheme char) (prefix (slib tree) t:) (patina compat smoke))
(check-equal "substitution replaces nested leaves and dotted tails" '(x (b x) . x)
  (t:subst 'x 'a '(a (b a) . a)))
(check-equal "substitution matches a whole subtree before descending" '(x x)
  (t:subst 'x '(a b) '((a b) (a b))))
(check-equal "substitution preserves its input tree" '((x (x)) (a (a)))
  (let ((original (list 'a (list 'a))))
    (list (t:subst 'x 'a original) original)))
(check-equal "a custom predicate can compare string leaves" '(x (x "b"))
  (t:subst 'x "a" '("A" ("a" "b"))
    (lambda (old item) (and (string? item) (string-ci=? old item)))))
(check-equal "substq uses identity for compound keys" '(#t #t)
  (let* ((key (list 'a)) (other (list 'a)) (result (t:substq 'x key (list key other))))
    (list (eq? (car result) 'x) (equal? (car (cdr result)) other))))
(check-equal "substv replaces numeric leaves" '(x (2 x) . x)
  (t:substv 'x 1 '(1 (2 1) . 1)))
(check-equal "replacing empty tails can produce dotted trees" '(a (b . end) . end)
  (t:substq 'end '() '(a (b))))
(check-equal "tree copies preserve nested and dotted structure" '(a (b . c) . d)
  (t:copy-tree '(a (b . c) . d)))
(check-equal "copies allocate every pair but preserve non-pair leaves" '(#f #f #f #t)
  (let* ((leaf (vector 'v)) (original (list (list 'a) leaf)) (copy (t:copy-tree original)))
    (list (eq? original copy) (eq? (car original) (car copy))
          (eq? (cdr original) (cdr copy)) (eq? leaf (car (cdr copy))))))
(check-equal "mutating a copied nested pair leaves the original unchanged" '((a) (x))
  (let* ((original (list (list 'a))) (copy (t:copy-tree original)))
    (set-car! (car copy) 'x) (list (car original) (car copy))))
(check-equal "empty trees and atomic leaves copy directly" '(() a 7)
  (map t:copy-tree '(() a 7)))
(smoke-finish)
