(import (scheme base) (prefix (slib rationalize) r:) (patina compat smoke))
(check-equal "a narrow tolerance retains the original ratio" '(3 97) (r:find-ratio 3/97 1/10000))
(check-equal "a wider tolerance permits a simpler ratio" '(1 32) (r:find-ratio 3/97 1/1000))
(check-equal "a positive interval chooses its simplest ratio" '(1 2) (r:find-ratio-between 2/7 3/5))
(check-equal "negative intervals reflect the numerator sign" '(-1 2) (r:find-ratio-between -3/5 -2/7))
(check-equal "reversed bounds describe the same interval" '(1 2) (r:find-ratio-between 3/5 2/7))
(check-equal "an interval spanning zero chooses zero" '(0 1) (r:find-ratio-between -1/10 1/5))
(check-equal "an included integer is simpler than a fraction" '(2 1) (r:find-ratio-between 3/2 5/2))
(check-equal "zero tolerance preserves the represented value" #t
  (let ((ratio (r:find-ratio 3/7 0))) (= 3/7 (/ (car ratio) (cadr ratio)))))
(check-equal "singleton rational intervals return integer numerators and denominators"
  '((3 7) (-3 7))
  (list (r:find-ratio 3/7 0) (r:find-ratio-between -3/7 -3/7)))
(check-equal "integer singleton intervals are exact" '(4 1) (r:find-ratio-between 4 4))
(check-equal "inexact interval endpoints still produce integer ratios" '(1 3)
  (r:find-ratio-between 0.32 0.34))
(check-equal "negative target tolerances retain the expected ratio" '(-1 32)
  (r:find-ratio -3/97 1/1000))
(smoke-finish)
