(import (scheme base) (prefix (slib tzfile) z:)
        (patina compat time-fixtures) (patina compat smoke))
(define-syntax observed
  (syntax-rules () ((_ expr) (guard (ex (else 'unexpected-error)) expr))))
(define (read-fixture attributes?)
  (call-with-tzif attributes? z:tzfile:read))
(check-equal "reader returns its path and the five documented components" '(#t 5)
  (call-with-tzif #f (lambda (path)
    (let ((result (z:tzfile:read path))) (list (string=? path (car result)) (length result))))))
(check-equal "signed big-endian transition seconds survive binary reads" '#(-1 100 200)
  (list-ref (read-fixture #f) 3))
(check-equal "transition type indices preserve their order" '#(1 0 1)
  (list-ref (read-fixture #f) 4))
(check-equal "UTC offsets decode as signed seconds east" '(-18000 -14400)
  (let ((modes (list-ref (read-fixture #f) 1)))
    (list (vector-ref (vector-ref modes 0) 1) (vector-ref (vector-ref modes 1) 1))))
(check-equal "daylight flags decode as booleans" '(#f #t)
  (let ((modes (list-ref (read-fixture #f) 1)))
    (list (vector-ref (vector-ref modes 0) 2) (vector-ref (vector-ref modes 1) 2))))
(check-equal "abbreviations are strings even without optional attributes" '("STD" "DST")
  (map (lambda (mode) (vector-ref mode 0)) (vector->list (list-ref (read-fixture #f) 1))))
(check-equal "leap second pairs retain time and correction" '#(1000 1)
  (list-ref (read-fixture #f) 2))
(check-equal "omitted transition attributes default to false" '((#f #f) (#f #f))
  (map (lambda (mode) (list (vector-ref mode 3) (vector-ref mode 4)))
       (vector->list (list-ref (read-fixture #f) 1))))
(check-equal "present attributes are associated with the correct mode" '((#t #f) (#f #t))
  (map (lambda (mode) (list (vector-ref mode 3) (vector-ref mode 4)))
       (vector->list (list-ref (read-fixture #t) 1))))
(check-equal "abbreviations are decoded when attributes are present too" '("STD" "DST")
  (map (lambda (mode) (vector-ref mode 0)) (vector->list (list-ref (read-fixture #t) 1))))
(check-error "truncated headers raise instead of yielding a timezone"
  (call-with-binary-fixture #u8(84 90 105 102) z:tzfile:read))
(check-error "missing files raise instead of yielding a timezone"
  (let ((path (call-with-binary-fixture #u8() (lambda (path) path)))) (z:tzfile:read path)))
(smoke-finish)
