(import (scheme base) (prefix (slib modular) m:) (patina compat smoke))
(define (bezout? a b)
  (let ((answer (m:extended-euclid a b)))
    (and (= (car answer) (gcd a b))
         (= (car answer) (+ (* a (cadr answer)) (* b (car (cddr answer))))))))
(check-equal "extended Euclid returns a gcd and valid coefficients" #t (bezout? 240 46))
(check-equal "extended Euclid handles signed and zero operands" #t
  (and (bezout? -7 3) (bezout? 7 -3) (bezout? -7 -3) (bezout? 0 7) (bezout? 7 0)))
(define symmetric (m:symmetric:modulus 7))
(check-equal "characteristics describe positive, symmetric and integer rings" '(7 7 #f)
  (map m:modular:characteristic (list 7 symmetric 0)))
(check-error "symmetric modulus rejects even characteristics" (m:symmetric:modulus 8))
(check-error "symmetric modulus rejects nonpositive characteristics" (m:symmetric:modulus 0))
(check-equal "ordinary residues are nonnegative" '(6 0 1 6)
  (map (lambda (n) (m:modular:normalize 7 n)) '(-8 0 8 20)))
(check-equal "symmetric residues are centered around zero" '(-1 0 1 -1)
  (map (lambda (n) (m:modular:normalize symmetric n)) '(-8 0 8 20)))
(check-equal "modulus zero leaves integers unchanged" -123 (m:modular:normalize 0 -123))
(check-equal "invertibility distinguishes units and nonunits" '(#t #f #t #f)
  (list (m:modular:invertable? 7 3) (m:modular:invertable? 8 2)
        (m:modular:invertable? 0 -1) (m:modular:invertable? 0 2)))
(check-equal "inverses use the selected representation" '(5 -2 -1)
  (list (m:modular:invert 7 3) (m:modular:invert symmetric 3) (m:modular:invert 0 -1)))
(check-error "nonunits cannot be inverted" (m:modular:invert 8 2))
(check-equal "modular arithmetic on normalized residues" '(4 5 2 1)
  (list (m:modular:negate 7 3) (m:modular:+ 7 6 6)
        (m:modular:- 7 1 6) (m:modular:* 7 3 5)))
(check-equal "symmetric arithmetic preserves centered results" '(-3 -1 1 -2)
  (list (m:modular:negate symmetric 3) (m:modular:+ symmetric 3 3)
        (m:modular:- symmetric -3 3) (m:modular:* symmetric -3 3)))
(check-equal "modular powers support positive, zero and negative exponents" '(4 1 5)
  (list (m:modular:expt 7 3 4) (m:modular:expt 7 3 0) (m:modular:expt 7 3 -1)))
(check-equal "zero to the zero power uses the ring's multiplicative identity" '(1 0 1)
  (list (m:modular:expt 7 0 0) (m:modular:expt 1 0 0) (m:modular:expt symmetric 0 0)))
(check-equal "zero modulus arithmetic matches integer arithmetic" '(-3 7 -1 12 16)
  (list (m:modular:negate 0 3) (m:modular:+ 0 3 4) (m:modular:- 0 3 4)
        (m:modular:* 0 3 4) (m:modular:expt 0 2 4)))
;; Every pair in the symmetric ring is checked against ordinary integer arithmetic.
(check-equal "symmetric addition and multiplication obey the ring laws" #t
  (let loop ((a -3) (b -3))
    (cond ((> a 3) #t) ((> b 3) (loop (+ a 1) -3))
          (else (and (= (modulo (m:modular:+ symmetric a b) 7) (modulo (+ a b) 7))
                     (= (modulo (m:modular:* symmetric a b) 7) (modulo (* a b) 7))
                     (loop a (+ b 1)))))))
(smoke-finish)
