(import (scheme base) (scheme inexact) (prefix (slib byte) b:) (prefix (slib byte-number) n:) (patina compat smoke))
(define-syntax observed
  (syntax-rules () ((_ expr) (guard (ex (else 'unexpected-error)) expr))))
(check-equal "unsigned integer encoding uses big-endian bytes" '(18 52 86 120)
  (b:bytes->list (n:integer->bytes #x12345678 4)))
(check-equal "signed and unsigned decoding share the stored bytes" '(-1 4294967295)
  (let ((bs (b:bytes 255 255 255 255)))
    (list (n:bytes->integer bs -4) (n:bytes->integer bs 4))))
(check-equal "signed integer boundary round trips" '(-32768 -1 0 1 32767)
  (map (lambda (x) (n:bytes->integer (n:integer->bytes x -2) -2)) '(-32768 -1 0 1 32767)))
(check-equal "large unsigned integers remain exact" 18446744073709551615
  (n:bytes->integer (n:integer->bytes 18446744073709551615 8) 8))
(check-equal "zero-width integer conversions" '(() 0)
  (list (b:bytes->list (n:integer->bytes 0 0)) (n:bytes->integer (b:make-bytes 0) 0)))
(check-equal "integer decoding honors its requested prefix" 258 (n:bytes->integer (b:bytes 1 2 3) 2))
(check-equal "single-precision known encodings" '((64 208 0 0) (192 208 0 0))
  (map (lambda (x) (b:bytes->list (n:ieee-float->bytes x))) '(6.5 -6.5)))
(check-equal "double-precision known encodings" '((64 26 0 0 0 0 0 0) (192 26 0 0 0 0 0 0))
  (map (lambda (x) (b:bytes->list (n:ieee-double->bytes x))) '(6.5 -6.5)))
(check-equal "single-precision decode and round trips" #t
  (let loop ((xs '(0.0 0.5 1.0 -6.5 1024.0)))
    (or (null? xs) (and (= (car xs) (n:bytes->ieee-float (n:ieee-float->bytes (car xs)))) (loop (cdr xs))))))
(check-equal "double-precision decode and round trips" #t
  (let loop ((xs '(0.0 0.5 1.0 -6.5 1024.0)))
    (or (null? xs) (and (= (car xs) (n:bytes->ieee-double (n:ieee-double->bytes (car xs)))) (loop (cdr xs))))))
(check-equal "single subnormal encoding and decoding" #t
  (let ((bs (b:bytes 0 0 0 1)))
    (and (= (n:bytes->ieee-float bs) (expt 2.0 -149))
         (equal? '(0 0 0 1) (b:bytes->list (n:ieee-float->bytes (expt 2.0 -149)))))))
(check-equal "double subnormal encoding and decoding" #t
  (let ((bs (b:bytes 0 0 0 0 0 0 0 1)))
    (and (= (n:bytes->ieee-double bs) (expt 2.0 -1074))
         (equal? '(0 0 0 0 0 0 0 1) (b:bytes->list (n:ieee-double->bytes (expt 2.0 -1074)))))))
(check-equal "single infinities have zero mantissas" '((127 128 0 0) (255 128 0 0))
  (map (lambda (x) (b:bytes->list (n:ieee-float->bytes x))) (list +inf.0 -inf.0)))
(check-equal "double infinities have zero mantissas" '((127 240 0 0 0 0 0 0) (255 240 0 0 0 0 0 0))
  (map (lambda (x) (b:bytes->list (n:ieee-double->bytes x))) (list +inf.0 -inf.0)))
(check-equal "infinity decoders preserve sign" '(#t #t #t #t)
  (list (= +inf.0 (n:bytes->ieee-float (b:bytes 127 128 0 0)))
        (= -inf.0 (n:bytes->ieee-float (b:bytes 255 128 0 0)))
        (= +inf.0 (n:bytes->ieee-double (b:bytes 127 240 0 0 0 0 0 0)))
        (= -inf.0 (n:bytes->ieee-double (b:bytes 255 240 0 0 0 0 0 0)))))
(check-equal "NaN encodings decode as NaN" '(#t #t)
  (list (nan? (n:bytes->ieee-float (n:ieee-float->bytes +nan.0)))
        (nan? (n:bytes->ieee-double (n:ieee-double->bytes +nan.0)))))
(check-equal "signed zeros retain their sign bits" '((128 0 0 0) (128 0 0 0 0 0 0 0))
  (list (b:bytes->list (n:ieee-float->bytes -0.0)) (b:bytes->list (n:ieee-double->bytes -0.0))))
(check-equal "destructive integer collation is its own inverse" '(#t (128 1) (0 1))
  (let* ((bs (b:bytes 0 1)) (same (eq? bs (n:integer-byte-collate! bs))) (once (b:bytes->list bs)))
    (n:integer-byte-collate! bs) (list same once (b:bytes->list bs))))
(check-equal "copying integer collation preserves its source" '((128 1) (0 1))
  (observed (let ((bs (b:bytes 0 1)))
    (list (b:bytes->list (n:integer-byte-collate bs)) (b:bytes->list bs)))))
(check-equal "destructive IEEE collation and inversion" '((63 229 255 255 255 255 255 255) (192 26 0 0 0 0 0 0))
  (let* ((bs (n:ieee-double->bytes -6.5)) (once (b:bytes->list (n:ieee-byte-collate! bs))))
    (n:ieee-byte-decollate! bs) (list once (b:bytes->list bs))))
(check-equal "copying IEEE collation round trips without mutation" '((192 26 0 0 0 0 0 0) (192 26 0 0 0 0 0 0))
  (observed (let* ((bs (n:ieee-double->bytes -6.5)) (key (n:ieee-byte-collate bs)))
    (list (b:bytes->list (n:ieee-byte-decollate key)) (b:bytes->list bs)))))
(check-error "single decoding rejects incorrect byte lengths" (n:bytes->ieee-float (b:make-bytes 5 0)))
(check-error "double decoding rejects incorrect byte lengths" (n:bytes->ieee-double (b:make-bytes 7 0)))
(smoke-finish)
