(import (scheme base) (prefix (srfi 63) a:) (prefix (slib coerce) c:) (patina compat smoke))
(define-syntax observed
  (syntax-rules () ((_ expr) (guard (ex (else 'unexpected-error)) expr))))
(check-equal "type tags cover basic values" '(boolean char number string symbol list pair vector procedure)
  (map c:type-of (list #f #\a 3/4 "s" 's '() '(a . b) '#(a) car)))
(check-equal "array, port and EOF tags" '(array port eof-object)
  (list (c:type-of (a:make-array '#() 2 2)) (c:type-of (open-input-string "")) (c:type-of (eof-object))))
(check-equal "identity coercion preserves mutable objects" #t
  (let ((s (string #\a))) (eq? s (c:coerce s 'string))))
(check-equal "character coercions" '(65 "A" A (#\A) #(#\A))
  (map (lambda (kind) (c:coerce #\A kind)) '(number string symbol list vector)))
(check-equal "number coercions" '(#\A "65" |65| (#\6 #\5) #(#\6 #\5))
  (map (lambda (kind) (c:coerce 65 kind)) '(char string symbol list vector)))
(check-equal "string numeric and atom coercions" '(3/4 12 hello)
  (list (c:coerce "3/4" 'number) (c:coerce "12" 'atom) (c:coerce "hello" 'atom)))
(check-equal "string sequence conversions" '(#\a (#\a #\b) #(#\a #\b))
  (list (c:coerce "a" 'char) (c:coerce "ab" 'list) (c:coerce "ab" 'vector)))
(check-equal "symbol coercions" '(#\A 12 "hi" (#\h #\i) #(#\h #\i))
  (list (c:coerce 'A 'char) (c:coerce '|12| 'number) (c:coerce 'hi 'string)
        (c:coerce 'hi 'list) (c:coerce 'hi 'vector)))
(check-equal "list coercions" '(#\A 12 "ab" ab #(1 2))
  (list (c:coerce '(#\A) 'char) (c:coerce '(#\1 #\2) 'number)
        (c:coerce '(#\a #\b) 'string) (c:coerce '(#\a #\b) 'symbol) (c:coerce '(1 2) 'vector)))
(check-equal "vector character and string coercions" '(#\A "ab")
  (list (c:coerce '#(#\A) 'char) (c:coerce '#(#\a #\b) 'string)))
(check-equal "vector to number" 12 (observed (c:coerce '#(#\1 #\2) 'number)))
(check-equal "vector to symbol" 'ab (observed (c:coerce '#(#\a #\b) 'symbol)))
(check-equal "vector to list copies the elements" '(1 2) (observed (c:coerce '#(1 2) 'list)))
(check-equal "empty sequence conversions" '(() #() "")
  (list (c:coerce "" 'list) (c:coerce '() 'vector) (c:coerce '#() 'string)))
(check-error "non-numeric text is rejected" (c:coerce "no" 'number))
(check-error "multi-character strings cannot become one character" (c:coerce "ab" 'char))
(check-error "unsupported conversions are rejected" (c:coerce #f 'number))
(smoke-finish)
