(import (scheme base) (prefix (srfi 63) a:) (slib charplot) (only (srfi 95) sort) (patina compat smoke))
(define (capture thunk)
  (let ((out (open-output-string)))
    (parameterize ((current-output-port out) (charplot:dimensions '(12 48))) (thunk))
    (get-output-string out)))
(define (count-char text char)
  (let loop ((i 0) (n 0))
    (if (= i (string-length text)) n
        (loop (+ i 1) (+ n (if (char=? char (string-ref text i)) 1 0))))))
(define (contains? text part)
  (let loop ((i 0))
    (and (<= (+ i (string-length part)) (string-length text))
         (or (string=? part (substring text i (+ i (string-length part)))) (loop (+ i 1))))))
(define points '((0 0) (1 1) (2 2)))
(define rendered (capture (lambda () (plot points "TIME" "VALUE"))))
(check-equal "explicit dimensions bound output rows and columns" '(576 12)
  (list (string-length rendered) (count-char rendered #\newline)))
(check-equal "axis labels appear in the plot" #t
  (and (contains? rendered "TIME") (contains? rendered "VALUE")))
(check-equal "one curve emits a marker for each distinct point" 3 (count-char rendered #\*))
(check-equal "plotting restores the dimension parameter" #f (charplot:dimensions))
(check-equal "dotted coordinate pairs render identically" rendered
  (capture (lambda () (plot '((0 . 0) (1 . 1) (2 . 2)) "TIME" "VALUE"))))
(check-equal "rank-two arrays render the same coordinate rows" rendered
  (capture (lambda () (plot (a:list->array 2 '#() points) "TIME" "VALUE"))))
(check-equal "rank-one vectors use their indices as x coordinates" rendered
  (capture (lambda () (plot '#(0 1 2) "TIME" "VALUE"))))
(check-equal "multiple curves use distinct marker characters" '(3 3)
  (let ((out (capture (lambda () (plot '((0 0 2) (1 1 3) (2 2 4)) "x" "y")))))
    (list (count-char out #\*) (count-char out #\+))))
(check-equal "function plots sample both endpoints exactly once" '(0 1 2 3 4)
  (let ((visited '()))
    (capture (lambda () (plot (lambda (x) (set! visited (cons x visited)) x) 0 4 5)))
    (sort (map exact visited) <)))
(check-equal "histogram accepts lists and vectors and emits bars" #t
  (let ((a (capture (lambda () (histograph '(0 0 1 2 2 2) "SAMPLE"))))
        (b (capture (lambda () (histograph '#(0 0 1 2 2 2) "SAMPLE")))) )
    (and (string=? a b) (> (count-char a #\I) 0) (contains? a "SAMPLE"))))
(smoke-finish)
