(import (scheme base) (srfi 180))
(import (patina compat smoke))

(define (read-json text) (json-read (open-input-string text)))
(define (write-json value)
  (let ((port (open-output-string)))
    (json-write value port)
    (get-output-string port)))
(define (json-error-with-reason? thunk)
  (guard (ex ((json-error? ex)
              (let ((reason (json-error-reason ex)))
                (and (string? reason) (> (string-length reason) 0))))
             (else #f))
    (thunk)
    #f))

(check-equal "array scalar types" '#(1 -2 #t #f "hello" null)
  (read-json "[1,-2,true,false,\"hello\",null]"))
(check-equal "null is distinct from false and an empty object" '(#t #f #f)
  (list (json-null? (read-json "null")) (json-null? (read-json "false"))
        (json-null? (read-json "{}"))))
(check-equal "empty containers have distinct representations" '(#() ())
  (list (read-json "[]") (read-json "{}")))
(check-equal "Unicode and escaped characters" "Aλ\n\"\\"
  (read-json "\"\\u0041\\u03bb\\n\\\"\\\\\""))
(define object (read-json "{\"answer\":42,\"items\":[true,null]}"))
(check-equal "object keys become symbols" '(42 #(#t null))
  (list (cdr (assq 'answer object)) (cdr (assq 'items object))))
(define decoded (read-json (write-json object)))
(check-equal "nested object round trip by fields" '(42 #(#t null))
  (list (cdr (assq 'answer decoded)) (cdr (assq 'items decoded))))
(check-equal "writer escapes strings for a round trip" "line\n\"quoted\"\\tail"
  (read-json (write-json "line\n\"quoted\"\\tail")))
(define lines (json-lines-read (open-input-string "1\n[2,3]\nfalse\n")))
(define line-one (lines))
(define line-two (lines))
(define line-three (lines))
(check-equal "line reader advances and reaches EOF" '(1 #(2 3) #f #t)
  (list line-one line-two line-three (eof-object? (lines))))
(check-equal "empty input returns EOF" #t (eof-object? (read-json "")))
(check-equal "truncated input raises a JSON error with a reason" #t
  (json-error-with-reason? (lambda () (read-json "[1,"))))
;; #505: JSON's number grammar is narrower than Scheme's string->number.
;; Compare numerically: exactness of parsed fractions/exponents may vary.
(check-equal "valid integer spellings" '(#t #t #t #t)
  (map (lambda (text expected) (= (read-json text) expected))
       '("0" "-0" "123" "-123") '(0 0 123 -123)))
(check-equal "valid fractions and exponents" '(#t #t #t #t #t #t #t)
  (map (lambda (text expected) (= (read-json text) expected))
       '("0.5" "-0.5" "1.25" "1e2" "1E+2" "1e-2" "-1.25E+2")
       '(0.5 -0.5 1.25 100 100 0.01 -125)))
(define (rejects-numbers? spellings)
  (map (lambda (text)
         (json-error-with-reason?
           (lambda () (read-json (string-append "[" text "]")))))
       spellings))
(check-equal "leading zeros are rejected" '(#t #t #t #t #t)
  (rejects-numbers? '("01" "-01" "00" "00.5" "01e2")))
(check-equal "fractions require digits on both sides" '(#t #t #t #t)
  (rejects-numbers? '(".5" "-.5" "1." "1.e2")))
(check-equal "exponents require digits after an optional sign" '(#t #t #t #t #t)
  (rejects-numbers? '("1e" "1E+" "1e-" "1e+-2" "1e2.0")))
(check-equal "Scheme-only numeric syntax is rejected" '(#t #t #t #t #t #t #t)
  (rejects-numbers? '("+1" "1/2" "1+2i" "#x10" "#e1" "+inf.0" "+nan.0")))
(check-equal "invalid signs and non-ASCII digits are rejected" '(#t #t #t #t #t)
  (rejects-numbers? '("-" "--1" "1-2" "١" "1٢")))
(check-equal "writer rejects unsupported values with a JSON error" #t
  (json-error-with-reason? (lambda () (write-json 'unsupported))))
(smoke-finish)
