(import (scheme base) (prefix (srfi 38) s:) (patina compat smoke))
(define (encode datum)
  (let ((port (open-output-string)))
    (s:write-with-shared-structure datum port)
    (get-output-string port)))
(define (decode text) (s:read-with-shared-structure (open-input-string text)))
(define (roundtrip datum) (decode (encode datum)))
;; Assert values and object identity, not the writer's choice of label numbers.
(check-equal "ordinary datums survive the shared-structure reader and writer"
  '(1 #t "a\"b\\c" #\newline #(1 2) (x . y))
  (roundtrip '(1 #t "a\"b\\c" #\newline #(1 2) (x . y))))
(check-equal "shared pairs retain identity and mutation visibility" '(#t changed)
  (let* ((pair (list 'original)) (copy (roundtrip (vector pair pair))))
    (set-car! (vector-ref copy 0) 'changed)
    (list (eq? (vector-ref copy 0) (vector-ref copy 1))
          (car (vector-ref copy 1)))))
(check-equal "a circular pair remains circular" '(loop #t)
  (let ((pair (cons 'loop #f)))
    (set-cdr! pair pair)
    (let ((copy (roundtrip pair))) (list (car copy) (eq? copy (cdr copy))))))
(check-equal "a vector can contain itself" #t
  (let ((v (vector #f)))
    (vector-set! v 0 v)
    (let ((copy (roundtrip v))) (eq? copy (vector-ref copy 0)))))
(check-equal "cycles can cross pair and vector boundaries" '(node #t)
  (let* ((v (vector #f)) (pair (cons 'node v)))
    (vector-set! v 0 pair)
    (let ((copy (roundtrip pair)))
      (list (car copy) (eq? copy (vector-ref (cdr copy) 0))))))
(check-equal "a shared string retains mutation visibility" '(#t "Xbc")
  (let* ((text (string-copy "abc")) (copy (roundtrip (vector text text))))
    (string-set! (vector-ref copy 0) 0 #\X)
    (list (eq? (vector-ref copy 0) (vector-ref copy 1)) (vector-ref copy 1))))
(check-equal "equal but distinct objects are not merged" '(#t #f)
  (let ((copy (roundtrip (vector (list 1) (list 1)))))
    (list (equal? (vector-ref copy 0) (vector-ref copy 1))
          (eq? (vector-ref copy 0) (vector-ref copy 1)))))
(check-equal "the reader resolves an explicit circular label" '(a #t)
  (let ((datum (decode "#7=(a . #7#)"))) (list (car datum) (eq? datum (cdr datum)))))
(check-equal "shared dotted tails keep their identity" '(a b (end) #t)
  (let* ((tail (list 'end)) (copy (roundtrip (list (cons 'a tail) (cons 'b tail)))))
    (list (caar copy) (car (cadr copy)) (cdar copy)
          (eq? (cdar copy) (cdr (cadr copy))))))
(check-equal "each top-level read has its own label scope" '((a) (b) #f #t)
  (let* ((port (open-input-string "#0=(a) #0=(b)"))
         (first (s:read-with-shared-structure port))
         (second (s:read-with-shared-structure port)))
    (list first second (eq? first second)
          (eof-object? (s:read-with-shared-structure port)))))
(check-equal "the reader skips whitespace and line comments" '(1 2)
  (decode " ; heading\n (1 ; between\n 2) "))
(check-equal "default ports use the current dynamic ports" '(hello . world)
  (let* ((out (open-output-string))
         (ignored (parameterize ((current-output-port out))
                    (s:write-with-shared-structure '(hello . world)))))
    (parameterize ((current-input-port (open-input-string (get-output-string out))))
      (s:read-with-shared-structure))))
(check-error "undefined labels are rejected" (decode "(#9#)"))
(check-error "duplicate labels in one datum are rejected" (decode "(#1=(a) #1=(b))"))
(check-equal "strings containing control characters survive a round trip"
  "line\nnext\ttab\rreturn" (roundtrip "line\nnext\ttab\rreturn"))
(check-equal "the reader decodes hexadecimal string escapes" "λ"
  (decode "\"\\x3bb;\""))
(check-equal "escaped shared strings remain mutable and retain identity"
  '(#t "X\n")
  (let* ((text (string #\a #\newline)) (copy (roundtrip (vector text text))))
    (string-set! (vector-ref copy 0) 0 #\X)
    (list (eq? (vector-ref copy 0) (vector-ref copy 1)) (vector-ref copy 1))))
(smoke-finish)
