(import (scheme base) (prefix (srfi 78) s:) (srfi 42) (patina compat smoke))
;; The pinned .sld exports only check, check-ec, check-report and check-set-mode!.
;; Exercise their public behavior by capturing reports, including deliberate
;; failures, so the smoke driver fails if the checking machinery stops working.
(define (capture thunk)
  (let ((out (open-output-string)))
    (parameterize ((current-output-port out)) (thunk))
    (get-output-string out)))
(define (contains? text part)
  (let ((end (- (string-length text) (string-length part))))
    (let loop ((i 0))
      (and (<= i end)
           (or (string=? part (substring text i (+ i (string-length part))))
               (loop (+ i 1)))))))
(define (summary)
  (s:check-set-mode! 'summary)
  (capture s:check-report))
(check-equal "a fresh checker reports zero counts"
  "\n; *** checks *** : 0 correct, 0 failed.\n" (summary))
(check-equal "summary mode evaluates checks without individual output" '("" 1)
  (let ((calls 0))
    (let ((output (capture (lambda ()
                            (s:check (begin (set! calls (+ calls 1)) '(a b))
                              => '(a b))))))
      (list output calls))))
(check-equal "successful checks increment the report"
  "\n; *** checks *** : 1 correct, 0 failed.\n" (summary))
(check-equal "custom equality and expected value precede the expression"
  '(1 1 1)
  (let ((predicates 0) (expected 0) (calls 0))
    (s:check (begin (set! calls (+ calls 1))
                   (if (and (= predicates 1) (= expected 1)) "OK" "bad order"))
      (=> (begin (set! predicates (+ predicates 1)) string=?))
      (begin (set! expected (+ expected 1)) "OK"))
    (list predicates expected calls)))
(check-equal "parametric checks visit every successful binding" '(0 1 2 3)
  (let ((seen '()))
    (s:check-ec (:range i 4)
      (begin (set! seen (cons i seen)) (* i i)) => (* i i) (i))
    (reverse seen)))
(check-equal "one comprehension counts as one check"
  "\n; *** checks *** : 3 correct, 0 failed.\n" (summary))
(check-equal "off mode suppresses expressions generators diagnostics and reports"
  '("" 0)
  (let ((calls 0))
    (s:check-set-mode! 'off)
    (let ((output
            (capture (lambda ()
                       (s:check (begin (set! calls (+ calls 1)) #t)
                         (=> (error "disabled predicate")) (error "disabled expected"))
                       (s:check-ec (:range i (error "disabled generator"))
                         (error "disabled expression") => (error "disabled expected"))
                       (s:check-report)))))
      (list output calls))))
(check-equal "turning checks back on preserves accumulated counts"
  "\n; *** checks *** : 3 correct, 0 failed.\n" (summary))
(check-equal "failed parametric checks stop at the first counterexample" '(0 1 2)
  (let ((seen '()))
    (s:check-ec (:range i 6)
      (begin (set! seen (cons i seen)) (< i 2)) => #t (i))
    (reverse seen)))
(check-equal "a failed comprehension counts once"
  "\n; *** checks *** : 3 correct, 1 failed.\n" (summary))
(check-equal "report-failed suppresses success and prints failures" '("" #t #t)
  (begin
    (s:check-set-mode! 'report-failed)
    (let* ((success (capture (lambda () (s:check 'ok => 'ok))))
           (failure (capture (lambda () (s:check 'actual => 'expected)))))
      (list success (contains? failure "*** failed ***")
            (contains? failure "expected result: expected")))))
(check-equal "reports retain the first counterexample and its bindings" '(#t #t #t)
  (let ((output (capture s:check-report)))
    (list (contains? output "4 correct, 2 failed.")
          (contains? output "First failed example:")
          (contains? output "(i 2)"))))
(check-equal "report mode prints a successful result" #t
  (begin
    (s:check-set-mode! 'report)
    (contains? (capture (lambda () (s:check (+ 1 2) => 3))) "3 ; correct")))
(check-equal "parametric checks use indexed generators from the corpus dependency"
  '((a 0) (b 1) (c 2))
  (let ((seen '()))
    (s:check-set-mode! 'summary)
    (s:check-ec (:vector x (index i) #(a b) #() #(c))
      (begin (set! seen (cons (list x i) seen)) (list x i))
      => (list x i) (x i))
    (reverse seen)))
(check-error "unknown modes are rejected" (s:check-set-mode! 'unknown))
(smoke-finish)
