(import (scheme base) (scheme write) (prefix (srfi 63) a:))
(import (patina compat smoke))
(define grid (a:make-array '#(0) 2 3))
(check-equal "rank and dimensions" '(2 (2 3))
  (list (a:array-rank grid) (a:array-dimensions grid)))
(check-equal "initial contents" '((0 0 0) (0 0 0)) (a:array->list grid))
(a:array-set! grid 9 1 2)
(check-equal "indexed mutation" 9 (a:array-ref grid 1 2))
(check-equal "bounds" '(#t #f)
  (list (a:array-in-bounds? grid 1 2) (a:array-in-bounds? grid 2 0)))
(define transposed (a:make-shared-array grid (lambda (i j) (list j i)) 3 2))
(a:array-set! transposed 7 0 1)
(check-equal "shared view updates the original" 7 (a:array-ref grid 1 0))
(check-equal "nested list round trip" '((1 2) (3 4))
  (a:array->list (a:list->array 2 '#(0) '((1 2) (3 4)))))
(smoke-finish)
