(import (scheme base) (prefix (srfi 39) s:) (patina compat smoke))
;; The prefix ensures these are the corpus's Scheme parameter procedures.
(define p (s:make-parameter 'root))
(check-equal "a new parameter returns its initial value" 'root (p))
(p 'global)
(check-equal "setting a parameter changes its global cell" 'global (p))
(define converted '())
(define q (s:make-parameter 2 (lambda (v) (set! converted (cons v converted)) (* v 10))))
(q 3)
(check-equal "the converter runs for creation and assignment" '(30 (2 3))
  (list (q) (reverse converted)))
(check-equal "dynamic binding converts once and restores the outer cell"
  '(40 30 (2 3 4))
  (let ((inside (s:parameterize ((q 4)) (q))))
    (list inside (q) (reverse converted))))
(check-equal "nested extents restore their enclosing values"
  '((outer inner outer) global)
  (let ((inside (s:parameterize ((p 'outer))
                  (list (p) (s:parameterize ((p 'inner)) (p)) (p)))))
    (list inside (p))))
(check-equal "assignment within an extent leaves the global cell intact"
  '(changed global)
  (let ((inside (s:parameterize ((p 'local)) (p 'changed) (p))))
    (list inside (p))))
(define a (s:make-parameter 'a))
(define b (s:make-parameter 'b))
(check-equal "simultaneous bindings evaluate values in the outer environment"
  '((b a) a b)
  (let ((inside (s:parameterize ((a (b)) (b (a))) (list (a) (b)))))
    (list inside (a) (b))))
(check-equal "parameter and value expressions are each evaluated once" '(local 1 1)
  (let ((parameters 0) (values 0))
    (let ((inside (s:parameterize
                   (((begin (set! parameters (+ parameters 1)) p)
                     (begin (set! values (+ values 1)) 'local)))
                   (p))))
      (list inside parameters values))))
(check-equal "exceptions leave the dynamic binding" '(caught global)
  (let ((result (guard (ex (else 'caught))
                  (s:parameterize ((p 'local)) (error "leave extent")))))
    (list result (p))))
(check-equal "continuation escape restores the outer binding" '(local global)
  (let ((escaped (call/cc (lambda (escape)
                           (s:parameterize ((p 'local)) (escape (p)))))))
    (list escaped (p))))
(check-equal "continuation reentry reinstalls the captured binding"
  '((local global local global) global)
  (let ((saved #f) (again #t) (seen '()))
    (s:parameterize ((p 'local))
      (call/cc (lambda (k) (set! saved k)))
      (set! seen (cons (p) seen)))
    (set! seen (cons (p) seen))
    (if again (begin (set! again #f) (saved 'resume)))
    (list (reverse seen) (p))))
(check-equal "an extent forwards multiple return values" '(one two)
  (call-with-values (lambda () (s:parameterize ((p 'local)) (values 'one 'two))) list))
(smoke-finish)
