(import (scheme base) (prefix (srfi 25) a:) (patina compat smoke))
(define bounds (a:shape -1 1 3 6))
(define matrix (a:array bounds 'a 'b 'c 'd 'e 'f))
(check-equal "arrays and shapes are recognized" '(#t #t #f #f)
  (list (a:array? matrix) (a:array? bounds) (a:array? '()) (a:array? 42)))
(check-equal "shape is a rank-two array of bounds" '(2 0 2 0 2 -1 1 3 6)
  (list (a:array-rank bounds) (a:array-start bounds 0) (a:array-end bounds 0)
        (a:array-start bounds 1) (a:array-end bounds 1)
        (a:array-ref bounds 0 0) (a:array-ref bounds 0 1)
        (a:array-ref bounds 1 0) (a:array-ref bounds 1 1)))
(check-equal "nonzero and negative bounds preserve row-major order"
  '(2 -1 1 3 6 a b c d e f)
  (list (a:array-rank matrix) (a:array-start matrix 0) (a:array-end matrix 0)
        (a:array-start matrix 1) (a:array-end matrix 1)
        (a:array-ref matrix -1 3) (a:array-ref matrix -1 4)
        (a:array-ref matrix -1 5) (a:array-ref matrix 0 3)
        (a:array-ref matrix 0 4) (a:array-ref matrix 0 5)))
(check-equal "vectors and rank-one arrays can supply indices" '(b f)
  (list (a:array-ref matrix #(-1 4))
        (a:array-ref matrix (a:array (a:shape 0 2) 0 5))))
(check-equal "all three index forms support mutation" '(x y z)
  (let ((m (a:make-array (a:shape 0 1 0 3) #f)))
    (a:array-set! m 0 0 'x)
    (a:array-set! m #(0 1) 'y)
    (a:array-set! m (a:array (a:shape 0 2) 0 2) 'z)
    (list (a:array-ref m 0 0) (a:array-ref m 0 1) (a:array-ref m 0 2))))
(check-equal "the initial object is shared across filled cells" '(#t changed)
  (let* ((value (list 'original)) (m (a:make-array (a:shape 0 2) value)))
    (set-car! (a:array-ref m 0) 'changed)
    (list (eq? (a:array-ref m 0) (a:array-ref m 1)) (car (a:array-ref m 1)))))
(check-equal "constructed arrays do not retain their shape argument" '(2 2 a filled)
  (let* ((s (a:shape 0 2)) (m (a:array s 'a 'b)) (n (a:make-array s 'filled)))
    (a:array-set! s 0 1 1)
    (list (a:array-end m 0) (a:array-end n 0) (a:array-ref m 0) (a:array-ref n 1))))
(check-equal "rank-zero arrays contain one mutable element" '(0 before after)
  (let* ((m (a:array (a:shape) 'before)) (old (a:array-ref m)))
    (a:array-set! m 'after)
    (list (a:array-rank m) old (a:array-ref m))))
(check-equal "an empty dimension retains its bounds" '(2 3 3 -2 1)
  (let ((m (a:array (a:shape 3 3 -2 1))))
    (list (a:array-rank m) (a:array-start m 0) (a:array-end m 0)
          (a:array-start m 1) (a:array-end m 1))))
(check-equal "a transpose shares mutations in both directions" '(c left right)
  (let* ((m (a:array (a:shape 0 2 0 2) 'a 'b 'c 'd))
         (t (a:share-array m (a:shape 0 2 0 2) (lambda (i j) (values j i))))
         (old (a:array-ref t 0 1)))
    (a:array-set! t 1 0 'left)
    (a:array-set! m 1 1 'right)
    (list old (a:array-ref m 0 1) (a:array-ref t 1 1))))
(check-equal "a diagonal view maps one index to two dimensions" '(x 0 0 y)
  (let* ((m (a:make-array (a:shape 0 2 0 2) 0))
         (d (a:share-array m (a:shape 0 2) (lambda (i) (values i i)))))
    (a:array-set! d 0 'x)
    (a:array-set! d 1 'y)
    (list (a:array-ref m 0 0) (a:array-ref m 0 1)
          (a:array-ref m 1 0) (a:array-ref m 1 1))))
(check-equal "nested views compose affine mappings" '(d b changed)
  (let* ((m (a:array (a:shape 0 4) 'a 'b 'c 'd))
         (r (a:share-array m (a:shape 0 4) (lambda (i) (- 3 i))))
         (s (a:share-array r (a:shape 0 2) (lambda (i) (* 2 i))))
         (old (list (a:array-ref s 0) (a:array-ref s 1))))
    (a:array-set! s 1 'changed)
    (append old (list (a:array-ref m 1)))))
(check-equal "shared arrays also copy their shape argument" '(2 b)
  (let* ((m (a:array (a:shape 0 2) 'a 'b)) (s (a:shape 0 2))
         (view (a:share-array m s (lambda (i) i))))
    (a:array-set! s 0 1 1)
    (list (a:array-end view 0) (a:array-ref view 1))))
(check-equal "rank-four arrays exercise general affine indexing" '(4 last)
  (let ((m (a:make-array (a:shape 0 2 1 3 -1 1 4 6) 'initial)))
    (a:array-set! m 1 2 0 5 'last)
    (list (a:array-rank m) (a:array-ref m #(1 2 0 5)))))
(check-error "an odd number of shape bounds is rejected" (a:shape 0 2 3))
(check-error "decreasing bounds are rejected" (a:shape 2 1))
(check-error "constructor element counts must match the shape"
  (a:array (a:shape 0 2) 'only-one))
(check-error "the upper bound is excluded" (a:array-ref matrix 1 3))
(check-error "too few indices are rejected" (a:array-ref matrix -1))
(check-error "an empty dimension has no valid element"
  (a:array-ref (a:make-array (a:shape 3 3)) 3))
(smoke-finish)
