(import (scheme base) (prefix (srfi 43) v:))
(import (patina compat smoke))

(check-equal "unfold carries two seeds through multiple values" '#(0 1 1 2 3 5)
  (v:vector-unfold (lambda (i a b) (values a b (+ a b))) 6 0 1))
(check-equal "unfold-right visits descending indices" '#(3 12 21 30)
  (v:vector-unfold-right (lambda (i seed) (values (+ (* i 10) seed) (+ seed 1)))
                         4 0))
(check-equal "copy extends a slice with the supplied fill" '#(b c pad pad)
  (v:vector-copy '#(a b c) 1 5 'pad))
(check-equal "copy accepts the empty range at the end" '#()
  (v:vector-copy '#(a b c) 3 3))
(check-equal "map receives indices and stops at the shortest vector" '#(11 23)
  (v:vector-map (lambda (i a b) (+ i a b)) '#(1 2 3) '#(10 20)))
(check-equal "fold receives index before accumulator"
  '((2 c) (1 b) (0 a))
  (v:vector-fold (lambda (i acc value) (cons (list i value) acc)) '() '#(a b c)))
(check-equal "fold-right visits the opposite direction"
  '((0 a) (1 b) (2 c))
  (v:vector-fold-right (lambda (i acc value) (cons (list i value) acc))
                       '() '#(a b c)))
(check-equal "search indices and absence" '(1 3 #f)
  (list (v:vector-index even? '#(1 2 3 4))
        (v:vector-index-right even? '#(1 2 3 4))
        (v:vector-index even? '#(1 3 5))))
(define mapped (vector 2 4 6))
(v:vector-map! (lambda (i value) (+ i value)) mapped)
(check-equal "indexed map mutates its destination" '#(2 5 8) mapped)
(define reversed (vector 'a 'b 'c 'd 'e))
(v:vector-reverse! reversed 1 4)
(check-equal "reverse mutates only the requested range" '#(a d c b e) reversed)
(define copied (make-vector 5 'pad))
(v:vector-reverse-copy! copied 1 '#(a b c d) 1 4)
(check-equal "reverse-copy respects source and destination bounds"
  '#(pad d c b pad) copied)
(check-error "reverse-copy rejects an overflowing destination"
  (v:vector-reverse-copy! (make-vector 2) 1 '#(a b c)))
(smoke-finish)
