(import (scheme base) (prefix (srfi 95) s:))
(import (patina compat smoke))

(check-equal "empty and singleton sequences are sorted" '(#t #t #t #t #t #t)
  (list (s:sorted? '() <) (s:sorted? '(1) <)
        (s:sorted? '#() <) (s:sorted? '#(1) <)
        (s:sorted? "" char<?) (s:sorted? "a" char<?)))
(check-equal "sortedness allows ties and detects inversions" '(#t #f #t #f)
  (list (s:sorted? '(1 1 3) <) (s:sorted? '(1 3 2) <)
        (s:sorted? '#(1 1 3) <) (s:sorted? '#(1 3 2) <)))
;; #504: the pristine package skips the adjacent comparison for length two.
(check-equal "two-element vectors compare adjacent elements" '(#t #t #f)
  (list (s:sorted? '#(1 2) <) (s:sorted? '#(2 2) <)
        (s:sorted? '#(2 1) <)))
(check-equal "two-element strings compare adjacent elements" '(#t #t #f)
  (list (s:sorted? "ab" char<?) (s:sorted? "aa" char<?)
        (s:sorted? "ba" char<?)))
(check-equal "two-element vectors use the key" '(#t #f)
  (list (s:sorted? '#((1 . a) (2 . b)) < car)
        (s:sorted? '#((2 . a) (1 . b)) < car)))

(define records (list (cons 2 'a) (cons 1 'b) (cons 2 'c) (cons 1 'd)))
(define key-calls 0)
(define ordered
  (s:sort records < (lambda (entry)
                     (set! key-calls (+ key-calls 1))
                     (car entry))))
(check-equal "stable sort with a key" '((1 . b) (1 . d) (2 . a) (2 . c))
  ordered)
(check-equal "sort preserves the input list" '((2 . a) (1 . b) (2 . c) (1 . d))
  records)
(check-equal "key is evaluated once per element" 4 key-calls)
(define numbers (vector 3 1 2))
(check-equal "vector sort copies without mutation" '(#(1 2 3) #(3 1 2))
  (list (s:sort numbers <) numbers))
(define sorted-numbers (s:sort! numbers >))
(check-equal "destructive vector sort returns its input" '(#t #(3 2 1))
  (list (eq? sorted-numbers numbers) numbers))
(define mutable-list (list 3 1 2))
(define sorted-list (s:sort! mutable-list <))
(check-equal "destructive list sort preserves its head" '(#t (1 2 3))
  (list (eq? sorted-list mutable-list) mutable-list))
(check-equal "merge keeps equal keys from the left first"
  '((1 . left) (1 . right) (2 . right) (3 . left))
  (s:merge '((1 . left) (3 . left)) '((1 . right) (2 . right)) < car))
(define left (list 1 3 5))
(define right (list 2 4 6))
(define merged (s:merge! left right <))
(check-equal "destructive merge links both inputs" '(#t #t (1 2 3 4 5 6))
  (list (eq? merged left) (eq? (cdr merged) right) merged))
(check-equal "empty sort and merge" '(() (1 2) (1 2))
  (list (s:sort '() <) (s:merge '() '(1 2) <) (s:merge '(1 2) '() <)))
(smoke-finish)
