(import (scheme base) (prefix (srfi 51) s:) (patina compat smoke))
;; The checked, unchecked and argument-search modes are specified at:
;; https://srfi.schemers.org/srfi-51/srfi-51.html
(define (results . args) (call-with-values (lambda () (apply s:rest-values args)) list))
(check-equal "rest-values forwards zero or several values" '(() (a 1))
  (list (results '()) (results '(a 1))))
(check-equal "unchecked defaults fill only missing positions" '((a 20 30) (a b c d))
  (list (results '(a) - 'default 20 30) (results '(a b c d) - 10 20)))
(check-equal "checked defaults combine membership and predicates" '(blue 7 "tail")
  (results '(blue 7) + '(red blue) (cons 0 number?) (cons "tail" string?)))
(check-equal "bounded unchecked mode preserves false values" '(#f 2)
  (results '(#f) -2 'fallback 2))
(check-equal "argument-search mode reorders matches and fills defaults" '(7 "tail" blue)
  (results '(blue 7) #t (cons 0 number?) (cons "tail" string?) '(red blue)))
(check-equal "permissive search mode appends unmatched arguments" '(7 red extra)
  (results '(extra 7) #f (cons 0 number?) '(red blue)))
(check-equal "caller annotations do not affect successful values" '((1 2) (1 2))
  (list (results 'caller '(1) -2 0 2) (results "caller" '(1) -2 0 2)))
(check-error "argument count limits are enforced" (results '(1 2 3) 2))
(check-error "default count limits are enforced" (results '() -1 10 20))
(check-error "checked mode rejects a mismatched argument"
  (results '(bad) + (cons 0 number?)))
(check-error "strict search rejects unmatched arguments"
  (results '(extra 7) #t (cons 0 number?)))
(check-equal "arg-and returns the last successful check's value" 3
  (let ((x '(a b c))) (s:arg-and x (list? x) (length x))))
(check-equal "arg-ands checks multiple argument groups" #t
  (let ((x 3) (y "text"))
    (s:arg-ands common 'caller (x (number? x) (> x 0)) (y (string? y)))))
(check-equal "arg-or and arg-ors accept false error conditions" '(#f #f)
  (let ((x 3) (y 4))
    (list (s:arg-or x (negative? x) (zero? x))
          (s:arg-ors common 'caller (x (negative? x)) (y (negative? y))))))
(check-equal "err-and and err-ands retain successful expression results" '(ok last)
  (list (s:err-and 'caller #t 'ok)
        (s:err-ands ('first #t) ("second" 'last))))
(check-equal "err-or and err-ors accept false expressions" '(#f #f)
  (list (s:err-or 'caller #f #f) (s:err-ors ('first #f) ("second" #f))))
(check-equal "arg-and stops at the first failed condition" '(#t 1)
  (let ((calls 0) (x 1))
    (let ((raised (guard (ex (else #t))
                    (s:arg-and x
                      (begin (set! calls (+ calls 1)) #f)
                      (begin (set! calls (+ calls 1)) #t))
                    #f)))
      (list raised calls))))
(check-equal "arg-or stops at the first true error condition" '(#t 1)
  (let ((calls 0) (x 1))
    (let ((raised (guard (ex (else #t))
                    (s:arg-or x
                      (begin (set! calls (+ calls 1)) #t)
                      (begin (set! calls (+ calls 1)) #f))
                    #f)))
      (list raised calls))))
(check-error "err-and signals a false expression" (s:err-and 'caller #t #f))
(check-error "err-or signals a true expression" (s:err-or 'caller #f #t))
(smoke-finish)
