(import (scheme base) (prefix (srfi 227) s:))
(import (patina compat smoke))

(define choose (s:opt-lambda (required (a 10) (b 20)) (list required a b)))
(check-equal "optional arguments may be absent or supplied"
  '((1 10 20) (1 2 20) (1 2 3))
  (list (choose 1) (choose 1 2) (choose 1 2 3)))
(check-equal "all arguments can be optional" '(10 20)
  ((s:opt-lambda ((a 10) (b 20)) (list a b))))
(define rest-args (s:opt-lambda (a (b 20) . rest) (list a b rest)))
(check-equal "rest arguments follow the optional positions"
  '((1 20 ()) (1 2 ()) (1 2 (3 4)))
  (list (rest-args 1) (rest-args 1 2) (rest-args 1 2 3 4)))
(check-equal "opt-lambda defaults use the outer lexical environment"
  '((3 11 21) (3 4 21))
  (let ((x 10) (y 20))
    (let ((f (s:opt-lambda (x (y (+ x 1)) (z (+ y 1))) (list x y z))))
      (list (f 3) (f 3 4)))))
(define sequential
  (s:opt*-lambda (x (y (+ x 1)) (z (+ y 1))) (list x y z)))
(check-equal "opt*-lambda defaults see earlier parameters" '((3 4 5) (3 10 11))
  (list (sequential 3) (sequential 3 10)))
(define default-calls 0)
(define with-default
  (s:opt-lambda ((x (begin (set! default-calls (+ default-calls 1))
                           default-calls)))
    x))
(define explicit-false (with-default #f))
(check-equal "an explicit false argument bypasses its default" '(#f 0)
  (list explicit-false default-calls))
(define default-first (with-default))
(define default-second (with-default))
(check-equal "missing defaults are evaluated afresh per call" '(1 2 2)
  (list default-first default-second default-calls))
(define visits '())
(define (visit label)
  (set! visits (cons label visits))
  (length visits))
(define visited ((s:opt*-lambda ((a (visit 'a)) (b (visit 'b))) (list a b))))
(check-equal "sequential defaults run left to right" '((1 2) (a b))
  (list visited (reverse visits)))
(define expression-calls 0)
(define bound
  (s:let-optionals (begin (set! expression-calls (+ expression-calls 1)) '(3))
      (x (y 20))
    (list x y)))
(check-equal "let-optionals evaluates its input once" '((3 20) 1)
  (list bound expression-calls))
(check-equal "let-optionals* combines dependent defaults and rest arguments"
  '((3 4 7 ()) (3 4 5 (6)))
  (list (s:let-optionals* '(3) (x (y (+ x 1)) (z (+ x y)) . rest)
          (list x y z rest))
        (s:let-optionals* '(3 4 5 6) (x (y (+ x 1)) (z (+ x y)) . rest)
          (list x y z rest))))
(check-error "missing required argument raises" (choose))
(check-error "excess arguments without rest raise" (choose 1 2 3 4))
(smoke-finish)
