(import (scheme base) (prefix (srfi 2) s:))
(import (patina compat smoke))

(check-equal "empty claws without a body" #t (s:and-let* ()))
(check-equal "empty claws evaluate the body" 42
  (s:and-let* () 'ignored 42))
(check-equal "later bindings see earlier bindings" '(3 6 9)
  (s:and-let* ((a 3) (b (* a 2)) (c (+ a b))) (list a b c)))
(check-equal "identifier and expression claws" 'accepted
  (let ((ready #t))
    (s:and-let* (ready ((< 2 3))) 'accepted)))
(check-equal "bodyless form returns the final value" '(last)
  (s:and-let* ((first '(first)) (last '(last)))))
(define skipped 0)
(define stopped
  (s:and-let* ((first #f)
              (second (begin (set! skipped (+ skipped 1)) #t)))
    (set! skipped (+ skipped 1))
    'unreachable))
(check-equal "false stops later initializers and the body" '(#f 0)
  (list stopped skipped))
(define visits '())
(define (visit label value)
  (set! visits (cons label visits))
  value)
(define result
  (s:and-let* ((a (visit 'first 2))
              ((visit 'guard #t))
              (b (visit 'second (+ a 3))))
    (visit 'body (+ a b))))
(check-equal "claws and body run once in order" '(7 (first guard second body))
  (list result (reverse visits)))
(check-equal "bindings stay local to the form" '(3 10)
  (let ((x 10))
    (list (s:and-let* ((x 3)) x) x)))
(smoke-finish)
