(import (scheme base) (scheme read) (srfi 42) (patina compat smoke))
(check-equal "integer ranges exclude the endpoint in either direction"
  '((0 1 2) (5 3 1) () ())
  (list (list-ec (:range i 3) i) (list-ec (:range i 5 0 -2) i)
        (list-ec (:range i 2 2) i) (list-ec (:range i 5 0 2) i)))
(check-equal "nested generators run in depth-first order"
  '((1 0) (2 0) (2 1) (3 0) (3 1) (3 2))
  (list-ec (:range n 1 4) (:range i n) (list n i)))
(check-equal "filters and local bindings compose" '(1 9 25)
  (list-ec (:range i 6) (if (odd? i)) (:let square (* i i)) square))
(check-equal "parallel generators stop at the shortest input" '((a 1) (b 2))
  (list-ec (:parallel (:list x '(a b c)) (:vector y #(1 2))) (list x y)))
(check-equal "list indices continue across concatenated inputs"
  '((a 0) (b 1) (c 2))
  (list-ec (:list x (index i) '(a) '() '(b c)) (list x i)))
(check-equal "string generators retain Unicode and indices"
  '((#\a 0) (#\λ 1) (#\z 2))
  (list-ec (:string c (index i) "aλ" "z") (list c i)))
(check-equal "vector generators concatenate and skip empty vectors" '(a b c)
  (list-ec (:vector x #() #(a b) #() #(c)) x))
(check-equal "a single vector supplies value and index bindings" '((a 0) (b 1))
  (list-ec (:vector x (index i) #(a b)) (list x i)))
(check-equal "vector indices continue across nonempty and empty inputs"
  '((a 0) (b 1) (c 2))
  (list-ec (:vector x (index i) #() #(a b) #() #(c) #()) (list x i)))
(check-equal "indexed empty vectors produce no bindings" '()
  (list-ec (:vector x (index i) #() #()) (list x i)))
(check-equal "dispatched generators recognize lists vectors and ranges"
  '((a b) (c d) (0 1 2))
  (list (list-ec (: x '(a b)) x) (list-ec (: x #(c d)) x)
        (list-ec (: x 3) x)))
(check-equal "while excludes its stop value and until includes it"
  '((0 1 2) (0 1 2 3))
  (list (list-ec (:while (:integers i) (< i 3)) i)
        (list-ec (:until (:integers i) (= i 3)) i)))
(check-equal "port generators stop at EOF without closing the port" '((a 2) #t #t)
  (let ((port (open-input-string "a 2")))
    (let ((items (list-ec (:port x port) x)))
      (list items (eof-object? (read port)) (input-port-open? port)))))
(check-equal "collection comprehensions preserve iteration order"
  '((0 0 1 1) "abc" "aabb" #(1 4 9))
  (list (append-ec (:range i 2) (list i i))
        (string-ec (:char-range c #\a #\c) c)
        (string-append-ec (:list s '("aa" "bb")) s)
        (vector-ec (:range i 1 4) (* i i))))
(check-equal "fixed-length vectors accept an exact element count" #(0 1 2)
  (vector-of-length-ec 3 (:range i 3) i))
(check-error "fixed-length vectors reject too few elements"
  (vector-of-length-ec 3 (:range i 2) i))
(check-error "fixed-length vectors reject too many elements"
  (vector-of-length-ec 2 (:range i 3) i))
(check-equal "numeric reductions and empty identities" '(10 24 1 4 0 1)
  (list (sum-ec (:range i 1 5) i) (product-ec (:range i 1 5) i)
        (min-ec (:list i '(3 1 4)) i) (max-ec (:list i '(3 1 4)) i)
        (sum-ec (:range i 0) i) (product-ec (:range i 0) i)))
(check-equal "fold receives each element before its accumulator" '(3 2 1)
  (fold-ec '() (:range i 1 4) i cons))
(check-equal "fold3 uses its default only for an empty enumeration" '((3 2 1) empty)
  (list (fold3-ec (error "unused default") (:range i 1 4) i list cons)
        (fold3-ec 'empty (:range i 0) i list cons)))
(check-equal "first stops after the first matching binding" '(2 3)
  (let ((visits 0))
    (let ((found (first-ec 'missing (:range i 10)
                   (begin (set! visits (+ visits 1))) (if (>= i 2)) i)))
      (list found visits))))
(check-equal "first and last retain defaults for an empty enumeration"
  '(missing missing 3)
  (list (first-ec 'missing (:range i 0) i) (last-ec 'missing (:range i 0) i)
        (last-ec 'missing (:range i 4) i)))
(check-equal "any and every stop after their deciding result" '(#t 3 #f 3 #f #t)
  (let ((any-calls 0) (every-calls 0))
    (let* ((some (any?-ec (:range i 10)
                   (begin (set! any-calls (+ any-calls 1)) (= i 2))))
           (all (every?-ec (:range i 10)
                  (begin (set! every-calls (+ every-calls 1)) (< i 2)))))
      (list some any-calls all every-calls
            (any?-ec (:range i 0) #t) (every?-ec (:range i 0) #f)))))
(check-equal "generator input expressions are evaluated once" '((0 1 2) 1)
  (let ((calls 0))
    (let ((items (list-ec (:range i (begin (set! calls (+ calls 1)) 3)) i)))
      (list items calls))))
(check-equal "do-ec executes commands in iteration order" '(0 1 2)
  (let ((seen '()))
    (do-ec (:range i 3) (set! seen (cons i seen)))
    (reverse seen)))
(check-equal "generated bindings preserve similarly named user variables"
  '((outer 0 saved) (outer 1 saved))
  (let ((result 'outer) (loop 'saved))
    (list-ec (:range i 2) (list result i loop))))
(check-equal "real ranges support an exact fractional step" '(0 1/2 1 3/2)
  (list-ec (:real-range x 0 2 1/2) x))
(check-error "an integer range rejects a zero step" (list-ec (:range i 0 3 0) i))
(smoke-finish)
