(import (scheme base) (prefix (srfi 29) l:) (prefix (srfi 28) f:)
        (patina compat smoke))
(define saved-language (l:current-language))
(define saved-country (l:current-country))
(l:current-language 'en)
(l:current-country 'gb)
(check-equal "locale accessors reflect explicit settings" '(en gb)
  (list (l:current-language) (l:current-country)))
(l:declare-bundle! '(smoke-localization)
  '((generic . "base") (shared . "base")))
(l:declare-bundle! '(smoke-localization en)
  '((greeting . "Hello ~a") (shared . "English")))
(l:declare-bundle! '(smoke-localization en gb)
  '((shared . "British") (country-only . "tea")))
(check-equal "an exact locale overrides a language template" '("British" "tea")
  (list (l:localized-template 'smoke-localization 'shared)
        (l:localized-template 'smoke-localization 'country-only)))
(check-equal "missing templates fall back through less specific bundles"
  '("Hello ~a" "base")
  (list (l:localized-template 'smoke-localization 'greeting)
        (l:localized-template 'smoke-localization 'generic)))
(l:current-country 'us)
(check-equal "an absent country bundle falls back to the language" "English"
  (l:localized-template 'smoke-localization 'shared))
(l:current-language 'fr)
(check-equal "an absent language bundle falls back to the package" "base"
  (l:localized-template 'smoke-localization 'shared))
(check-equal "unknown packages and templates return false" '(#f #f)
  (list (l:localized-template 'unknown-package 'greeting)
        (l:localized-template 'smoke-localization 'unknown-template)))
(l:current-language 'en)
(l:current-country 'gb)
(l:declare-bundle! '(smoke-localization en gb) '((shared . "replacement")))
(check-equal "redeclaring a bundle replaces its old templates"
  '("replacement" #f "Hello ~a")
  (list (l:localized-template 'smoke-localization 'shared)
        (l:localized-template 'smoke-localization 'country-only)
        (l:localized-template 'smoke-localization 'greeting)))
(l:declare-bundle! '(other-package en gb) '((shared . "other")))
(check-equal "bundle lookup keeps packages separate" '("other" "replacement")
  (list (l:localized-template 'other-package 'shared)
        (l:localized-template 'smoke-localization 'shared)))
(check-equal "a localized template can be formatted by SRFI 28" "Hello Ada"
  (f:format (l:localized-template 'smoke-localization 'greeting) "Ada"))
;; This pinned implementation deliberately has no external bundle store.
(check-equal "unsupported storage leaves declared bundles available"
  '(#f #f "replacement" ())
  (let* ((stored (l:store-bundle! '(smoke-localization en gb)))
         (loaded (l:load-bundle! '(smoke-localization en gb))))
    (list stored loaded (l:localized-template 'smoke-localization 'shared)
          (l:current-locale-details))))
(l:current-language saved-language)
(l:current-country saved-country)
(smoke-finish)
