(import (scheme base) (prefix (srfi 26) s:))
(import (patina compat smoke))

(check-equal "slots preserve argument positions" '(a 1 b 2)
  ((s:cut list 'a <> 'b <>) 1 2))
(check-equal "the procedure position can be a slot" 7
  ((s:cut <> 10 <>) - 3))
(define variadic (s:cut list 'head <...>))
(check-equal "rest slot accepts zero or more arguments" '((head) (head 1 2))
  (list (variadic) (variadic 1 2)))
(define cut-calls 0)
(define delayed
  (s:cut list (begin (set! cut-calls (+ cut-calls 1)) cut-calls) <>))
(check-equal "cut does not evaluate fixed expressions at creation" 0 cut-calls)
(define delayed-first (delayed 'a))
(define delayed-second (delayed 'b))
(check-equal "cut evaluates fixed expressions on every call" '((1 a) (2 b) 2)
  (list delayed-first delayed-second cut-calls))
(define cute-calls 0)
(define captured
  (s:cute list (begin (set! cute-calls (+ cute-calls 1)) cute-calls) <>))
(check-equal "cute evaluates fixed expressions at creation" 1 cute-calls)
(define captured-first (captured 'a))
(define captured-second (captured 'b))
(check-equal "cute reuses captured values" '((1 a) (1 b) 1)
  (list captured-first captured-second cute-calls))
(check-equal "generated slots do not capture user variables" '(outer input tail)
  (let ((x 'outer) (rest-slot 'tail))
    ((s:cut list x <> rest-slot) 'input)))
(check-equal "cute captures the procedure while cut reads it at call time"
  '(3 7)
  (let ((operation +))
    (let ((later (s:cut operation 5 <>))
          (now (s:cute operation 5 <>)))
      (set! operation -)
      (list (later 2) (now 2)))))
(smoke-finish)
