(import (scheme base) (scheme file) (scheme write))
(define kept '())
(let loop ((i 0))
  (when (< i 400)
    (let ((p (open-output-file (string-append "live-" (number->string i) ".txt"))))
      (write-string "x" p)
      (set! kept (cons p kept))
      (loop (+ i 1)))))
(write (length kept)) (newline)
