(import (scheme base) (scheme inexact) (srfi 69) (scheme char))
(define-record-type point (make-point x y) point? (x point-x) (y point-y))
(define pts (let loop ((i 0) (acc '())) (if (= i 20000) acc (loop (+ i 1) (cons (make-point (* i 1.5) (- i)) acc)))))
(define dists (map (lambda (p) (sqrt (+ (* (point-x p) (point-x p)) (* (point-y p) (point-y p))))) pts))
(define total (apply + dists))

(define (iota-like n) (let loop ((i (- n 1)) (acc '())) (if (< i 0) acc (loop (- i 1) (cons i acc)))))
(define ht (make-hash-table equal?))
(let loop ((i 0)) (when (< i 5000) (hash-table-set! ht (number->string i) (make-vector 3 i)) (loop (+ i 1))))
(define big (let loop ((i 0) (acc 1)) (if (= i 200) acc (loop (+ i 1) (* acc 3)))))
(define strs (map (lambda (p) (string-append "p" (number->string (point-y p)))) pts))
(define up (map string-upcase strs))
(define k-uses (let loop ((i 0) (acc 0)) (if (= i 2000) acc (loop (+ i 1) (+ acc (call/cc (lambda (k) (k i))))))))
(define adders (map (lambda (i) (lambda (x) (+ x i))) (iota-like 5000)))
