(define (f) (reverse '(1 2)))
(define (g) (car '(1 2)))
(write (list (f) (g))) (newline)
(define (reverse x) 'mine)
(define (car x) 'mycar)
(write (list (f) (g))) (newline)
(define (h) (later 1))
(define (later x) (list 'later x))
(write (h)) (newline)
