(library (counter) (export count bump! get-count) (import (chezscheme))
  (define count 0) (define (bump!) (set! count (+ count 1))) (define (get-count) count))
(import (counter))
(define (show) count)
(bump!)
(write (list 'a (show) count (get-count))) (newline)
(define count 100)
(bump!)
(write (list 'b (show) count (get-count))) (newline)
(define (f2) (zork))
(define (zork) 'z)
(write (f2)) (newline)
(define (later-import) (get-count2))
(library (counter2) (export get-count2) (import (chezscheme)) (define (get-count2) 'c2))
(import (counter2))
(write (guard (e (#t (list 'error (condition-message e)))) (later-import))) (newline)
