(library (counter) (export count) (import (chezscheme)) (define count 0))
(import (counter))
(define (show) count)
(write (list 'a (show) count)) (newline)
(define count 100)
(write (list 'b (show) count)) (newline)
(write (guard (e (#t (list 'error (condition-message e)))) (eval '(set! count 5)) count)) (newline)
(define base-env (environment '(rnrs)))
(write (guard (e (#t (list 'error (condition-message e) (condition-irritants e)))) (eval '(define zz 1) base-env))) (newline)
(write (guard (e (#t (list 'error (condition-message e) (condition-irritants e)))) (eval '(set! car cdr) base-env))) (newline)
