(import (scheme base) (scheme write) (scheme eval) (scheme repl))
(define e (environment '(scheme base)))
(write (guard (x (#t (list 'error (error-object-message x)))) (eval '(define zz 1) e) (eval 'zz e))) (newline)
(write (guard (x (#t (list 'error (error-object-message x)))) (eval '(set! car cdr) e) (eval '(car '(1 2)) e))) (newline)
(write (car '(1 2))) (newline)
(write (guard (x (#t (list 'error (error-object-message x)))) (eval '(define car cdr) e) (eval '(car '(1 2)) e))) (newline)
(write (car '(1 2))) (newline)
(eval '(define (ie-f) (list-copy '(1))) (interaction-environment))
(eval '(define (list-copy x) 'mine) (interaction-environment))
(write (eval '(ie-f) (interaction-environment))) (newline)
