(import (scheme base) (scheme write) (counter))
(define (show) count)
(bump!)
(write (list 'a (show) count (get-count))) (newline)
(define count 100)
(bump!)
(write (list 'b (show) count (get-count))) (newline)
(set! count 200)
(write (list 'c (show) count (get-count))) (newline)
