(define (now-ms) (let ((t (current-time 'time-monotonic))) (+ (* 1000.0 (time-second t)) (/ (time-nanosecond t) 1e6))))
(define (gc-ms)
  (let loop ((i 0) (total 0.0))
    (if (= i 100)
        (/ total 100)
        (let ((t0 (now-ms)))
          (collect (collect-maximum-generation))
          (loop (+ i 1) (+ total (- (now-ms) t0)))))))
(display (list 'before (gc-ms))) (newline)
(length (make-list 2000000 0))
(display (list 'after (gc-ms))) (newline)
