(import (scheme base) (scheme write) (scheme time) (only (gauche base) gc))
(define (now-ms) (/ (* 1000.0 (current-jiffy)) (jiffies-per-second)))
(define (gc-ms)
  (let loop ((i 0) (total 0.0))
    (if (= i 100)
        (/ total 100)
        (let ((t0 (now-ms)))
          (gc)
          (loop (+ i 1) (+ total (- (now-ms) t0)))))))
(display (list 'before (gc-ms))) (newline)
(length (make-list 2000000 0))
(display (list 'after (gc-ms))) (newline)
