(import (scheme base) (scheme write) (scheme time) (scheme process-context) (patina debug))
(define n (string->number (cadr (command-line))))
(define (now-ms) (/ (* 1000.0 (current-jiffy)) (jiffies-per-second)))
(define (collections) (cdr (assq 'collections (gc-stats))))
(define (gc-ms)                       ; mean wall time of 20 forced collections
  (let ((c0 (collections)))
    (let loop ((i 0) (total 0.0))
      (if (= i 20)
          (begin (display (/ total 20)) (display " ms (")
                 (display (- (collections) c0)) (display " collections)") (newline))
          (let ((t0 (now-ms)))
            (gc) (cons 1 2)           ; (gc) collects at the next safe point
            (loop (+ i 1) (+ total (- (now-ms) t0))))))))
(display "before the peak: ") (gc-ms)
(define big (make-list n 0))
(set! big #f)
(display "after the drop:  ") (gc-ms)
(display "after the drop:  ") (gc-ms)
(write (gc-stats)) (newline)
