(define n (string->number (cadr (command-line))))
(define (build n) (let loop ((i 0) (acc (quote ()))) (if (= i n) acc (loop (+ i 1) (cons (vector i i) acc))))) (length (build n))
(collect (collect-maximum-generation)) (collect (collect-maximum-generation))
(display "idle") (newline) (flush-output-port (current-output-port))
(read-char)
