(import (scheme base) (scheme write) (patina debug))
(define (free) (gc) (cons 1 2) (cdr (assq 'free-pairs (gc-stats))))
(display (free)) (newline)
(define big (make-list 200000 0))
(display (free)) (newline)
(set! big #f)
(display (free)) (newline)
(display (free)) (newline)
(define (build n) (let loop ((i 0) (acc '())) (if (= i n) acc (loop (+ i 1) (cons i acc)))))
(define big2 (build 200000))
(set! big2 #f)
(display (free)) (newline)
(let ((x (make-list 200000 0))) (length x))
(display (free)) (newline)
