(import (scheme base) (scheme write) (patina debug))
(define (free) (gc) (cons 1 2) (cdr (assq 'free-pairs (gc-stats))))
(define (pairs) (cdr (assq 'pairs (gc-stats))))
(display (list 'start (free) (pairs))) (newline)
(define big #f)
(set! big (make-list 200000 0))
(display (list 'set (free) (pairs))) (newline)
(set! big #f)
(display (list 'dropped (free) (pairs))) (newline)
(set! big 1)
(display (list 'set-again (free) (pairs))) (newline)
(define v (vector (make-list 200000 0)))
(vector-set! v 0 #f)
(display (list 'vector-drop (free) (pairs))) (newline)
