(import (scheme base) (scheme write) (patina debug))
(define (free) (gc) (cons 1 2) (cdr (assq 'free-pairs (gc-stats))))
(define (pairs) (cdr (assq 'pairs (gc-stats))))
(define (build n) (let loop ((i 0) (acc '())) (if (= i n) acc (loop (+ i 1) (cons (vector i i) acc)))))
(display (list 'start (free) (pairs))) (newline)
(define big (build 200000))
(display (list 'built (free) (pairs))) (newline)
(set! big #f)
(display (list 'dropped (free) (pairs))) (newline)
(display (list 'dropped (free) (pairs))) (newline)
