(import (scheme base) (scheme write) (patina debug))
(define (free) (gc) (cons 1 2) (cdr (assq 'free-pairs (gc-stats))))
(define (build n) (let loop ((i 0) (acc '())) (if (= i n) acc (loop (+ i 1) (cons i acc)))))
(define big (build 100000))
(set! big #f)
(display (list 'dropped (free))) (newline)
(build 10)
(display (list 'after-build-10 (free))) (newline)
(define big (build 100000))
(set! big #f)
(display (list 'dropped2 (free))) (newline)
(make-list 10 0)
(display (list 'after-make-list (free))) (newline)
(vector 1 2 3)
(display (list 'after-vector (free))) (newline)
(define x (list 1 2 3))
(display (list 'after-define-list (free))) (newline)
(define y (build 5))
(display (list 'after-define-build5 (free))) (newline)
