(import (scheme base) (scheme write) (patina debug))
(define (free) (gc) (cons 1 2) (cdr (assq 'free-pairs (gc-stats))))
(define (build n) (let loop ((i 0) (acc '())) (if (= i n) acc (loop (+ i 1) (cons i acc)))))
(define big (build 100000))
(set! big #f)
(display (list 'dropped (free))) (newline)
(define z 0)
(display (list 'after-define-z (free))) (newline)
(define big2 #f)
(set! big2 (build 100000))
(set! big2 #f)
(display (list 'dropped-set (free))) (newline)
(set! z 1)
(display (list 'after-set-z (free))) (newline)
(define w (cons 1 2))
(display (list 'after-define-w (free))) (newline)
