(import (scheme base) (scheme write))
;; mutable binary search tree of records (old interior nodes get young children)
(define-record-type node (mk-node key val left right) node? (key n-key) (val n-val set-n-val!) (left n-left set-n-left!) (right n-right set-n-right!))
(define root (mk-node 50000 0 #f #f))
(define (insert! t k v)
  (cond ((= k (n-key t)) (set-n-val! t v))
        ((< k (n-key t)) (if (n-left t) (insert! (n-left t) k v) (set-n-left! t (mk-node k v #f #f))))
        (else (if (n-right t) (insert! (n-right t) k v) (set-n-right! t (mk-node k v #f #f))))))
(define (rnd s) (modulo (+ (* s 1103515245) 12345) 2147483648))
(let loop ((i 0) (s 7))
  (when (< i 60000)
    (insert! root (modulo s 100000) (list i))
    (loop (+ i 1) (rnd s))))
(display (n-key root)) (newline)
