(import (scheme base) (scheme write))
;; FIFO queue via tail set-cdr!, long-lived queue header record
(define-record-type queue (mk-queue head tail n) queue? (head q-head set-q-head!) (tail q-tail set-q-tail!) (n q-n set-q-n!))
(define q (mk-queue '() '() 0))
(define (enq! q x)
  (let ((cell (list x)))
    (if (null? (q-head q)) (begin (set-q-head! q cell) (set-q-tail! q cell))
        (begin (set-cdr! (q-tail q) cell) (set-q-tail! q cell)))
    (set-q-n! q (+ 1 (q-n q)))))
(define (deq! q)
  (let ((c (q-head q))) (set-q-head! q (cdr c)) (set-q-n! q (- (q-n q) 1)) (car c)))
(let loop ((i 0) (sum 0))
  (if (< i 300000)
      (begin (enq! q (cons i i)) (enq! q (list i))
             (loop (+ i 1) (+ sum (car (deq! q)))))
      (begin (display sum) (newline))))
