//! A generated matrix of macro-hygiene shapes, scored against two reference
//! implementations.
//!
//! Hygiene defects in this repo have been found one at a time, by accident —
//! a corpus package tripping over one, a review noticing another. That is how
//! triage families 33–38 arrived, and it has a failure mode: a fix aimed at
//! one shape silently breaks the *opposite* shape, because nothing enumerates
//! the opposite shape. PR #133 and PR #138 were both closed for exactly that,
//! after passing every gate in the repo including 1226/1226 on the chibi
//! suite.
//!
//! So this file does not test a defect. It enumerates a **space** — the cross
//! product of how a use site binds a name, where the macro that mentions that
//! name is defined, and whether the template reads or assigns it — and pins
//! what each backend answers for every point in it. A fix that improves one
//! row and breaks another cannot pass.
//!
//! # The oracle
//!
//! The `correct` column is what **chibi 0.12 and Racket 9.3 both** answer,
//! measured 2026-08-28. They agree on all 28 shapes, which is why a single
//! column can stand for "correct". Where they say a program is *ill-formed*
//! the column is [`ERROR`].
//!
//! Two independent implementations agreeing is the strongest oracle available
//! here; R7RS §4.3.2 states referential transparency but does not work these
//! shapes out.
//!
//! # Reading a row
//!
//! Each row records `correct`, and what the VM and the tree-walker answer
//! **today**. A row where an actual differs from `correct` is a live defect,
//! pinned so it cannot drift silently. [`shapes_score_as_recorded`] asserts
//! every actual, so:
//!
//! - **fix a defect** → its row goes red with `left` = the new (correct)
//!   answer. Update that row's `vm`/`tw` to match and the count in
//!   [`the_defect_count_is_what_the_roadmap_says`].
//! - **break a working shape** → its row goes red too. That is the direction
//!   #138 went, undetected.
//!
//! # Adding axes
//!
//! The axes here are deliberately the cheap ones. The shapes this file does
//! *not* cover yet, roughly in order of how much they are worth: a macro
//! generated by another macro; a macro imported across a library boundary;
//! expansion nested more than one level; ellipsis depth greater than one;
//! `define-record-type` and other derived binding forms; and literals in the
//! pattern. Each is a new `Site` or `Binder`, not a new file.

mod common;

use common::{
    eval_program_tree_walker, eval_program_vm, try_eval_program_tree_walker, try_eval_program_vm,
};

const TRIAGE: &str = "scheme_tests/reports/larceny_triage.md";

/// The `correct` value for a program both reference implementations reject.
const ERROR: &str = "<error>";

/// Where the macro that mentions `X` is defined, relative to the binding of
/// `X` at the use site.
///
/// This is the axis that decides which way hygiene must point, and the axis
/// PR #138 got half right: a template's `X` means the binding visible **where
/// the macro was written**, so a macro defined outside must reach *past* a
/// same-named use-site binder, and one defined inside must reach *into* it.
#[derive(Clone, Copy, PartialEq)]
enum Site {
    /// Top level, so the template's `X` is the global.
    Outside,
    /// Inside the binding form, so the template's `X` is the binder's.
    Inside,
}

/// What the template does with `X`.
#[derive(Clone, Copy, PartialEq)]
enum Action {
    Read,
    Write,
}

/// One point in the space.
struct Shape {
    /// How the use site binds `X`. Keyed into [`binder_expr`].
    binder: &'static str,
    site: Site,
    action: Action,
    /// What chibi 0.12 and Racket 9.3 both answer.
    correct: &'static str,
    /// What the VM answers today.
    vm: &'static str,
    /// What the tree-walker answers today.
    tw: &'static str,
    /// The defect this row is a face of, or `""` when the row is correct.
    family: &'static str,
}

/// Wrap `body` in a binding of `X` to 5.
///
/// Every form R7RS gives for binding a variable at a use site, since the
/// question "does a template's reference get captured" is about the *binding*,
/// not about which surface form produced it — and the answer turned out to
/// differ between them (an internal define behaves unlike a `let`).
fn binder_expr(binder: &str, body: &str) -> String {
    match binder {
        "lambda-param" => format!("((lambda (X) {body}) 5)"),
        "let" => format!("(let ((X 5)) {body})"),
        "let*" => format!("(let* ((X 5)) {body})"),
        "letrec" => format!("(letrec ((X 5)) {body})"),
        "named-let" => format!("(let lp ((X 5)) {body})"),
        "internal-def" => format!("((lambda () (define X 5) {body}))"),
        "do-var" => format!("(do ((X 5 X)) (#t {body}))"),
        other => panic!("unknown binder {other}"),
    }
}

/// Build the program for one shape.
///
/// Both the inner result and the global are observed, because a capture shows
/// up in either one depending on direction, and reporting only one hides half
/// the defect. Order is forced through `(define r …)` rather than written as
/// `(list (f) X)`: R7RS §4.1.3 leaves operand order unspecified, and a
/// version of this matrix that did not force it read chibi's right-to-left
/// evaluation as a divergence.
fn program(shape: &Shape) -> String {
    let template = match shape.action {
        Action::Read => "X",
        Action::Write => "(set! X 99)",
    };
    let macro_def = format!("(define-syntax m (syntax-rules () ((m) {template})))");
    // A write has to be observed after it happens, so the body yields `X`.
    let body = match shape.action {
        Action::Read => "(m)".to_string(),
        Action::Write => "(begin (m) X)".to_string(),
    };
    let inner = match shape.site {
        Site::Outside => binder_expr(shape.binder, &body),
        Site::Inside => binder_expr(shape.binder, &format!("{macro_def} {body}")),
    };
    match shape.site {
        Site::Outside => format!("(define X 'global)\n{macro_def}\n(define r {inner})\n(list r X)"),
        Site::Inside => format!("(define X 'global)\n(define r {inner})\n(list r X)"),
    }
}

/// Every shape, with both backends' current answers.
///
/// Measured 2026-08-28 on `971c090f`. The `family` column names the defect a
/// wrong row is a face of, so the seven `outside/read` rows read as one bug
/// with seven surfaces rather than seven bugs.
#[rustfmt::skip]
const MATRIX: &[Shape] = &[
    // ---- macro defined OUTSIDE, template READS X ------------------------
    // The template's `X` is the global; a use-site binder must not capture
    // it. The tree-walker captures on every binder — family 36, and this is
    // its true extent. The VM captures only through an internal define.
    Shape { binder: "lambda-param", site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(5 global)", family: "36" },
    Shape { binder: "let",          site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(5 global)", family: "36" },
    Shape { binder: "let*",         site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(5 global)", family: "36" },
    Shape { binder: "letrec",       site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(5 global)", family: "36" },
    Shape { binder: "named-let",    site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(5 global)", family: "36" },
    Shape { binder: "do-var",       site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(5 global)", family: "36" },
    // The one binder the VM gets wrong too: an internal define reaches the
    // runtime with an empty scope set on both backends.
    Shape { binder: "internal-def", site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(5 global)", tw: "(5 global)", family: "36" },

    // ---- macro defined OUTSIDE, template WRITES X -----------------------
    // The write must reach past the use-site binder to the global. These are
    // the rows PR #138 broke while every other gate stayed green; they are
    // correct today and are a regression guard, not a defect pin.
    Shape { binder: "lambda-param", site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    Shape { binder: "let",          site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    Shape { binder: "let*",         site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    Shape { binder: "letrec",       site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    Shape { binder: "named-let",    site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    Shape { binder: "do-var",       site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    // The VM captures the internal define and never touches the global.
    Shape { binder: "internal-def", site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(99 global)", tw: "(5 99)", family: "36" },

    // ---- macro defined INSIDE, template READS X -------------------------
    // The template's `X` *is* the binder's, so reading it must yield 5.
    // Everything passes: reaching inward is the direction both backends have.
    Shape { binder: "lambda-param", site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: "let",          site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: "let*",         site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: "letrec",       site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: "named-let",    site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: "internal-def", site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    // Both oracles reject a `define-syntax` in a `do` result clause — it is
    // not a definition context (R7RS §5.3.2). Patina accepts it. Not a
    // hygiene defect; found by this matrix and unrecorded before it.
    Shape { binder: "do-var",       site: Site::Inside, action: Action::Read,
            correct: ERROR, vm: "(5 global)", tw: "(5 global)", family: "def-context" },

    // ---- macro defined INSIDE, template WRITES X ------------------------
    // The write must land on the binder, leaving the global alone.
    Shape { binder: "lambda-param", site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    Shape { binder: "let",          site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    Shape { binder: "let*",         site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    Shape { binder: "letrec",       site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    Shape { binder: "named-let",    site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    // The tree-walker's scoped write finds no candidate — an internal define
    // has no scopes — and falls back at the *root*, so it assigns the global
    // and leaves the binder at 5. Triage family 38's remaining half.
    Shape { binder: "internal-def", site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(5 99)", family: "38" },
    Shape { binder: "do-var",       site: Site::Inside, action: Action::Write,
            correct: ERROR, vm: "(99 global)", tw: "(99 global)", family: "def-context" },
];

impl Shape {
    fn name(&self) -> String {
        let site = if self.site == Site::Outside {
            "outside"
        } else {
            "inside"
        };
        let action = if self.action == Action::Read {
            "read"
        } else {
            "write"
        };
        format!("{}/{site}/{action}", self.binder)
    }
}

/// Run one shape on one backend, rendering a rejection as [`ERROR`].
fn answer(code: &str, vm: bool) -> String {
    let ok = if vm {
        try_eval_program_vm(code)
    } else {
        try_eval_program_tree_walker(code)
    };
    ok.unwrap_or_else(|_| ERROR.to_string())
}

/// Every shape answers what the table says it answers, on both backends.
///
/// The whole point is that this fails in *both* directions: fixing a defect
/// turns its row red just as breaking a working shape does. A red row is never
/// "just update the table" — read which direction it moved first.
#[test]
fn shapes_score_as_recorded() {
    let mut moved = Vec::new();
    for shape in MATRIX {
        let code = program(shape);
        for (backend, recorded) in [("vm", shape.vm), ("tree-walker", shape.tw)] {
            let got = answer(&code, backend == "vm");
            if got != recorded {
                let direction = if got == shape.correct {
                    "FIXED — it now matches chibi and Racket"
                } else if recorded == shape.correct {
                    "REGRESSED — it used to match chibi and Racket"
                } else {
                    "changed, and is still wrong"
                };
                moved.push(format!(
                    "  {} [{backend}] {direction}\n    recorded {recorded}\n    got      {got}\n\
                     \x20   correct  {}\n    program:\n{}",
                    shape.name(),
                    shape.correct,
                    code.lines()
                        .map(|l| format!("      {l}"))
                        .collect::<Vec<_>>()
                        .join("\n")
                ));
            }
        }
    }
    assert!(
        moved.is_empty(),
        "{} hygiene shape(s) no longer answer what the matrix records.\n\n{}\n\n\
         Update the row(s) in MATRIX and the count in \
         `the_defect_count_is_what_the_roadmap_says`, then say which family \
         moved in {TRIAGE}.",
        moved.len(),
        moved.join("\n\n")
    );
}

/// How many shapes each backend gets wrong, asserted as a number.
///
/// A count is the thing the chibi suite cannot give: it has read 1226/1226 on
/// both backends through every defect in this table. This number can only move
/// deliberately.
#[test]
fn the_defect_count_is_what_the_roadmap_says() {
    let wrong = |pick: fn(&Shape) -> &'static str| {
        MATRIX
            .iter()
            .filter(|s| pick(s) != s.correct)
            .map(|s| s.name())
            .collect::<Vec<_>>()
    };
    let vm = wrong(|s| s.vm);
    let tw = wrong(|s| s.tw);

    // VM: an internal define captures a template's reference either way
    // (family 36), plus the two `do` result-clause rows that are a
    // definition-context defect rather than a hygiene one.
    assert_eq!(vm.len(), 4, "VM shapes wrong: {vm:?}");
    // Tree-walker: the same two `do` rows, family 36 on all seven binders in
    // the read direction, and family 38's fallback on the internal define.
    assert_eq!(tw.len(), 10, "tree-walker shapes wrong: {tw:?}");

    // Every wrong row names the family it belongs to, so the table doubles as
    // the index from defect to surface count.
    for shape in MATRIX {
        let correct = shape.vm == shape.correct && shape.tw == shape.correct;
        assert_eq!(
            correct,
            shape.family.is_empty(),
            "{}: `family` must be set exactly on rows some backend gets wrong",
            shape.name()
        );
    }
}

/// Family 36 is one defect with eight surfaces, not eight defects.
///
/// Recorded as a test rather than as prose because the count is what makes the
/// fix's acceptance criterion checkable: all seven go green together, or the
/// fix is addressing a symptom.
#[test]
fn family_36_has_eight_surfaces() {
    let faces: Vec<String> = MATRIX
        .iter()
        .filter(|s| s.family == "36")
        .map(|s| s.name())
        .collect();
    assert_eq!(faces.len(), 8, "{faces:?}");
    // Seven are the read direction, one per binder; the eighth is the write
    // direction through an internal define, which only the VM gets wrong.
    assert_eq!(
        faces
            .iter()
            .filter(|n| n.ends_with("/outside/read"))
            .count(),
        7,
        "{faces:?}"
    );
}

/// The two `do` rows are not a hygiene defect and should not be fixed as one.
///
/// R7RS §5.3.2 admits definitions in a `⟨body⟩`; a `do` result clause is a
/// sequence of expressions, not a body. chibi and Racket both reject it and
/// Patina runs it. Separated from the hygiene rows because a reader scanning
/// this file for "what is wrong with our macros" should not count it.
#[test]
fn a_do_result_clause_is_not_a_definition_context() {
    let code = "(define X 'global)\n\
                (define r (do ((X 5 X)) (#t (define-syntax m (syntax-rules () ((m) X))) (m))))\n\
                (list r X)";
    // Pinned as accepted, which is the defect. When Patina starts rejecting
    // this, both of these turn red and the two `do` rows in MATRIX get
    // `vm`/`tw` set to ERROR.
    assert_eq!(eval_program_vm(code), "(5 global)");
    assert_eq!(eval_program_tree_walker(code), "(5 global)");
}
