//! A generated matrix of macro-hygiene shapes, scored against two reference
//! implementations.
//!
//! Hygiene defects in this repo have been found one at a time, by accident —
//! a corpus package tripping over one, a review noticing another. That is how
//! triage families 33–38 arrived, and it has a failure mode: a fix aimed at
//! one shape silently breaks the *opposite* shape, because nothing enumerates
//! the opposite shape. PR #133 and PR #138 were both closed for exactly that,
//! after passing every gate in the repo including 1226/1226 on the chibi
//! suite.
//!
//! So this file does not test a defect. It enumerates a **space** — the cross
//! product of how a use site binds a name, where the macro that mentions that
//! name is defined, and whether the template reads or assigns it — and pins
//! what each backend answers for every point in it. A fix that improves one
//! row and breaks another cannot pass.
//!
//! There are two tables. [`MATRIX`] is that cross product: 28 shapes that
//! hold the macro fixed — hand-written, in the program — and move the use
//! site's binder. [`MADE`] holds the binder simple and moves the *macro*: 109
//! shapes over how it came to exist (written, or generated by another macro),
//! where (the program, or a library that keeps `X` private), what its
//! template does with `X`, what the use site itself means by `X`, and — for
//! 18 of them — whether the two `X`s hold equal values while the macro is
//! expanded ([`Values`]). In 40 of them the generator also *introduces* the
//! `X` its macro mentions, so the binder is a macro-introduced global (the
//! `Introducing` makers). Both tables are scored by the same tests.
//!
//! # The oracle
//!
//! The `correct` column is what **chibi 0.12 and Racket 9.3 both** answer,
//! measured 2026-08-28. They agree on all 28 shapes, which is why a single
//! column can stand for "correct". Patina got **9** of the 28 wrong when
//! first measured — two on the VM, eight on the tree-walker, one of them on
//! both. The six ordinary-binder read rows went green together when the
//! by-name fallback stopped resurrecting a rejected binding (the triage
//! queue's step 1); the three internal-define rows went green together when
//! internal defines started carrying the scopes of the body they stand in to
//! the runtime (step 2). **All 28 now match the oracles.** The matrix stays:
//! every row is a regression guard now, in both directions, which is the
//! guard PR #133 and PR #138 did not have.
//!
//! Every shape is a program both oracles *accept*: see the note in
//! **Adding axes** about why a row pinned at "both reject it" is not coverage.
//! The one shape Patina accepts and both oracles reject has its own test,
//! [`a_do_result_clause_is_not_a_definition_context`], because it is a
//! definition-context defect rather than a hygiene one and should not be
//! counted with these.
//!
//! Two independent implementations agreeing is the strongest oracle available
//! here; R7RS §4.3.2 states referential transparency but does not work these
//! shapes out.
//!
//! [`MADE`]'s `correct` column is what **chibi 0.12 and Gauche 0.9.15 both**
//! answer, measured 2026-09-18 from [`dump_programs`]'s output; they agree on
//! all 45. Racket was not available for that measurement and is *not* claimed
//! for those rows. The same run re-measured [`MATRIX`] under both, and Gauche
//! agrees with the recorded column on all 28. Patina got **18** of the 45
//! wrong, on both backends — exactly the generated-macro rows across a
//! library boundary, with both controls (generated in one program;
//! hand-written across a library) clean. That is triage family 47, issue
//! #402, and all eighteen went green together.
//!
//! The 18 [`Values::Equal`] rows were measured the same way on 2026-09-19,
//! and chibi and Gauche agree on all of them. Patina got the **6** across a
//! library with a top-level `X` at the use site wrong, on both backends,
//! hand-written macros included — #407, a value comparison where a question
//! about the binding was needed — and they went green together when the
//! relinker started asking it. The 12 others were never wrong and are the
//! control: one program, where nothing is relinked, and a `let`-bound `X`,
//! which the by-name view being compared does not see.
//!
//! The 40 `Introducing` rows, same method, 2026-09-19, and chibi and Gauche
//! agree on all of them. Patina got **12** wrong on both backends — across a
//! library, with something else of the spelling at the definition site: a
//! plain `X`, or a second run of the generator. Eight of those were the loud
//! `unbound variable: X`; the four with a top-level `X` at the use site were
//! silent, the template reading and assigning the *program's*. That is #408:
//! the relinker aliased by name, and the name does not identify such a
//! definition. They went green together when the alias started naming the
//! binding the mention's scopes select. 18 others are the control — the
//! introduced `X` alone of its spelling, where the name is enough, and
//! everything in one program, where nothing is relinked.
//!
//! The last **10**, `introducing-together`, put the definer's two runs in one
//! top-level form, and were wrong on the **VM alone** — in one program as
//! well as across a library, and every one of them silently: the first run's
//! macro read and assigned the second run's `X`. Review of #408 found it. The
//! VM kept one record per *spelling* per form of the definitions it renamed,
//! so the first run's identity was never recorded (`RenameEnv::global_aliases`
//! in patina-vm). Two runs in two forms never showed it, which is what
//! `introducing-twice` had been measuring.
//!
//! The **6** `redefined` rows ([`UseSite::Redefined`]), same method, same
//! day, chibi and Gauche agreeing on all of them: the program imports `X`,
//! expands `m`, and *then* defines an `X` of its own. All six were wrong on
//! both backends, silently — a read answered `(use use)` and a write landed
//! on the program's `X` — and written macros as much as generated ones. That
//! is #438: where both sides reach one binding the relinker left the
//! template's reference as a bare global name, which is looked up when it
//! runs. It is bound to the import's location now.
//!
//! # Reading a row
//!
//! Each row records `correct`, and what the VM and the tree-walker answer
//! **today**. A row where an actual differs from `correct` is a live defect,
//! pinned so it cannot drift silently. [`shapes_score_as_recorded`] asserts
//! every actual, so:
//!
//! - **fix a defect** → its row goes red with `left` = the new (correct)
//!   answer. Update that row's `vm`/`tw` to match and the count in
//!   [`the_defect_count_is_what_the_roadmap_says`].
//! - **break a working shape** → its row goes red too. That is the direction
//!   #138 went, undetected.
//!
//! # Adding axes
//!
//! The axes here are deliberately the cheap ones. Two that this list used to
//! open with are [`MADE`]'s now — a macro generated by another macro, and a
//! macro imported across a library boundary — and each had produced a
//! both-backend defect found somewhere other than this file before it was an
//! axis: triage family 13 through `(r6rs enums)` (a pattern variable under
//! `quote`, substituted in a hand-written macro and not in a generated one;
//! pinned in `tests/scheme/expansion/syntax-rules.scm`), and family 47 through
//! the compat corpus's `chibi-tar`, which was both axes at once. The shapes
//! this file does *not* cover yet, roughly in order of how much they are
//! worth: expansion nested more than two levels; ellipsis depth greater than
//! one;
//! `define-record-type` and other derived binding forms; literals in the
//! pattern; and the *refusal* half of a **macro-introduced global** as the
//! binder — the family-40 shapes (the last section of
//! `tests/scheme/expansion/hygiene.scm`; the last three rows of
//! `larceny_families.rs` before #193 Phase 1 deleted it), where a reference
//! from a *different* expansion must not reach the definition, the two
//! backends currently diverge, and the tree-walker is the one chibi agrees
//! with (#427). The half where the reference *should* reach it is
//! [`MADE`]'s since #408: the `Introducing` makers, whose generated macro
//! mentions a definition its own generator introduced, in one program and
//! across a library. Each is a new `Site`, `Binder`, `Maker` or the like, not
//! a new file.
//!
//! **An axis must move one thing.** `Site::Inside` originally placed the
//! macro definition wherever the binder's body went, which for `do` is the
//! result clause — a sequence of expressions, not a `⟨body⟩` (R7RS §5.3.2).
//! That moved the definition *and* made the program ill-formed, so both
//! oracles rejected it, two of the 28 cells measured a definition-context
//! defect instead of hygiene, and `do-var` had no inside-direction hygiene
//! coverage at all. Agreement on *rejection* is not agreement on an answer.
//! The definition-context defect has its own test; the matrix supplies a
//! `(let () …)` so the axis moves one thing again.

mod common;

use common::{
    eval_program_tree_walker, eval_program_vm, try_eval_program_tree_walker, try_eval_program_vm,
};

const TRIAGE: &str = "scheme_tests/reports/larceny_triage.md";

/// The `correct` value for a program both reference implementations reject.
const ERROR: &str = "<error>";

/// Where the macro that mentions `X` is defined, relative to the binding of
/// `X` at the use site.
///
/// This is the axis that decides which way hygiene must point, and the axis
/// PR #138 got half right: a template's `X` means the binding visible **where
/// the macro was written**, so a macro defined outside must reach *past* a
/// same-named use-site binder, and one defined inside must reach *into* it.
#[derive(Clone, Copy, PartialEq)]
enum Site {
    /// Top level, so the template's `X` is the global.
    Outside,
    /// Inside the binding form, so the template's `X` is the binder's.
    Inside,
}

/// What the template does with `X`.
#[derive(Clone, Copy, PartialEq)]
enum Action {
    Read,
    Write,
}

/// How the use site binds `X`.
///
/// An enum rather than a string key, so a typo is a compile error as it
/// already is for [`Site`] and [`Action`]. As a `&str` matched with a
/// `panic!` default, a misspelled binder still produced a row that two of the
/// tests counted as valid before the third panicked on it.
#[derive(Clone, Copy, PartialEq)]
enum Binder {
    LambdaParam,
    Let,
    LetStar,
    Letrec,
    NamedLet,
    InternalDef,
    DoVar,
}

impl Binder {
    fn name(self) -> &'static str {
        match self {
            Binder::LambdaParam => "lambda-param",
            Binder::Let => "let",
            Binder::LetStar => "let*",
            Binder::Letrec => "letrec",
            Binder::NamedLet => "named-let",
            Binder::InternalDef => "internal-def",
            Binder::DoVar => "do-var",
        }
    }
}

/// One point in the space.
struct Shape {
    /// How the use site binds `X`.
    binder: Binder,
    site: Site,
    action: Action,
    /// What chibi 0.12 and Racket 9.3 both answer.
    correct: &'static str,
    /// What the VM answers today.
    vm: &'static str,
    /// What the tree-walker answers today.
    tw: &'static str,
    /// The defect this row is a face of, or `""` when the row is correct.
    family: &'static str,
}

/// Wrap `body` in a binding of `X` to 5.
///
/// Every form R7RS gives for binding a variable at a use site, since the
/// question "does a template's reference get captured" is about the *binding*,
/// not about which surface form produced it — and the answer turned out to
/// differ between them (an internal define behaves unlike a `let`).
fn binder_expr(binder: Binder, body: &str) -> String {
    match binder {
        Binder::LambdaParam => format!("((lambda (X) {body}) 5)"),
        Binder::Let => format!("(let ((X 5)) {body})"),
        Binder::LetStar => format!("(let* ((X 5)) {body})"),
        Binder::Letrec => format!("(letrec ((X 5)) {body})"),
        Binder::NamedLet => format!("(let lp ((X 5)) {body})"),
        Binder::InternalDef => format!("((lambda () (define X 5) {body}))"),
        Binder::DoVar => format!("(do ((X 5 X)) (#t {body}))"),
    }
}

/// Build the program for one shape.
///
/// Both the inner result and the global are observed, because a capture shows
/// up in either one depending on direction, and reporting only one hides half
/// the defect. Order is forced through `(define r …)` rather than written as
/// `(list (f) X)`: R7RS §4.1.3 leaves operand order unspecified, and a
/// version of this matrix that did not force it read chibi's right-to-left
/// evaluation as a divergence.
fn program(shape: &Shape) -> String {
    let template = match shape.action {
        Action::Read => "X",
        Action::Write => "(set! X 99)",
    };
    let macro_def = format!("(define-syntax m (syntax-rules () ((m) {template})))");
    // A write has to be observed after it happens, so the body yields `X`.
    let body = match shape.action {
        Action::Read => "(m)".to_string(),
        Action::Write => "(begin (m) X)".to_string(),
    };
    let inner = match shape.site {
        Site::Outside => binder_expr(shape.binder, &body),
        // `Site::Inside` must move the macro definition and nothing else. A
        // `do` result clause is a sequence of expressions, not a `⟨body⟩`
        // (R7RS §5.3.2), so putting a `define-syntax` there changes *two*
        // things and both oracles reject the program — which cost `do-var`
        // its inside-direction hygiene coverage entirely, two of 28 cells
        // measuring a definition-context defect instead. `(let () …)` supplies
        // the definition context without binding anything, so the axis moves
        // one thing again. The definition-context defect keeps its own test.
        Site::Inside if shape.binder == Binder::DoVar => {
            binder_expr(shape.binder, &format!("(let () {macro_def} {body})"))
        }
        Site::Inside => binder_expr(shape.binder, &format!("{macro_def} {body}")),
    };
    match shape.site {
        Site::Outside => format!("(define X 'global)\n{macro_def}\n(define r {inner})\n(list r X)"),
        Site::Inside => format!("(define X 'global)\n(define r {inner})\n(list r X)"),
    }
}

/// Every shape, with both backends' current answers.
///
/// First measured 2026-08-28 on `971c090f` (nine rows wrong); the six
/// ordinary-binder `outside/read` rows were re-measured green together when
/// the by-name fallback stopped resurrecting a rejected binding. The
/// `family` column names the defect a wrong row is a face of, and is empty
/// on a row both backends answer correctly.
#[rustfmt::skip]
const MATRIX: &[Shape] = &[
    // ---- macro defined OUTSIDE, template READS X ------------------------
    // The template's `X` is the global; a use-site binder must not capture
    // it. The tree-walker used to capture on every binder; the six ordinary
    // binder rows went green when the by-name fallback stopped resurrecting
    // a binding the resolution rejected (`Environment::get_scoped_fallback`).
    // The internal define captured on both backends until it carried the
    // scopes of the body it stands in to the runtime, like a parameter.
    Shape { binder: Binder::LambdaParam, site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(global global)", family: "" },
    Shape { binder: Binder::Let,         site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(global global)", family: "" },
    Shape { binder: Binder::LetStar,         site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(global global)", family: "" },
    Shape { binder: Binder::Letrec,       site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(global global)", family: "" },
    Shape { binder: Binder::NamedLet,    site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(global global)", family: "" },
    Shape { binder: Binder::DoVar,       site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(global global)", family: "" },
    // The one binder the VM got wrong too: an internal define reached the
    // runtime with an empty scope set on both backends, until step 2.
    Shape { binder: Binder::InternalDef, site: Site::Outside, action: Action::Read,
            correct: "(global global)", vm: "(global global)", tw: "(global global)", family: "" },

    // ---- macro defined OUTSIDE, template WRITES X -----------------------
    // The write must reach past the use-site binder to the global. These are
    // the rows PR #138 broke while every other gate stayed green; they are
    // correct today and are a regression guard, not a defect pin.
    Shape { binder: Binder::LambdaParam, site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    Shape { binder: Binder::Let,         site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    Shape { binder: Binder::LetStar,         site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    Shape { binder: Binder::Letrec,       site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    Shape { binder: Binder::NamedLet,    site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    Shape { binder: Binder::DoVar,       site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },
    // The VM captured the internal define here until it carried scopes: an
    // empty binding set is a subset of every reference's, so the define was
    // a universal candidate for the template's `set!`.
    Shape { binder: Binder::InternalDef, site: Site::Outside, action: Action::Write,
            correct: "(5 99)", vm: "(5 99)", tw: "(5 99)", family: "" },

    // ---- macro defined INSIDE, template READS X -------------------------
    // The template's `X` *is* the binder's, so reading it must yield 5.
    // Everything passes: reaching inward is the direction both backends have.
    Shape { binder: Binder::LambdaParam, site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: Binder::Let,         site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: Binder::LetStar,         site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: Binder::Letrec,       site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: Binder::NamedLet,    site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: Binder::InternalDef, site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },
    Shape { binder: Binder::DoVar,       site: Site::Inside, action: Action::Read,
            correct: "(5 global)", vm: "(5 global)", tw: "(5 global)", family: "" },

    // ---- macro defined INSIDE, template WRITES X ------------------------
    // The write must land on the binder, leaving the global alone.
    Shape { binder: Binder::LambdaParam, site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    Shape { binder: Binder::Let,         site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    Shape { binder: Binder::LetStar,         site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    Shape { binder: Binder::Letrec,       site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    Shape { binder: Binder::NamedLet,    site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    // Family 38's last surface: the tree-walker's scoped write found no
    // candidate — an internal define had no scopes — and fell back at the
    // *root*, assigning the global and leaving the binder at 5. Fixed by the
    // same change as the rows above: with the define bound at its body's
    // scopes, the template's write resolves to it like any other binding.
    Shape { binder: Binder::InternalDef, site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
    Shape { binder: Binder::DoVar,       site: Site::Inside, action: Action::Write,
            correct: "(99 global)", vm: "(99 global)", tw: "(99 global)", family: "" },
];

// ─── The second table: generated macros and the library boundary ────────────
//
// The 28 shapes above hold the macro fixed — hand-written, in the program —
// and move the use site's *binder*. This table holds the binder simple and
// moves the macro: who wrote it, and where. Those were the two axes the header
// used to list first among the uncovered ones, and issue #402 (chibi-tar) was
// both at once: a macro *generated by another macro* inside a library, then
// *imported*, lost every reference its template made to the library's own
// bindings. It has its own table rather than new `Site`s above because its
// axes do not cross with a `Binder`: a macro in a library cannot also be
// defined inside the use site's `let`.

/// How the macro `m` that mentions `X` came to exist.
#[derive(Clone, Copy, PartialEq)]
enum Maker {
    /// Hand-written: `(define-syntax m (syntax-rules () …))`. The control —
    /// one level of macro, which is all the first table has.
    Written,
    /// Generated: `(def-m m)`, where `def-m`'s template is the whole
    /// `define-syntax`, the mention of `X` included. `X` reaches `m`'s
    /// template as an identifier `def-m`'s expansion introduced.
    Generated,
    /// Generated, with the mention arriving through `def-m`'s pattern
    /// variable: `(def-m m X)`. `X` reaches `m`'s template as what the
    /// *caller* of `def-m` wrote — a different route through the template
    /// compiler from [`Maker::Generated`], and the one `chibi-binary-record`
    /// takes.
    GeneratedArg,
    /// Generated by a generator that **also introduces the definition the
    /// macro mentions**: `(def-m m get-X)` expands to `(define X 'def)`, a
    /// getter for it under the caller's name, and the `define-syntax` — the
    /// ordinary shape of a definer with private state. The binder is a
    /// macro-introduced global, which is triage family 40's axis; every other
    /// maker leaves `X` a definition somebody wrote. Here it is the only
    /// thing of its spelling at the definition site, so the bare name reaches
    /// it too, and relinking by name is enough.
    Introducing,
    /// [`Maker::Introducing`] with a plain `(define X 'plain)` beside it, so
    /// the bare name reaches *that* and only the mention's scopes select the
    /// introduced one. #408's first shape.
    IntroducingBeside,
    /// [`Maker::Introducing`] with the generator run a second time — the
    /// ordinary way to use a definer. The row uses the *first* run's macro and
    /// getter; the bare name reaches the second run's definition, which holds
    /// `'other` so that a read can tell the two apart. #408's second shape.
    IntroducingTwice,
    /// [`Maker::IntroducingTwice`] with both runs in **one top-level form**,
    /// as a macro that expands to two definer calls leaves them. The
    /// difference is the VM's: it renames and records introduced definitions
    /// a form at a time, and kept one record per *spelling* per form, so the
    /// first run's identity was lost and its macro was relinked by name — to
    /// the second run's `X`, silently. Two forms never showed it.
    IntroducingTogether,
}

impl Maker {
    /// Whether the generator introduces `X` itself, rather than mentioning
    /// one the definition site wrote.
    fn introduces(self) -> bool {
        matches!(
            self,
            Maker::Introducing
                | Maker::IntroducingBeside
                | Maker::IntroducingTwice
                | Maker::IntroducingTogether
        )
    }
}

/// What `m`'s template does with `X`.
#[derive(Clone, Copy, PartialEq)]
enum Mention {
    /// `X` is a variable and the template reads it.
    Read,
    /// `X` is a variable and the template assigns it.
    Write,
    /// `X` is a macro and the template uses it.
    Keyword,
}

/// Where `m` is defined, relative to where it is used.
#[derive(Clone, Copy, PartialEq)]
enum Boundary {
    /// In the program that uses it.
    Program,
    /// In a library that exports `m` and keeps `X` private, so the use site
    /// has no way to mean the library's `X` except through `m`.
    Library,
}

/// What the use site itself means by `X`.
///
/// This is the axis that makes the table two-directional. `Unbound` is the
/// loud face of #402 — the template's `X` reaches nothing. The other two are
/// the silent one: the use site has an `X` of its own, the template's must
/// not reach *it*, and the `X` the user passes to `m` as an argument must not
/// be dragged to the definition site either (Larceny family 35, which is the
/// direction a careless fix for the first face breaks).
#[derive(Clone, Copy, PartialEq)]
enum UseSite {
    /// The use site does not bind `X`.
    Unbound,
    /// The use site binds `X` at top level. Only under [`Boundary::Library`]:
    /// in one program that is a second definition of the *same* variable,
    /// which is not a question about hygiene.
    Global,
    /// The use site binds `X` in a `let` (`let-syntax` for a keyword).
    Local,
    /// The use site **imports** `X` from the library — so the two mean one
    /// binding while `m` is expanded — and defines an `X` of its own
    /// *afterwards* (#438). The expansion sits in a procedure that runs after
    /// the definition, as under [`Values::Equal`].
    ///
    /// R7RS calls redefining an import an error in a program and says a REPL
    /// should permit it; chibi and Gauche both permit it and both keep the
    /// template's `X` the library's. What they *disagree* about is a
    /// reference the program itself wrote before its definition (chibi keeps
    /// the import, Gauche follows the definition), so the row passes `m` a
    /// literal rather than the program's `X`.
    Redefined,
}

/// What the two `X`s hold **while the macro is being expanded**.
///
/// The axis #407 was missing, and the reason this table read 45 of 45 across
/// it: every row gave the two sides different values, and the relinker's
/// fast path compared values. Two variables that are both `0`, `#f` or `'()`
/// — which is what variables are initialised to — read as one binding, so a
/// library macro's `(set! X …)` landed on the importing program's `X`.
///
/// An `Equal` program cannot be the `Distinct` one with the values changed,
/// because a read of two equal values says nothing about which was read. So
/// it expands `m` inside a procedure while both sides hold `'same`, gives the
/// use site's `X` the value `'use` afterwards, and only then runs it. That
/// wrapper is how the axis is observed rather than a second thing it moves:
/// what differs at expansion time is the values and nothing else.
#[derive(Clone, Copy, PartialEq)]
enum Values {
    /// `'def` at the definition site, `'use` at the use site.
    Distinct,
    /// `'same` at both until `m` has been expanded.
    Equal,
}

/// One point in the second space.
struct MadeShape {
    maker: Maker,
    mention: Mention,
    boundary: Boundary,
    use_site: UseSite,
    values: Values,
    /// What chibi 0.12 and Gauche 0.9.15 both answer.
    correct: &'static str,
    /// What the VM answers today.
    vm: &'static str,
    /// What the tree-walker answers today.
    tw: &'static str,
    /// The defect this row is a face of, or `""` when the row is correct.
    family: &'static str,
}

impl MadeShape {
    fn name(&self) -> String {
        let maker = match self.maker {
            Maker::Written => "written",
            Maker::Generated => "generated",
            Maker::GeneratedArg => "generated-arg",
            Maker::Introducing => "introducing",
            Maker::IntroducingBeside => "introducing-beside",
            Maker::IntroducingTwice => "introducing-twice",
            Maker::IntroducingTogether => "introducing-together",
        };
        let mention = match self.mention {
            Mention::Read => "read",
            Mention::Write => "write",
            Mention::Keyword => "keyword",
        };
        let boundary = match self.boundary {
            Boundary::Program => "program",
            Boundary::Library => "library",
        };
        let use_site = match self.use_site {
            UseSite::Unbound => "unbound",
            UseSite::Global => "global",
            UseSite::Local => "local",
            UseSite::Redefined => "redefined",
        };
        let values = match self.values {
            Values::Distinct => "",
            Values::Equal => "/equal",
        };
        format!("{maker}/{mention}/{boundary}/{use_site}{values}")
    }
}

/// The two halves of a [`MadeShape`]'s program: the library form, when there
/// is one, and everything after it.
///
/// Kept apart because chibi cannot take a `define-library` in a script
/// (`tests/scheme/expansion/template-references.scm` has the measurement), so
/// [`dump_programs`] writes the first half to `hm/gen.sld` for the oracles.
/// Patina runs the two concatenated. Neither half is edited on the way.
///
/// Every shape observes both sides, like the first table: the definition
/// site's `X` through `get-X`, which the defining context supplies whether or
/// not the shape needs it (an axis must move one thing), and the use site's
/// through the argument the user passes to `m`. A write is sequenced by a
/// `let`, not by operand order, for the reason [`program`] gives.
fn made_program_parts(shape: &MadeShape) -> (Option<String>, String) {
    let equal = shape.values == Values::Equal;
    // `Equal` is an axis of two *variables*: a keyword holds no value to be
    // equal, and an unbound use site has no `X` to be equal with. Either
    // would build a program that runs and says nothing about the axis, so a
    // row asking for one is refused rather than scored.
    assert!(
        !equal || (shape.mention != Mention::Keyword && shape.use_site != UseSite::Unbound),
        "{}: `Values::Equal` needs a variable `X` on both sides",
        shape.name()
    );
    // Defining over an import takes a library to import from, a variable to
    // define, and an `X` the library can export by its bare name — which a
    // definition a macro introduced is not.
    let redefined = shape.use_site == UseSite::Redefined;
    assert!(
        !redefined
            || (shape.boundary == Boundary::Library
                && shape.mention != Mention::Keyword
                && !shape.maker.introduces()
                && !equal),
        "{}: `UseSite::Redefined` needs a library exporting a written variable `X`",
        shape.name()
    );
    // An introducing generator's `X` is a variable; a keyword it introduced
    // would be #269's `define-syntax` half, which is not this table's.
    assert!(
        !shape.maker.introduces() || (shape.mention != Mention::Keyword && !equal),
        "{}: an introducing maker needs a variable `X`, with distinct values",
        shape.name()
    );
    // What each side's variable starts as is all `Values` changes in the
    // definitions; the wrapper below is how it is observed.
    let (def_x, use_global, use_local) = if equal {
        ("(define X 'same)", "(define X 'same)", "let ((X 'same))")
    } else {
        ("(define X 'def)", "(define X 'use)", "let ((X 'use))")
    };
    let (define_x, mention, get_x) = match shape.mention {
        Mention::Read => (def_x, "X", "X"),
        Mention::Write => (def_x, "(set! X 'set)", "X"),
        Mention::Keyword => (
            "(define-syntax X (syntax-rules () ((X) 'def)))",
            "(X)",
            "(X)",
        ),
    };
    // What `m` expands to, given the text that mentions `X`.
    let template = |mention: &str| match shape.mention {
        Mention::Write => format!("(begin {mention} v)"),
        Mention::Read | Mention::Keyword => format!("(list {mention} v)"),
    };
    let make_m = match shape.maker {
        Maker::Written => format!(
            "(define-syntax m (syntax-rules () ((m v) {})))",
            template(mention)
        ),
        Maker::Generated => format!(
            "(define-syntax def-m\n  (syntax-rules ()\n    ((def-m name)\n     \
             (define-syntax name (syntax-rules () ((name v) {}))))))\n(def-m m)",
            template(mention)
        ),
        Maker::GeneratedArg => format!(
            "(define-syntax def-m\n  (syntax-rules ()\n    ((def-m name mention)\n     \
             (define-syntax name (syntax-rules () ((name v) {}))))))\n(def-m m {mention})",
            template("mention")
        ),
        // The definer alone; what runs it, and how often, is the rest of the
        // axis, below. It takes the value so that two runs can differ.
        Maker::Introducing
        | Maker::IntroducingBeside
        | Maker::IntroducingTwice
        | Maker::IntroducingTogether => format!(
            "(define-syntax def-m\n  (syntax-rules ()\n    ((def-m name getter value)\n     \
             (begin\n       (define X value)\n       (define (getter) {get_x})\n       \
             (define-syntax name (syntax-rules () ((name v) {})))))))",
            template(mention)
        ),
    };
    // The definition site's `X` and its getter are the generator's own work
    // under an introducing maker; what stands beside them is the rest of the
    // axis.
    let (first_run, second_run) = ("(def-m m get-X 'def)", "(def-m m2 get-X2 'other)");
    let definitions = match shape.maker {
        Maker::Introducing => format!("{make_m}\n{first_run}"),
        Maker::IntroducingBeside => format!("(define X 'plain)\n{make_m}\n{first_run}"),
        Maker::IntroducingTwice => format!("{make_m}\n{first_run}\n{second_run}"),
        Maker::IntroducingTogether => format!("{make_m}\n(begin {first_run} {second_run})"),
        Maker::Written | Maker::Generated | Maker::GeneratedArg => {
            format!("{define_x}\n(define (get-X) {get_x})\n{make_m}")
        }
    };

    // The use site's own `X`, and the expression that names it.
    let (bind_global, bind_local, own_x) = match shape.mention {
        Mention::Read | Mention::Write => (use_global, use_local, "X"),
        Mention::Keyword => (
            "(define-syntax X (syntax-rules () ((X) 'use)))",
            "let-syntax ((X (syntax-rules () ((X) 'use))))",
            "(X)",
        ),
    };
    let own_x = if matches!(shape.use_site, UseSite::Unbound | UseSite::Redefined) {
        "'use"
    } else {
        own_x
    };
    let observe = match shape.mention {
        Mention::Write => format!("(let ((u (m {own_x}))) (list (get-X) u))"),
        Mention::Read | Mention::Keyword => format!("(m {own_x})"),
    };
    // Under `Values::Equal`: expand while the two are equal, tell them apart,
    // then run. Each top-level form is expanded as it is reached, so the
    // `define` is expanded before the `set!` runs; a `let` body is expanded
    // whole, before any of it runs.
    let use_site = match (shape.use_site, equal) {
        (UseSite::Unbound, _) => observe,
        // Expand while `X` is the import, define over it, then run.
        (UseSite::Redefined, _) => {
            format!("(define (run) {observe})\n{bind_global}\n(run)")
        }
        (UseSite::Global, false) => format!("{bind_global}\n{observe}"),
        (UseSite::Local, false) => format!("({bind_local} {observe})"),
        (UseSite::Global, true) => {
            format!("{bind_global}\n(define (run) {observe})\n(set! X 'use)\n(run)")
        }
        (UseSite::Local, true) => {
            format!("({bind_local} (define (run) {observe}) (set! X 'use) (run))")
        }
    };

    match shape.boundary {
        Boundary::Program => (None, format!("{definitions}\n{use_site}")),
        Boundary::Library => {
            let body = definitions.replace('\n', "\n    ");
            let exports = if redefined { "m get-X X" } else { "m get-X" };
            let library = format!(
                "(define-library (hm gen)\n  (import (scheme base))\n  \
                 (export {exports})\n  (begin\n    {body}))"
            );
            (
                Some(library),
                format!("(import (scheme base) (hm gen))\n{use_site}"),
            )
        }
    }
}

/// The program Patina runs for one [`MadeShape`].
fn made_program(shape: &MadeShape) -> String {
    match made_program_parts(shape) {
        (Some(library), main) => format!("{library}\n{main}"),
        (None, main) => main,
    }
}

#[rustfmt::skip]
const MADE: &[MadeShape] = &[
    // ---- defined and used in ONE PROGRAM --------------------------------
    // No boundary, so nothing needs carrying across one: generation alone has
    // never been the defect. These are the control for the rows below, and
    // the guard against a fix that reaches for a generated macro's
    // identifiers where nothing was wrong with them.
    MadeShape { maker: Maker::Written,       mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Keyword,  boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Keyword,  boundary: Boundary::Program, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Keyword,  boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Keyword,  boundary: Boundary::Program, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Keyword,  boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Keyword,  boundary: Boundary::Program, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    // ---- defined in a LIBRARY, used by a program that imports it ----------
    // `X` is private to the library. The hand-written rows are the control for
    // the boundary, as the block above is for generation: each axis was sound
    // alone and the defect was their intersection.
    MadeShape { maker: Maker::Written,       mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Global, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Global, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Keyword,  boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Keyword,  boundary: Boundary::Library, use_site: UseSite::Global, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Keyword,  boundary: Boundary::Library, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    // Family 47 (#402) was all eighteen rows from here down, on both backends.
    // A generated macro's template holds `X` as an *identifier* — text an
    // outer expansion produced — and the relinker's list of names to carry
    // back to the definition site was built from written symbols only, so
    // for such a macro it was empty. Twelve rows were loud (`unbound
    // variable: X`). The six `global` rows were not: the template's `X`
    // landed on the importing program's own — `(use use)` — and the write
    // rows *assigned* it, `(def set)`. All eighteen went green together when
    // the template compiler started recording those identifiers
    // (`CompiledMacro::inherited_identifiers`), none of the other 55 moving.
    MadeShape { maker: Maker::Generated,     mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Global, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Global, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Keyword,  boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Keyword,  boundary: Boundary::Library, use_site: UseSite::Global, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Keyword,  boundary: Boundary::Library, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Global, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Global, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Keyword,  boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Keyword,  boundary: Boundary::Library, use_site: UseSite::Global, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Keyword,  boundary: Boundary::Library, use_site: UseSite::Local, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    // ---- EQUAL VALUES while `m` is expanded (#407) -----------------------
    // In one program there is one environment and nothing to relink, so
    // these are the control again.
    MadeShape { maker: Maker::Written,       mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(same use)", vm: "(same use)", tw: "(same use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(same use)", vm: "(same use)", tw: "(same use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(same use)", vm: "(same use)", tw: "(same use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    // Across a library. `global` is #407 itself: the relinker took the
    // program's `X` for the library's because both held `'same`, so the
    // template read and assigned the program's. `local` was never wrong — the
    // by-name view the relinker compares does not see a `let` — and is here
    // so that a fix keeps it that way.
    MadeShape { maker: Maker::Written,       mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Equal,
                correct: "(same use)", vm: "(same use)", tw: "(same use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(same use)", vm: "(same use)", tw: "(same use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Equal,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Equal,
                correct: "(same use)", vm: "(same use)", tw: "(same use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(same use)", vm: "(same use)", tw: "(same use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Equal,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Equal,
                correct: "(same use)", vm: "(same use)", tw: "(same use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(same use)", vm: "(same use)", tw: "(same use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Equal,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Equal,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    // ---- THE GENERATOR INTRODUCES THE DEFINITION (#408) ------------------
    // A macro-introduced global as the binder, family 40's axis, which this
    // file listed as uncovered until it was crossed with the library boundary
    // here. `introducing` is the control: nothing else has the spelling, so
    // the bare name reaches the introduced `X` and relinking by name was
    // always enough. `-beside` and `-twice` are #408: the bare name reaches
    // something else — a plain `X`, or a second run's — and only the
    // mention's own scopes select the right one. Across a library both were
    // refused (`unbound variable: X`) where the program had no `X`, and
    // answered with the *program's* `X` where it had one.
    MadeShape { maker: Maker::Introducing,       mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Introducing,       mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Introducing,       mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Introducing,       mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Introducing,       mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Introducing,       mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Introducing,       mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Introducing,       mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Introducing,       mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Introducing,       mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingBeside, mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingBeside, mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingBeside, mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingBeside, mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingBeside, mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingBeside, mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingBeside, mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingBeside, mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingBeside, mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingBeside, mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingTwice,  mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingTwice,  mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingTwice,  mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingTwice,  mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingTwice,  mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingTwice,  mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingTwice,  mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingTwice,  mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingTwice,  mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingTwice,  mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    // Both runs in one form. Red on the VM alone, in one program as well as
    // across a library, and silently: `(other use)` for a read.
    MadeShape { maker: Maker::IntroducingTogether, mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingTogether, mention: Mention::Read,     boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingTogether, mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingTogether, mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingTogether, mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::IntroducingTogether, mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingTogether, mention: Mention::Write,    boundary: Boundary::Program, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingTogether, mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Unbound, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingTogether, mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Global,  values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::IntroducingTogether, mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Local,   values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    // ---- IMPORTED, THEN DEFINED OVER after `m` was expanded (#438) -------
    // The relinker left a reference alone where both sides reached one
    // binding — and here they do, the program's `X` *is* the import — so it
    // stayed a bare global name, looked up when it ran, by which time the
    // name was the program's own. Both backends, written and generated alike:
    // `(use use)` for a read, and a write landing on the program's `X`.
    MadeShape { maker: Maker::Written,       mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Redefined, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Written,       mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Redefined, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Redefined, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::Generated,     mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Redefined, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Read,     boundary: Boundary::Library, use_site: UseSite::Redefined, values: Values::Distinct,
                correct: "(def use)", vm: "(def use)", tw: "(def use)", family: "" },
    MadeShape { maker: Maker::GeneratedArg,  mention: Mention::Write,    boundary: Boundary::Library, use_site: UseSite::Redefined, values: Values::Distinct,
                correct: "(set use)", vm: "(set use)", tw: "(set use)", family: "" },
];

impl Shape {
    fn name(&self) -> String {
        let site = if self.site == Site::Outside {
            "outside"
        } else {
            "inside"
        };
        let action = if self.action == Action::Read {
            "read"
        } else {
            "write"
        };
        format!("{}/{site}/{action}", self.binder.name())
    }
}

/// Write every program out, **ready to run** under an oracle.
///
/// Ignored by default: it asserts nothing, it exists so both tables can be
/// re-*measured* rather than re-derived — the same arrangement, for the same
/// reason, as `control_flow_matrix.rs`'s `dump_programs`. The text an oracle
/// is fed must be the text this file runs, and taking it from the same
/// generator is the only thing that guarantees it.
///
/// Each shape gets a directory holding `main.scm` — the program behind an
/// `(import (scheme base) (scheme write))`, with a `write` around its final
/// expression, which the oracles otherwise evaluate silently — and, for a
/// [`Boundary::Library`] shape, the library form verbatim in `hm/gen.sld`,
/// since chibi cannot take one in a script. **The program text itself is
/// never edited.**
///
/// ```text
/// HYGIENE_MATRIX_DUMP=/tmp/hm cargo test -p patina-tests \
///     --test hygiene_matrix -- --ignored dump_programs
/// for d in /tmp/hm/*/; do chibi-scheme -I "$d" "$d/main.scm"; done
/// for d in /tmp/hm/*/; do gosh -r7 -I "$d" "$d/main.scm"; done
/// ```
#[test]
#[ignore]
fn dump_programs() {
    let dir = std::env::var("HYGIENE_MATRIX_DUMP").expect("set HYGIENE_MATRIX_DUMP to a directory");
    let first = MATRIX.iter().map(|s| (s.name(), None, program(s)));
    let second = MADE.iter().map(|s| {
        let (library, main) = made_program_parts(s);
        (s.name(), library, main)
    });
    for (name, library, main) in first.chain(second) {
        let sub = format!("{dir}/{}", name.replace('/', "_").replace('*', "star"));
        std::fs::create_dir_all(format!("{sub}/hm")).expect("create dump directory");
        if let Some(library) = library {
            std::fs::write(format!("{sub}/hm/gen.sld"), format!("{library}\n"))
                .expect("write library");
        }
        let (body, last) = main
            .rsplit_once('\n')
            .expect("every program has more than one line");
        std::fs::write(
            format!("{sub}/main.scm"),
            format!("(import (scheme base) (scheme write))\n{body}\n(write {last})(newline)\n"),
        )
        .expect("write program");
    }
}

/// A row of either table, reduced to what scoring reads.
struct Row {
    name: String,
    code: String,
    correct: &'static str,
    vm: &'static str,
    tw: &'static str,
    family: &'static str,
}

/// Both tables, so the scoring tests cannot cover one and forget the other.
fn all_rows() -> Vec<Row> {
    let first = MATRIX.iter().map(|s| Row {
        name: s.name(),
        code: program(s),
        correct: s.correct,
        vm: s.vm,
        tw: s.tw,
        family: s.family,
    });
    let second = MADE.iter().map(|s| Row {
        name: s.name(),
        code: made_program(s),
        correct: s.correct,
        vm: s.vm,
        tw: s.tw,
        family: s.family,
    });
    first.chain(second).collect()
}

/// Run one shape on one backend, rendering a rejection as [`ERROR`].
fn answer(code: &str, vm: bool) -> String {
    let ok = if vm {
        try_eval_program_vm(code)
    } else {
        try_eval_program_tree_walker(code)
    };
    // The message is kept rather than collapsed to a token: no row expects an
    // error, so one appearing is a surprise, and a bare `<error>` in the
    // failure output would say nothing about which.
    ok.unwrap_or_else(|e| format!("{ERROR}: {}", e.lines().next().unwrap_or("").trim()))
}

/// Every shape answers what the table says it answers, on both backends.
///
/// The whole point is that this fails in *both* directions: fixing a defect
/// turns its row red just as breaking a working shape does. A red row is never
/// "just update the table" — read which direction it moved first.
#[test]
fn shapes_score_as_recorded() {
    let mut moved = Vec::new();
    for row in all_rows() {
        for (backend, recorded) in [("vm", row.vm), ("tree-walker", row.tw)] {
            let got = answer(&row.code, backend == "vm");
            if got != recorded {
                moved.push(common::describe_move(
                    &row.name,
                    backend,
                    recorded,
                    &got,
                    row.correct,
                    &row.code,
                ));
            }
        }
    }
    assert!(
        moved.is_empty(),
        "{} hygiene shape(s) no longer answer what the matrix records.\n\n{}\n\n\
         Update the row(s) in MATRIX or MADE and the count in \
         `the_defect_count_is_what_the_roadmap_says`, then say which family \
         moved in {TRIAGE}.",
        moved.len(),
        moved.join("\n\n")
    );
}

/// How many shapes each backend gets wrong, asserted as a number.
///
/// A count is the thing the chibi suite cannot give: it has read 1226/1226 on
/// both backends through every defect in this table. This number can only move
/// deliberately.
#[test]
fn the_defect_count_is_what_the_roadmap_says() {
    let rows = all_rows();
    let wrong = |pick: fn(&Row) -> &'static str| {
        rows.iter()
            .filter(|r| pick(r) != r.correct)
            .map(|r| r.name.clone())
            .collect::<Vec<_>>()
    };
    let vm = wrong(|r| r.vm);
    let tw = wrong(|r| r.tw);

    // Zero, on both backends and in both tables — the hygiene queue's steps 1
    // and 2 are done, and family 47's eighteen rows (36 cells) went green
    // together. A row going red now is a regression on a shape the oracles
    // agree about, whichever direction it moved.
    assert_eq!(vm.len(), 0, "VM shapes wrong: {vm:?}");
    assert_eq!(tw.len(), 0, "tree-walker shapes wrong: {tw:?}");

    // Every wrong row names the family it belongs to, so the table doubles as
    // the index from defect to surface count.
    for row in &rows {
        let correct = row.vm == row.correct && row.tw == row.correct;
        assert_eq!(
            correct,
            row.family.is_empty(),
            "{}: `family` must be set exactly on rows some backend gets wrong",
            row.name
        );
    }
}

/// Families 36 and 38 are closed; no row is a defect pin any more.
///
/// Family 36 began as one defect with eight surfaces. The six ordinary
/// binder rows went green together when the by-name fallback stopped
/// resurrecting a rejected binding — together, which is what this count
/// being a test was for. The internal-define rows (and family 38's, whose
/// fix was the same one) went green together when internal defines started
/// carrying the scopes of the body they stand in to the runtime, on both
/// backends. An empty `family` on every row — of both tables, family 47's
/// eighteen included — is now itself asserted, so a future defect pin has to
/// bring its family label back with it.
#[test]
fn family_36_is_closed() {
    let faces: Vec<String> = all_rows()
        .iter()
        .filter(|r| !r.family.is_empty())
        .map(|r| format!("{} ({})", r.name, r.family))
        .collect();
    assert!(faces.is_empty(), "rows still pinned to a defect: {faces:?}");
}

/// The two `do` rows are not a hygiene defect and should not be fixed as one.
///
/// R7RS §5.3.2 admits definitions in a `⟨body⟩`; a `do` result clause is a
/// sequence of expressions, not a body. chibi and Racket both reject it and
/// Patina runs it. Separated from the hygiene rows because a reader scanning
/// this file for "what is wrong with our macros" should not count it.
#[test]
fn a_do_result_clause_is_not_a_definition_context() {
    let code = "(define X 'global)\n\
                (define r (do ((X 5 X)) (#t (define-syntax m (syntax-rules () ((m) X))) (m))))\n\
                (list r X)";
    // Pinned as accepted, which is the defect. When Patina starts rejecting
    // this, both of these turn red and the two `do` rows in MATRIX get
    // `vm`/`tw` set to ERROR.
    assert_eq!(eval_program_vm(code), "(5 global)");
    assert_eq!(eval_program_tree_walker(code), "(5 global)");
}

/// A program that defines over an imported name *after* a library macro
/// mentioning it was expanded does not capture the template's reference: one
/// procedure, compiled once, bumps the library's `count` on both of its
/// calls. chibi 0.12 and Gauche 0.9.15 both answer `(2 100)`.
///
/// This pinned `(1 101)` from #439 until #438: the second call bumped the
/// *program's* `count`. The relinker leaves a template's reference alone when
/// the use site and the definition site reach one binding by the name, and
/// here they truthfully do — the program's `count` *is* the import. Left
/// alone it was a bare global name, resolved again when it ran, and `define`
/// over an import makes the program a binding of its own in the same slot. It
/// is bound to the import's *location* now (`Environment::import_alias`).
///
/// [`MADE`]'s `redefined` rows score the axis. This test stays for the shape
/// they do not have — the same procedure called on both sides of the
/// definition — and for the other order, define first and expand afterwards,
/// which was always right and which a fix for one order must not cost.
#[test]
fn a_definition_over_an_import_does_not_capture_an_expanded_template() {
    let library = "(define-library (hm shared)\n  (import (scheme base))\n  \
                   (export count get-count bump-count!)\n  (begin\n    \
                   (define count 0)\n    (define (get-count) count)\n    \
                   (define-syntax bump-count!\n      \
                   (syntax-rules () ((_) (set! count (+ count 1)))))))\n\
                   (import (scheme base) (hm shared))\n";
    let expanded_first = format!(
        "{library}(define (bump) (bump-count!))\n(bump)\n(define count 100)\n(bump)\n\
         (list (get-count) count)"
    );
    let defined_first = format!(
        "{library}(define count 100)\n(define (bump) (bump-count!))\n(bump)\n\
         (list (get-count) count)"
    );
    for vm in [true, false] {
        assert_eq!(
            answer(&expanded_first, vm),
            "(2 100)",
            "`(1 101)` is the template's reference following the program's definition"
        );
        assert_eq!(answer(&defined_first, vm), "(1 100)");
    }
}

/// A program's definition over an imported name is not the binding a
/// library macro's *literal* of that name means (#450) — the literal-side
/// twin of the test above. chibi 0.12 and Gauche 0.9.15 answer `2`, `lit` and
/// `1`, measured 2026-09-22.
///
/// Two identifiers spelled alike and reaching no local binding were matched
/// whatever global each reached, so after `(define else #f)` the `(else 1)`
/// below was still `cond`'s else clause and answered `1`. The literal now
/// matches when the two reach one location (`Environment::binding_location`),
/// which the program's `else` stops doing once it defines over the import.
///
/// The other two are the controls. A macro the program defines itself sees
/// the program's own `else` as its literal's binding, before the definition
/// and after it, in both oracles: `lit`. And a program that never defines
/// `else` reaches the imported keyword, as it always did.
#[test]
fn a_definition_over_an_import_is_not_a_library_macros_literal() {
    let over_the_import = "(import (scheme base))\n(define else #f)\n\
                           (cond (#f 0) (else 1) (#t 2))";
    let the_programs_own_macro = "(import (scheme base))\n\
                                  (define-syntax m\n  \
                                  (syntax-rules (else) ((_ else) 'lit) ((_ x) 'var)))\n\
                                  (define else #f)\n(m else)";
    let never_defined = "(import (scheme base))\n(cond (#f 0) (else 1))";
    for vm in [true, false] {
        assert_eq!(
            answer(over_the_import, vm),
            "2",
            "`1` is the program's `else` taken for `cond`'s keyword"
        );
        assert_eq!(answer(the_programs_own_macro, vm), "lit");
        assert_eq!(answer(never_defined, vm), "1");
    }
}

/// An import that is a *copy* still matches the exporting library's literal
/// of that name. An export a macro introduced is one `share_binding` cannot
/// share, so the importer holds it at a location of its own; compared by
/// location alone, the two read as the different globals #450 tells apart,
/// and `(m kw)` below answered `var`. Gauche 0.9.15 answers `lit`, as does
/// chibi 0.12 with the library in a file of its own, measured 2026-09-22.
#[test]
fn an_import_installed_as_a_copy_still_matches_the_librarys_literal() {
    let program = "(define-library (hm introduced)\n  (import (scheme base))\n  \
                   (export m kw)\n  (begin\n    \
                   (define-syntax define-kw (syntax-rules () ((_) (define kw 'kw))))\n    \
                   (define-kw)\n    \
                   (define-syntax m (syntax-rules (kw) ((_ kw) 'lit) ((_ x) 'var)))))\n\
                   (import (scheme base) (hm introduced))\n(m kw)";
    for vm in [true, false] {
        assert_eq!(
            answer(program, vm),
            "lit",
            "`var` is the copied import read as a global of the program's own"
        );
    }
}

/// Two libraries' bindings of one spelling are two literals, not one: under
/// SRFI 101's `quote` a library macro's `quote` literal takes its other rule.
/// chibi 0.12 and Gauche 0.9.15 answer `other`, and `quoted` for the control,
/// where the use site's `quote` is `(scheme base)`'s, measured 2026-09-22.
///
/// The global half of the spelling-based matching recorded in
/// `scheme_tests/reports/larceny_triage.md`: two names reaching no local
/// binding matched whenever they were spelled alike, and this answered
/// `quoted` for both. #450's location comparison is what tells them apart.
#[test]
fn a_literal_is_not_another_librarys_binding_of_its_spelling() {
    let library = "(define-library (hm q)\n  (import (scheme base))\n  (export mq)\n  \
                   (begin\n    (define-syntax mq\n      \
                   (syntax-rules (quote) ((_ 'x) 'quoted) ((_ y) 'other)))))\n";
    let srfi_101 =
        format!("{library}(import (except (scheme base) quote) (srfi 101) (hm q))\n(mq 'a)");
    let scheme_base = format!("{library}(import (scheme base) (hm q))\n(mq 'a)");
    for vm in [true, false] {
        assert_eq!(
            answer(&srfi_101, vm),
            "other",
            "`quoted` is SRFI 101's `quote` taken for `(scheme base)`'s"
        );
        assert_eq!(answer(&scheme_base, vm), "quoted");
    }
}

/// A location both sides imported under **two names** — `string-length`, and
/// `slen` by a `rename` — keeps its two spellings apart when a reference is
/// bound early (#438). Gauche 0.9.15 answers `(2 introduced)` and `(3 3)`.
///
/// The alias is a name for the *location*, and the end of the form reads the
/// spelling a reference was written with back off it, to take the binding
/// back where the same expansion introduced a definition of that spelling
/// (`Desugarer::settle_early_bindings`). With one alias per location both
/// spellings shared it, the first one seen was what it read back, and the
/// template's `(slen "abc")` beside the `(define (slen s) …)` its own
/// expansion introduced stayed bound to the import: `(2 3)`, where `main`
/// answered `(2 introduced)` before there was any early binding. An alias per
/// imported name (`Environment::import_alias`) is what keeps them apart.
///
/// The second program is the other half: with no introduced definition both
/// spellings are bound early, so a later definition of either captures
/// neither — `(3 mine)` is the second spelling having been left as written.
#[test]
fn two_names_for_one_import_are_bound_early_as_two() {
    let library = "(define-library (hm two-names)\n  (import (scheme base)\n    \
                   (rename (only (scheme base) string-length) (string-length slen)))\n  \
                   (export def-and-use both)\n  (begin\n    \
                   (define-syntax def-and-use\n      (syntax-rules ()\n        \
                   ((_ getter)\n         \
                   (begin (define (getter) (list (string-length \"ab\") (slen \"abc\")))\n                \
                   (define (slen s) 'introduced)))))\n    \
                   (define-syntax both\n      \
                   (syntax-rules () ((_ s) (list (string-length s) (slen s)))))))\n\
                   (import (scheme base)\n  \
                   (rename (only (scheme base) string-length) (string-length slen))\n  \
                   (hm two-names))\n";
    let introduced_beside = format!("{library}(def-and-use get)\n(get)");
    let defined_over = format!(
        "{library}(define (f) (both \"abc\"))\n(define (slen s) 'mine)\n\
         (define (string-length s) 'mine)\n(f)"
    );
    for vm in [true, false] {
        assert_eq!(
            answer(&introduced_beside, vm),
            "(2 introduced)",
            "`(2 3)` is `slen` settled by what the form said about `string-length`"
        );
        assert_eq!(answer(&defined_over, vm), "(3 3)");
    }
}

/// A generated macro whose generator *also introduced the definition it
/// mentions*, beside a plain definition of the same spelling, reaches the
/// introduced one across a library boundary — `introduced`, as chibi 0.12 and
/// Gauche 0.9.15 answer.
///
/// [`MADE`]'s `introducing-beside` rows score this axis now (#408). This test
/// predates them — it was the pin for the refusal — and stays for the two
/// wrong answers it exists to tell apart, which a row's `(def use)` does not
/// name:
///
/// - **`plain`** means the relinker aliased *by name*. The name alone reaches
///   the plain `X`; the template's `X` carries the generator's expansion
///   scope, which selects the introduced one. The first version of #402's fix
///   did exactly this, silently, where there had been a loud error — the
///   trade PR #133 and PR #138 were closed for making.
/// - **an error naming `X`, or `use`** means the mention was left to scoped
///   resolution at the use site, which cannot see into the library: the
///   refusal this pinned from #402 until #408, loud only where the importing
///   program has no `X` of its own. The second program gives it one.
///
/// What fixed it is an alias to the *binding* the mention's scopes select
/// (`Environment::introduced_definition`) rather than to the spelling.
#[test]
fn a_generated_macro_reaches_its_generators_definition_past_a_plain_one() {
    let library = "(define-library (hm sibling)\n  (import (scheme base))\n  (export m)\n  (begin\n    \
                   (define X 'plain)\n    \
                   (define-syntax def-m\n      (syntax-rules ()\n        ((def-m name)\n         \
                   (begin\n           (define X 'introduced)\n           \
                   (define-syntax name (syntax-rules () ((name) X)))))))\n    \
                   (def-m m)))\n\
                   (import (scheme base) (hm sibling))\n";
    let unbound_at_use = format!("{library}(m)");
    let bound_at_use = format!("{library}(define X 'use)\n(m)");
    for code in [&unbound_at_use, &bound_at_use] {
        for vm in [true, false] {
            assert_eq!(
                answer(code, vm),
                "introduced",
                "`plain` is the relinker aliasing by name past the introduced `X`; \
                 `use` or an error is the mention left to the use site\n{code}"
            );
        }
    }
}

/// The same where the two definitions hold **equal values**, which is how
/// they usually start (`(define count 0)`), and which a relinker that
/// compares the two views' *values* reads as agreement.
///
/// Three programs. In the first the introduced `X` sits beside a plain `X`,
/// as in the test above but both `0`; in the second a definer is run twice,
/// so each generated macro has a `count` of its own and the name alone
/// reaches only the later one; the third is the second with the two macros
/// used in the other order. chibi 0.12 and Gauche 0.9.15 answer `(1 0)`,
/// `(1 1)` and `(1 1)`, measured 2026-09-18 and 2026-09-19.
///
/// Compared by value, both backends answered `(1 1)` and `(1 2)` — the
/// library macro's `set!` landed on the plain `X`, and `tick` and `tock`
/// bumped one counter — and, since the values differ after the first bump, a
/// *later* use of the same macro was refused: run `tock` first and `tick` was
/// `unbound`, so what a program answered depended on what it had already run.
/// Asked about the binding instead (`Environment::name_reaches_binding_of`,
/// #402) all three were the loud refusal, which this test pinned; aliased to
/// the binding the mention's scopes select (#408) they are the oracles'
/// answers. [`MADE`]'s introducing makers cover distinct values only, so the
/// equal-valued face is scored here.
#[test]
fn equal_valued_definitions_are_not_mistaken_for_one_binding() {
    let sibling = "(define-library (hm sibling)\n  (import (scheme base))\n  (export bump! plain-X)\n  (begin\n    \
                   (define X 0)\n    (define (plain-X) X)\n    \
                   (define-syntax def-bump\n      (syntax-rules ()\n        ((def-bump name)\n         \
                   (begin\n           (define X 0)\n           \
                   (define-syntax name\n             (syntax-rules () ((name) (begin (set! X (+ X 1)) X))))))))\n    \
                   (def-bump bump!)))\n\
                   (import (scheme base) (hm sibling))\n\
                   (define r (bump!))\n\
                   (list r (plain-X))";
    let counters = "(define-library (hm counter)\n  (import (scheme base))\n  (export tick tock)\n  (begin\n    \
                    (define-syntax define-counter\n      (syntax-rules ()\n        ((define-counter name)\n         \
                    (begin\n           (define count 0)\n           \
                    (define-syntax name\n             (syntax-rules () ((name) (begin (set! count (+ count 1)) count))))))))\n    \
                    (define-counter tick)\n    (define-counter tock)))\n\
                    (import (scheme base) (hm counter))\n";
    let twice = format!("{counters}(define r (tick))\n(list r (tock))");
    let twice_reversed = format!("{counters}(define r (tock))\n(list r (tick))");
    for (code, correct, shared) in [
        (sibling, "(1 0)", "(1 1)"),
        (twice.as_str(), "(1 1)", "(1 2)"),
        (twice_reversed.as_str(), "(1 1)", "(1 2)"),
    ] {
        for vm in [true, false] {
            assert_eq!(
                answer(code, vm),
                correct,
                "`{shared}` means the relinker took two bindings holding equal \
                 values for one; an error means the mention was left to the use \
                 site\n{code}"
            );
        }
    }
}

/// A generated macro can mention one spelling as **two different things**,
/// which a written one cannot: here `tmp` the generator introduced, which the
/// generated template binds, and the library's own `tmp`, which the caller of
/// `def-m` passed in. chibi 0.12 and Gauche 0.9.15 both answer `(local lib)`,
/// measured 2026-09-18, and so does Patina within one program.
///
/// Across a library the relinker has to carry the second back to the
/// definition site, and one alias for the spelling renamed both mentions
/// alike — the `let` then captured the library's `tmp`: `(local local)` on
/// both backends, silently, where there had been `unbound variable: tmp`
/// before #402. Each identity a macro mentions a name under gets its own
/// alias now. The second program is the same shape with the routes swapped:
/// the binder arrives through the pattern variable and the free reference is
/// the generator's.
#[test]
fn one_spelling_mentioned_as_two_bindings_is_relinked_as_two() {
    let library = |template: &str| {
        format!(
            "(define-library (hm two)\n  (import (scheme base))\n  (export m)\n  (begin\n    \
             (define tmp 'lib)\n    \
             (define-syntax def-m\n      (syntax-rules ()\n        ((def-m name arg)\n         \
             (define-syntax name (syntax-rules () ((name) {template}))))))\n    \
             (def-m m tmp)))\n\
             (import (scheme base) (hm two))\n\
             (m)"
        )
    };
    for template in [
        "(let ((tmp 'local)) (list tmp arg))",
        "(let ((arg 'local)) (list arg tmp))",
    ] {
        let code = library(template);
        assert_eq!(eval_program_vm(&code), "(local lib)", "{code}");
        assert_eq!(eval_program_tree_walker(&code), "(local lib)", "{code}");
    }
}
