(import (scheme base) (scheme eval) (scheme repl) (scheme process-context) (scheme write) (scheme time))
(define-syntax def-counter
  (syntax-rules ()
    ((_ name) (begin (define state 0)
                     (define (name) (set! state (+ state 1)) state)))))
(define n (string->number (cadr (command-line))))
(do ((i 0 (+ i 1))) ((= i n))
  (eval '(def-counter counter) (interaction-environment)))
(define t0 (current-jiffy))
(do ((i 0 (+ i 1))) ((= i 100000)) (counter))
(display (counter)) (display " calls: ")
(display (/ (- (current-jiffy) t0) (/ (jiffies-per-second) 1000.))) (display " ms") (newline)
