(import (scheme base) (scheme eval) (scheme repl) (scheme process-context) (scheme write) (scheme time))
(define env (interaction-environment))
(eval '(define-syntax def-counter
         (syntax-rules ()
           ((_ name) (begin (define state 0)
                            (define (name) (set! state (+ state 1)) state)))))
      env)
(define n (string->number (cadr (command-line))))
(define t0 (current-jiffy))
(do ((i 0 (+ i 1))) ((= i n))
  (eval '(def-counter counter) env))
(define t1 (current-jiffy))
(define ctr (eval (quote counter) env))
(do ((i 0 (+ i 1))) ((= i 100000)) (ctr))
(define t2 (current-jiffy))
(define (ms a b) (round (/ (* 1000 (- b a)) (jiffies-per-second))))
(display (ctr)) (display " expand-ms ") (display (ms t0 t1))
(display " 100k-calls-ms ") (display (ms t1 t2)) (newline)
