(define n (string->number (cadr (command-line))))
(define env (interaction-environment))
(eval '(define-syntax def-counter
         (syntax-rules ()
           ((_ name) (begin (define state 0)
                            (define (name) (set! state (+ state 1)) state)))))
      env)
(define (now) (let ((t (current-time 'time-monotonic))) (+ (* 1000 (time-second t)) (quotient (time-nanosecond t) 1000000))))
(define t0 (now))
(do ((i 0 (+ i 1))) ((= i n)) (eval '(def-counter counter) env))
(define t1 (now))
(define ctr (eval 'counter env))
(do ((i 0 (+ i 1))) ((= i 100000)) (ctr))
(define t2 (now))
(display (ctr)) (display " expand-ms ") (display (- t1 t0)) (display " 100k-calls-ms ") (display (- t2 t1)) (newline)
