(import (scheme base) (scheme eval) (scheme repl) (scheme process-context)
        (scheme write) (scheme time))
(define env (interaction-environment))
(eval '(define-syntax def-counter
         (syntax-rules ()
           ((_ name) (begin (define state 0)
                            (define (name) (set! state (+ state 1)) state)))))
      env)
(define (ms t) (round (/ (* 1000 (- (current-jiffy) t)) (jiffies-per-second))))
(define n (string->number (cadr (command-line))))
(define t (current-jiffy))
(do ((i 0 (+ i 1))) ((= i n)) (eval '(def-counter counter) env))
(display (ms t)) (display " ms to expand, ")
(define ctr (eval 'counter env))
(set! t (current-jiffy))
(do ((i 0 (+ i 1))) ((= i 100000)) (ctr))
(display (ms t)) (display " ms for 100,000 calls") (newline)
