(define (fib n) (if (< n 2) n (+ (fib (- n 1)) (fib (- n 2)))))
(define (tak x y z) (if (not (< y x)) z (tak (tak (- x 1) y z) (tak (- y 1) z x) (tak (- z 1) x y))))
(define (alloc-churn n)
  (let loop ([i 0] [acc 0])
    (if (= i n) acc
        (let ([l (let build ([k 0] [l '()]) (if (= k 50) l (build (+ k 1) (cons k l))))])
          (loop (+ i 1) (+ acc (length l)))))))
;; pointer stores into an old (surviving) vector: write barrier path
(define old-vec (make-vector 100000 #f))
(collect (collect-maximum-generation))
(define (store-old n)
  (let loop ([i 0])
    (when (< i n)
      (vector-set! old-vec (fxmodulo i 100000) (cons i i))
      (loop (+ i 1)))))
(define old-pairs (let loop ([i 0] [l '()]) (if (= i 100000) l (loop (+ i 1) (cons (list i) l)))))
(collect (collect-maximum-generation))
(define (setcar-old n)
  (let loop ([k 0])
    (when (< k n)
      (let inner ([p old-pairs])
        (unless (null? p) (set-car! (car p) (vector k)) (inner (cdr p))))
      (loop (+ k 1)))))
(define (hash-ops n)
  (let ([h (make-eqv-hashtable)])
    (let loop ([i 0])
      (when (< i n) (hashtable-set! h (fxmodulo i 4096) i) (hashtable-ref h (fxmodulo (* i 7) 4096) #f) (loop (+ i 1))))))
(define (port-ops n)
  (let loop ([i 0])
    (when (< i n)
      (let ([p (open-output-string)])
        (let w ([k 0]) (when (< k 20) (write-char #\a p) (w (+ k 1))))
        (get-output-string p))
      (loop (+ i 1)))))
(define p (make-parameter 0))
(define (param-ops n)
  (let loop ([i 0] [acc 0]) (if (= i n) acc (loop (+ i 1) (+ acc (p))))))
(define (run name thunk)
  (collect)
  (let ([t0 (real-time)] [c0 (cpu-time)])
    (thunk)
    (let ([t1 (real-time)] [c1 (cpu-time)])
      (printf "~a\t~a\n" name (- c1 c0)))))
(run "fib40" (lambda () (fib 40)))
(run "tak" (lambda () (do ([i 0 (+ i 1)]) ((= i 12000)) (tak 18 12 6))))
(run "alloc-churn" (lambda () (alloc-churn 12000000)))
(run "store-old" (lambda () (store-old 300000000)))
(run "setcar-old" (lambda () (setcar-old 3000)))
(run "hash-ops" (lambda () (hash-ops 100000000)))
(run "port-ops" (lambda () (port-ops 20000000)))
(run "param-ops" (lambda () (param-ops 1000000000)))
