(import (scheme base) (scheme cxr) (scheme write) (scheme process-context))
(define N (string->number (cadr (command-line))))
(define DEPTH (string->number (caddr (command-line))))
(define (deep n)
  (if (= n 0)
      (call-with-current-continuation (lambda (k) 1))
      (+ 1 (deep (- n 1)))))
(let loop ((i 0) (acc 0))
  (if (< i N)
      (loop (+ i 1) (+ acc (deep DEPTH)))
      (begin (display acc) (newline))))
