(import (scheme base) (scheme cxr) (scheme write) (scheme file) (scheme process-context))
(define N (string->number (cadr (command-line))))
(define path (caddr (command-line)))
(let loop ((i 0))
  (when (< i N)
    (let ((out (open-output-file path)))
      (write i out)
      (close-port out))
    (let ((in (open-input-file path)))
      (read-char in)
      (close-port in))
    (loop (+ i 1))))
(display 'done) (newline)
