(import (scheme base) (scheme write) (scheme time) (scheme process-context) (patina debug))
(define LEN (string->number (cadr (command-line))))
(define (ms) (/ (* 1000.0 (current-jiffy)) (jiffies-per-second)))
(define (avg-gc-ms k)
  ;; (gc) requests a collection at the next safe point; the cons forces one
  (let loop ((i 0) (total 0.0))
    (if (= i k)
        (/ total k)
        (let ((t0 (ms)))
          (gc) (cons 1 2)
          (loop (+ i 1) (+ total (- (ms) t0)))))))
(define (build n) (let loop ((i 0) (acc '())) (if (= i n) acc (loop (+ i 1) (cons (vector i i) acc)))))
(display "before peak: ") (display (avg-gc-ms 20)) (newline)
(define big (build LEN))
(display "at peak (live): ") (display (avg-gc-ms 5)) (newline)
(set! big #f)
(display "after drop: ") (display (avg-gc-ms 20)) (newline)
(display (cdr (assq 'pairs (gc-stats)))) (display " pair slots, ")
(display (cdr (assq 'free-pairs (gc-stats)))) (display " free") (newline)
