(import (scheme base) (scheme cxr) (scheme write) (scheme process-context) (scheme time))
(define LEN (string->number (cadr (command-line))))
(define SECONDS (string->number (caddr (command-line))))
(define (build n) (let loop ((i 0) (acc '())) (if (= i n) acc (loop (+ i 1) (cons (vector i i) acc)))))
(define big (build LEN))
(display (length big)) (newline)
(set! big #f)
(define start (current-jiffy))
(let loop ((i 0) (acc '()))
  (if (> (- (current-jiffy) start) (* SECONDS (jiffies-per-second)))
      (begin (display i) (newline))
      (loop (+ i 1) (if (= 0 (modulo i 1000)) '() (cons i acc)))))
