(import (scheme base) (scheme write) (scheme read) (scheme process-context))
(define N (string->number (cadr (command-line))))
(let loop ((i 0) (acc 0))
  (if (< i N)
      (let ((out (open-output-string)))
        (write (list i "abc" 'sym (vector 1 2 3)) out)
        (let* ((s (get-output-string out))
               (in (open-input-string s))
               (d (read in)))
          (close-port in)
          (close-port out)
          (loop (+ i 1) (+ acc (car d)))))
      (begin (display acc) (newline))))
