(import (scheme base) (scheme write) (scheme eval) (scheme repl) (scheme process-context))
(define N (string->number (cadr (command-line))))
(define env (interaction-environment))
(let loop ((i 0))
  (when (< i N)
    (eval '(define-record-type point (make-point x y) point? (x point-x) (y point-y)) env)
    (eval '(point-x (make-point 1 2)) env)
    (loop (+ i 1))))
(display 'done) (newline)
