(import (scheme base) (scheme write) (scheme time))
(define n 5000000)
(define (go)
  (let ((p (open-output-string)))
    (do ((i 0 (+ i 1))) ((= i n)) (write-char #\a p))
    (string-length (get-output-string p))))
(define (loop-only)
  (do ((i 0 (+ i 1))) ((= i n)) #t))
(define t0 (current-jiffy))
(loop-only)
(define t1 (current-jiffy))
(go)
(define t2 (current-jiffy))
(display (list 'loop-ns-per-iter (/ (* 1e9 (/ (- t1 t0) (jiffies-per-second))) n)
               'write-char-loop-ns-per-iter (/ (* 1e9 (/ (- t2 t1) (jiffies-per-second))) n)))
(newline)
