;; Run from a separate project directory with the pinned adaptation supplied:
;; patina --isolated-libraries -A /path/to/patina-source/test-lib main.scm
;; Creates and removes only the new filesystem-demo-work directory below cwd.
(import (scheme base) (scheme write)
        (only (scheme file) call-with-input-file call-with-output-file)
        (chibi filesystem))

(define (check condition message)
  (unless condition (error message)))

(let ((root "filesystem-demo-work")
      (before (current-directory)))
  (check (not (file-exists? root)) "demo directory already exists")
  (create-directory root)
  (create-directory* (string-append root "/nested/child"))
  (let ((file (string-append root "/nested/child/message.txt")))
    (call-with-output-file file (lambda (out) (display "hello from Patina" out)))
    (check (file-regular? file) "file was not created")
    (check (equal? (call-with-input-file file read-line) "hello from Patina")
           "file contents differ")
    (check (member "message.txt" (directory-files (string-append root "/nested/child")))
           "directory listing missed the file"))
  (check (= 1 (directory-fold root (lambda (name count) (+ count 1)) 0))
         "directory-fold did not skip dot entries")
  (check (= 1 (directory-fold-tree root #f #f (lambda (file count) (+ count 1)) 0))
         "recursive traversal missed the file")
  (check (with-directory root (lambda () (file-directory? "nested/child")))
         "with-directory did not change directories")
  (check (equal? before (current-directory)) "directory was not restored")
  (check (guard (e ((and (error-object? e)
                        (equal? (error-object-message e) "demo unwind")) #t)
                   (else (raise e)))
           (with-directory root (lambda () (error "demo unwind")))
           #f)
         "expected a caught exception")
  (check (equal? before (current-directory)) "directory was not restored after exception")
  ;; Importing this library does not imply that its POSIX layer is implemented.
  (check (guard (e ((and (error-object? e)
                        (equal? (error-object-message e)
                                "requires FFI, unavailable in Patina:")) #t)
                   (else (raise e)))
           (file-status root)
           #f)
         "expected the documented FFI limitation")
  (delete-file-hierarchy root)
  (check (not (file-exists? root)) "demo directory was not removed")
  (write '(filesystem-ok ffi-unavailable))
  (newline))
