(import (scheme base) (scheme write) (scheme eval) (scheme process-context))
(define n (string->number (cadr (command-line))))
(let loop ((i 0))
  (when (< i n)
    (environment '(scheme base))
    (loop (+ i 1))))
(display "done") (newline)
