(import (scheme base) (scheme write))
(define other #f)
(define (switch!) (call/cc (lambda (k) (let ((o other)) (set! other k) (o #f)))))
(define (producer n) (if (> n 0) (begin (switch!) (producer (- n 1))) 'done))
(define (consumer n) (if (> n 0) (begin (switch!) (consumer (- n 1))) 'done))
(define (deep d thunk) (if (= d 0) (thunk) (let ((r (deep (- d 1) thunk))) r)))
(define (main)
  (call/cc (lambda (exit)
    (set! other (lambda (ignored) (deep 1 (lambda () (consumer 20000) (exit 'c)))))
    (producer 20000)
    'p)))
(display (deep 1000 main))
