(import (scheme base) (scheme write) (scheme time) (patina debug)
        (scheme list) (scheme hash-table) (scheme char) (scheme comparator) (scheme generator)
        (scheme set) (scheme sort) (scheme vector) (scheme text) (scheme ideque) (scheme ilist)
        (scheme rlist) (scheme mapping) (scheme stream) (scheme show) (scheme regex) (scheme charset)
        (scheme lseq) (scheme bytevector) (scheme flonum) (scheme fixnum) (scheme bitwise))
(define (stat k) (cdr (assq k (gc-stats))))
(define (time-gc label)
  (let ((t0 (current-jiffy)))
    (gc)
    (let ((t1 (current-jiffy)))
      (display label) (display ": ") (display (- t1 t0)) (display " us  pairs=") (display (stat 'pairs))
      (display " objects=") (display (stat 'objects)) (display " free-objects=") (display (stat 'free-objects))
      (display " free-pairs=") (display (stat (quote free-pairs))) (display " vectors=") (display (stat 'vectors)) (display " strings=") (display (stat 'strings)) (newline))))
(time-gc "1") (time-gc "2") (time-gc "3") (time-gc "4")
