(import (scheme base) (scheme write) (scheme time) (patina debug))
(define (stat k) (cdr (assq k (gc-stats))))
(define (time-gc label)
  (let ((t0 (current-jiffy)))
    (gc)
    (let ((t1 (current-jiffy)))
      (display label) (display ": ")
      (display (/ (* 1000000 (- t1 t0)) (jiffies-per-second)))
      (display " us  pairs=") (display (stat 'pairs))
      (display " objects=") (display (stat 'objects))
      (display " vectors=") (display (stat 'vectors))
      (display " strings=") (display (stat 'strings))
      (display " symbols=") (display (stat 'symbols))
      (display " collections=") (display (stat 'collections))
      (newline))))
(time-gc "warm1")
(time-gc "empty-ish heap")
(time-gc "empty-ish heap again")
(define big (let loop ((i 0) (acc '())) (if (= i 1000000) acc (loop (+ i 1) (cons i acc)))))
(time-gc "1M live pairs (1st)")
(time-gc "1M live pairs (2nd)")
(define vecs (let loop ((i 0) (acc '())) (if (= i 100000) acc (loop (+ i 1) (cons (make-vector 8 i) acc)))))
(time-gc "+100k live 8-vectors")
(define flos (let loop ((i 0) (acc '())) (if (= i 200000) acc (loop (+ i 1) (cons (* 1.5 i) acc)))))
(time-gc "+200k live flonums")
(set! big #f) (set! vecs #f) (set! flos #f)
(time-gc "after dropping all")
(time-gc "steady")
